function reproduce_introduction_pof_figures
%REPRODUCE_INTRODUCTION_POF_FIGURES Reproduce the two Introduction figures.
%   Run this file after opening the cTSEMO repository in MATLAB. It
%   regenerates both PoF figures and the pointwise synthetic-margin table,
%   checks their numerical consistency, and displays both saved figures.

entryDirectory = fileparts(mfilename("fullpath"));
pathBeforeRun = path;
restorePath = onCleanup(@() path(pathBeforeRun));
figureVisibilityBeforeRun = get(groot, "DefaultFigureVisible");
restoreFigureVisibility = onCleanup(@() set( ...
    groot, "DefaultFigureVisible", figureVisibilityBeforeRun));
addpath(entryDirectory, "-begin");

run_introduction_pof_comparison;

outputDirectory = fullfile(entryDirectory, "output");
tablePath = fullfile( ...
    outputDirectory, "synthetic_constraint_margins.csv");
atlasPath = fullfile(outputDirectory, "table1_pof_atlas.png");
comparisonPath = fullfile( ...
    outputDirectory, "gpc_ctsemo_pof_comparison.png");
assert(isfile(tablePath), ...
    "The pointwise synthetic-margin table was not generated.");
assert(isfile(atlasPath), ...
    "The Figure 1 atlas was not generated.");
assert(isfile(comparisonPath), ...
    "The Figure 2 comparison was not generated.");

pointwiseData = readtable(tablePath);
requiredVariables = [ ...
    "x1", "x2", "AnalyticG1", "AnalyticG2", ...
    "SyntheticG1", "SyntheticG2", ...
    "Phi1AtObservation", "Phi2AtObservation", ...
    "ProductPoFAtObservation", "AggregateFeasible"];
assert(all(ismember(requiredVariables, ...
    string(pointwiseData.Properties.VariableNames))), ...
    "The generated pointwise table has an unexpected schema.");
assert(height(pointwiseData) == 40, ...
    "The generated table must contain all 40 sampled designs.");

individualProbability = [ ...
    pointwiseData.Phi1AtObservation, ...
    pointwiseData.Phi2AtObservation];
assert(all(isfinite(individualProbability), "all"), ...
    "An individual satisfaction probability is not finite.");
assert(all(individualProbability > 0 & ...
    individualProbability < 1, "all"), ...
    "An individual satisfaction probability reached zero or one.");

reconstructedProduct = prod(individualProbability, 2);
productTolerance = 1e-12;
assert(all(abs(reconstructedProduct - ...
    pointwiseData.ProductPoFAtObservation) <= productTolerance), ...
    "A stored product PoF does not equal Phi1 times Phi2.");

analyticConstraintStatus = [ ...
    pointwiseData.AnalyticG1 <= 0, ...
    pointwiseData.AnalyticG2 <= 0];
syntheticConstraintStatus = [ ...
    pointwiseData.SyntheticG1 <= 0, ...
    pointwiseData.SyntheticG2 <= 0];
assert(isequal(analyticConstraintStatus, syntheticConstraintStatus), ...
    "A synthetic margin does not preserve its analytic constraint sign.");
assert(isequal(all(syntheticConstraintStatus, 2), ...
    logical(pointwiseData.AggregateFeasible)), ...
    "A synthetic-margin pair does not preserve its aggregate label.");

fprintf("Introduction PoF figure reproduction verified.\n");
fprintf("  sampled designs: %d\n", height(pointwiseData));
fprintf("  Phi1 at observations: %.6f to %.6f\n", ...
    min(individualProbability(:, 1)), ...
    max(individualProbability(:, 1)));
fprintf("  Phi2 at observations: %.6f to %.6f\n", ...
    min(individualProbability(:, 2)), ...
    max(individualProbability(:, 2)));
fprintf("  product PoF at observations: %.6f to %.6f\n", ...
    min(pointwiseData.ProductPoFAtObservation), ...
    max(pointwiseData.ProductPoFAtObservation));
fprintf("  output directory: %s\n", outputDirectory);

atlasImage = imread(atlasPath);
atlasFigure = figure( ...
    "Name", "Reproduced manuscript Figure 1", ...
    "Color", "w", ...
    "Visible", "on");
atlasAxes = axes(atlasFigure);
image(atlasAxes, atlasImage);
axis(atlasAxes, "image");
axis(atlasAxes, "off");
title(atlasAxes, "Reproduced manuscript Figure 1 PoF atlas");

comparisonImage = imread(comparisonPath);
comparisonFigure = figure( ...
    "Name", "Reproduced manuscript Figure 2", ...
    "Color", "w", ...
    "Visible", "on");
comparisonAxes = axes(comparisonFigure);
image(comparisonAxes, comparisonImage);
axis(comparisonAxes, "image");
axis(comparisonAxes, "off");
title(comparisonAxes, ...
    "Reproduced manuscript Figure 2 PoF comparison");

clear restoreFigureVisibility restorePath
end
