function run_introduction_pof_comparison
%RUN_INTRODUCTION_POF_COMPARISON Create matched PoF illustrations.
%   The script uses one fixed two-dimensional design and one analytic
%   two-constraint feasibility problem. The product-GP reference receives
%   both continuous constraint margins. Every other fitted field receives
%   only the same aggregate feasible/violating labels.

close all force;
set(groot, "DefaultFigureVisible", "off");
previousRandomState = rng;
restoreRandomState = onCleanup(@() rng(previousRandomState));
rng(20260728, "twister");

analysisDirectory = fileparts(mfilename("fullpath"));
repositoryDirectory = fileparts(fileparts(analysisDirectory));
sourceDirectory = fullfile(repositoryDirectory, "src");
outputDirectory = fullfile(analysisDirectory, "output");
assert(isfolder(sourceDirectory), ...
    "The cTSEMO source directory was not found.");
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
pathBeforeRun = path;
restorePath = onCleanup(@() path(pathBeforeRun));
addpath(sourceDirectory, "-begin");

trainingCount = 40;
xTraining = lhsdesign(trainingCount, 2, ...
    "Criterion", "maximin", "Iterations", 100);
[gTraining, yTraining] = evaluateSyntheticConstraints(xTraining);
assert(nnz(yTraining) >= 8 && nnz(~yTraining) >= 8, ...
    "The fixed design does not contain enough observations of both labels.");

axisValues = linspace(0, 1, 181);
[x1Grid, x2Grid] = meshgrid(axisValues, axisValues);
xQuery = [x1Grid(:), x2Grid(:)];
[~, yQuery] = evaluateSyntheticConstraints(xQuery);
gridSize = size(x1Grid);
truthGrid = reshape(double(yQuery), gridSize);

% Information-richer conventional reference: one GP per continuous margin.
constraintGpModels = cell(2, 1);
constraintMean = zeros(size(xQuery, 1), 2);
constraintStd = zeros(size(xQuery, 1), 2);
for constraintIndex = 1:2
    constraintGpModels{constraintIndex} = fitContinuousMarginGp( ...
        xTraining, gTraining(:, constraintIndex));
    [constraintMean(:, constraintIndex), ...
        constraintStd(:, constraintIndex)] = ...
        predictContinuousMarginGp( ...
        constraintGpModels{constraintIndex}, xQuery);
end
productPof = prod(normalCdf( ...
    -constraintMean ./ max(constraintStd, 1e-12)), 2);

% Bernoulli-logistic GP classifier with a Laplace approximation.
lengthScaleGrid = [0.06 0.09 0.13 0.18 0.25 0.35 0.50];
signalStdGrid = [0.50 0.75 1.00 1.50 2.25 3.50];
[gpcModel, gpcNegativeLogEvidence] = selectLaplaceLogisticGp( ...
    xTraining, yTraining, lengthScaleGrid, signalStdGrid);
gpcPof = predictLaplaceLogisticGp(gpcModel, xQuery);

% RBF support-vector machine followed by MATLAB's posterior calibration.
rng(20260729, "twister");
svmModel = fitcsvm(xTraining, yTraining, ...
    "KernelFunction", "gaussian", ...
    "KernelScale", "auto", ...
    "BoxConstraint", 0.75, ...
    "Standardize", true, ...
    "ClassNames", [false true]);
warningState = warning("off", "stats:fitSVMPosterior:PerfectSeparation");
restoreWarning = onCleanup(@() warning(warningState));
svmPosteriorModel = fitPosterior(svmModel, xTraining, yTraining);
svmPof = positiveClassScore(svmPosteriorModel, xQuery);
clear restoreWarning

% Random-forest vote/probability proxy.
rng(20260730, "twister");
treeTemplate = templateTree( ...
    "MinLeafSize", 2, ...
    "NumVariablesToSample", 2);
forestModel = fitcensemble(xTraining, yTraining, ...
    "Method", "Bag", ...
    "NumLearningCycles", 200, ...
    "Learners", treeTemplate, ...
    "ClassNames", [false true]);
forestPof = positiveClassScore(forestModel, xQuery);

% Gaussian-weighted seven-nearest-neighbour field.
knnNeighbourCount = 7;
knnBandwidth = estimateKnnBandwidth(xTraining, knnNeighbourCount);
knnPof = predictWeightedKnn( ...
    xTraining, yTraining, xQuery, ...
    knnNeighbourCount, knnBandwidth);

% Small bootstrapped neural-classifier ensemble.
networkCount = 8;
networkPof = zeros(size(xQuery, 1), 1);
networkModels = cell(networkCount, 1);
for networkIndex = 1:networkCount
    rng(20260800 + networkIndex, "twister");
    bootstrapIndex = balancedBootstrap(yTraining);
    networkModels{networkIndex} = fitcnet( ...
        xTraining(bootstrapIndex, :), ...
        yTraining(bootstrapIndex), ...
        "LayerSizes", [10 6], ...
        "Activations", "tanh", ...
        "Lambda", 0.02, ...
        "IterationLimit", 350, ...
        "Standardize", true, ...
        "ClassNames", [false true]);
    networkPof = networkPof + positiveClassScore( ...
        networkModels{networkIndex}, xQuery);
end
networkPof = networkPof ./ networkCount;

% Shipped cTSEMO operational field, including exact stored-anchor snapping.
ctsemoOptions = cTSEMOOptions();
[ctsemoModel, ctsemoFitDiagnostics] = ...
    ctsemo.fitClippedBinaryPof( ...
        xTraining, yTraining, ctsemoOptions);
[ctsemoPof, ctsemoRawMean] = ...
    ctsemo.predictClippedBinaryPof(ctsemoModel, xQuery);

methodNames = [ ...
    "Constraint-wise GP product"; ...
    "Bernoulli GP classification"; ...
    "Probabilistic RBF SVM"; ...
    "Random-forest vote fraction"; ...
    "Weighted 7-nearest neighbours"; ...
    "Neural-network ensemble"; ...
    "cTSEMO clipped GP mean"];
methodScores = { ...
    productPof; ...
    gpcPof; ...
    svmPof; ...
    forestPof; ...
    knnPof; ...
    networkPof; ...
    ctsemoPof};
methodAnchorScores = { ...
    predictProductPofAt( ...
        constraintGpModels, xTraining); ...
    predictLaplaceLogisticGp(gpcModel, xTraining); ...
    positiveClassScore(svmPosteriorModel, xTraining); ...
    positiveClassScore(forestModel, xTraining); ...
    predictWeightedKnn( ...
        xTraining, yTraining, xTraining, ...
        knnNeighbourCount, knnBandwidth); ...
    predictNetworkEnsemble(networkModels, xTraining); ...
    ctsemo.predictClippedBinaryPof(ctsemoModel, xTraining)};

metrics = calculateMetrics( ...
    methodNames, methodScores, methodAnchorScores, ...
    yQuery, yTraining);
writetable(metrics, fullfile(outputDirectory, ...
    "pof_field_metrics.csv"));

atlasFields = methodScores(1:6);
atlasTitles = { ...
    "(a) Constraint-wise GP product", ...
    "(b) Bernoulli GP classification", ...
    "(c) Probabilistic RBF SVM", ...
    "(d) Random-forest vote fraction", ...
    "(e) Weighted 7-nearest neighbours", ...
    "(f) Neural-network ensemble"};
atlasDetails = { ...
    "Uses both continuous constraint margins", ...
    sprintf("Binary labels; ell = %.2f, sigma_f = %.2f", ...
        gpcModel.lengthScale, gpcModel.signalStd), ...
    "Binary labels; calibrated classifier score", ...
    "Binary labels; 200 bagged trees", ...
    sprintf("Binary labels; k = 7, bandwidth = %.3f", ...
        knnBandwidth), ...
    "Binary labels; mean of 8 classifiers"};
atlasFigure = makeAtlasFigure( ...
    x1Grid, x2Grid, truthGrid, ...
    xTraining, yTraining, ...
    atlasFields, atlasTitles, atlasDetails);
atlasBase = fullfile(outputDirectory, "table1_pof_atlas");
exportgraphics(atlasFigure, atlasBase + ".png", ...
    "Resolution", 300);
exportgraphics(atlasFigure, atlasBase + ".pdf", ...
    "ContentType", "vector");
close(atlasFigure);

comparisonFields = {gpcPof, ctsemoPof};
comparisonTitles = { ...
    "(a) Bernoulli GP classification", ...
    "(b) cTSEMO clipped GP mean"};
comparisonDetails = { ...
    "Posterior class probability; no forced anchors", ...
    "Exterior targets; clip [0,1]; exact stored anchors"};
comparisonFigure = makeComparisonFigure( ...
    x1Grid, x2Grid, truthGrid, ...
    xTraining, yTraining, ...
    comparisonFields, comparisonTitles, comparisonDetails);
comparisonBase = fullfile(outputDirectory, ...
    "gpc_ctsemo_pof_comparison");
exportgraphics(comparisonFigure, comparisonBase + ".png", ...
    "Resolution", 300);
exportgraphics(comparisonFigure, comparisonBase + ".pdf", ...
    "ContentType", "vector");
close(comparisonFigure);

save(fullfile(outputDirectory, "pof_comparison_data.mat"), ...
    "xTraining", "yTraining", "gTraining", ...
    "x1Grid", "x2Grid", "truthGrid", ...
    "constraintGpModels", "gpcModel", ...
    "svmPosteriorModel", "forestModel", ...
    "knnNeighbourCount", "knnBandwidth", ...
    "ctsemoModel", "ctsemoFitDiagnostics", ...
    "ctsemoRawMean", "methodNames", "methodScores", ...
    "methodAnchorScores", "metrics", ...
    "gpcNegativeLogEvidence", "-v7.3");
writeSummary( ...
    fullfile(outputDirectory, "SUMMARY.txt"), ...
    xTraining, yTraining, methodNames, metrics, ...
    gpcModel, gpcNegativeLogEvidence, ...
    knnBandwidth, ctsemoOptions, ...
    ctsemoFitDiagnostics);

fprintf("Created %s.[png|pdf]\n", atlasBase);
fprintf("Created %s.[png|pdf]\n", comparisonBase);
clear restorePath restoreRandomState
end

function [constraintMargins, isFeasible] = ...
        evaluateSyntheticConstraints(x)
g1 = x(:, 2) - (0.62 + 0.16 .* sin(2 .* pi .* x(:, 1)));
g2 = (0.18 + 0.07 .* cos(2 .* pi .* x(:, 2))) - x(:, 1);
constraintMargins = [g1, g2];
isFeasible = all(constraintMargins <= 0, 2);
end

function model = fitContinuousMarginGp(x, response)
responseMean = mean(response);
responseScale = std(response);
if responseScale <= 100 * eps
    responseScale = 1;
end
standardizedResponse = (response - responseMean) ./ responseScale;
lengthScaleGrid = [0.06 0.09 0.13 0.18 0.25 0.35 0.50];
signalStdGrid = [0.70 1.00 1.40];
noiseStd = 0.05;
bestNegativeLogLikelihood = inf;
bestModel = struct();
for lengthScale = lengthScaleGrid
    for signalStd = signalStdGrid
        kernel = matern32Kernel( ...
            x, x, lengthScale, signalStd);
        kernel = kernel + noiseStd.^2 .* eye(size(x, 1));
        [choleskyFactor, flag] = chol(kernel, "lower");
        if flag ~= 0
            continue
        end
        coefficient = choleskyFactor' \ ...
            (choleskyFactor \ standardizedResponse);
        negativeLogLikelihood = ...
            0.5 .* standardizedResponse' * coefficient + ...
            sum(log(diag(choleskyFactor))) + ...
            0.5 * size(x, 1) * log(2 * pi);
        if negativeLogLikelihood < bestNegativeLogLikelihood
            bestNegativeLogLikelihood = negativeLogLikelihood;
            bestModel = struct( ...
                "xTraining", x, ...
                "responseMean", responseMean, ...
                "responseScale", responseScale, ...
                "lengthScale", lengthScale, ...
                "signalStd", signalStd, ...
                "noiseStd", noiseStd, ...
                "choleskyFactor", choleskyFactor, ...
                "coefficient", coefficient, ...
                "negativeLogLikelihood", ...
                negativeLogLikelihood);
        end
    end
end
assert(~isempty(fieldnames(bestModel)), ...
    "No continuous-margin GP candidate was numerically valid.");
model = bestModel;
end

function [posteriorMean, posteriorStd] = ...
        predictContinuousMarginGp(model, xQuery)
crossKernel = matern32Kernel( ...
    model.xTraining, xQuery, ...
    model.lengthScale, model.signalStd);
standardizedMean = crossKernel' * model.coefficient;
projection = model.choleskyFactor \ crossKernel;
standardizedVariance = max( ...
    1e-14, model.signalStd.^2 - sum(projection.^2, 1)');
posteriorMean = model.responseMean + ...
    model.responseScale .* standardizedMean;
posteriorStd = model.responseScale .* ...
    sqrt(standardizedVariance);
end

function pof = predictProductPofAt(models, xQuery)
probability = ones(size(xQuery, 1), 1);
for constraintIndex = 1:numel(models)
    [posteriorMean, posteriorStd] = ...
        predictContinuousMarginGp( ...
            models{constraintIndex}, xQuery);
    probability = probability .* normalCdf( ...
        -posteriorMean ./ max(posteriorStd, 1e-12));
end
pof = min(1, max(0, probability));
end

function [bestModel, bestNegativeLogEvidence] = ...
        selectLaplaceLogisticGp( ...
        x, labels, lengthScaleGrid, signalStdGrid)
bestNegativeLogEvidence = inf;
bestModel = struct();
for lengthScale = lengthScaleGrid
    for signalStd = signalStdGrid
        [candidateModel, negativeLogEvidence] = ...
            fitLaplaceLogisticGp( ...
                x, labels, lengthScale, signalStd);
        if negativeLogEvidence < bestNegativeLogEvidence
            bestNegativeLogEvidence = negativeLogEvidence;
            bestModel = candidateModel;
        end
    end
end
assert(~isempty(fieldnames(bestModel)), ...
    "No Laplace-logistic GP candidate was numerically valid.");
end

function [model, negativeLogEvidence] = ...
        fitLaplaceLogisticGp(x, labels, lengthScale, signalStd)
observationCount = size(x, 1);
kernel = matern32Kernel(x, x, lengthScale, signalStd);
kernel = kernel + 1e-9 .* eye(observationCount);
latent = zeros(observationCount, 1);

for iteration = 1:80
    probability = stableLogistic(latent);
    weight = max(probability .* (1 - probability), 1e-10);
    squareRootWeight = sqrt(weight);
    systemMatrix = eye(observationCount) + ...
        kernel .* (squareRootWeight * squareRootWeight');
    choleskyFactor = chol(systemMatrix, "lower");
    rhs = weight .* latent + double(labels) - probability;
    kernelRhs = kernel * rhs;
    correction = choleskyFactor' \ ...
        (choleskyFactor \ (squareRootWeight .* kernelRhs));
    coefficient = rhs - squareRootWeight .* correction;
    updatedLatent = kernel * coefficient;
    if max(abs(updatedLatent - latent)) < 1e-9
        latent = updatedLatent;
        break
    end
    latent = updatedLatent;
end

probability = stableLogistic(latent);
weight = max(probability .* (1 - probability), 1e-10);
squareRootWeight = sqrt(weight);
systemMatrix = eye(observationCount) + ...
    kernel .* (squareRootWeight * squareRootWeight');
choleskyFactor = chol(systemMatrix, "lower");
rhs = weight .* latent + double(labels) - probability;
kernelRhs = kernel * rhs;
coefficient = rhs - squareRootWeight .* ...
    (choleskyFactor' \ ...
    (choleskyFactor \ (squareRootWeight .* kernelRhs)));

probability = min(1 - eps, max(eps, probability));
logLikelihood = double(labels) .* log(probability) + ...
    (1 - double(labels)) .* log1p(-probability);
negativeLogEvidence = 0.5 .* coefficient' * latent - ...
    sum(logLikelihood) + sum(log(diag(choleskyFactor)));

model = struct( ...
    "xTraining", x, ...
    "labels", logical(labels), ...
    "lengthScale", lengthScale, ...
    "signalStd", signalStd, ...
    "coefficient", coefficient, ...
    "squareRootWeight", squareRootWeight, ...
    "choleskyFactor", choleskyFactor);
end

function probability = predictLaplaceLogisticGp(model, xQuery)
crossKernel = matern32Kernel( ...
    model.xTraining, xQuery, ...
    model.lengthScale, model.signalStd);
latentMean = crossKernel' * model.coefficient;
projectedKernel = model.choleskyFactor \ ...
    (model.squareRootWeight .* crossKernel);
latentVariance = max(0, model.signalStd.^2 - ...
    sum(projectedKernel.^2, 1)');
scaledMean = latentMean ./ sqrt(1 + pi .* latentVariance ./ 8);
probability = stableLogistic(scaledMean);
end

function kernel = matern32Kernel(x1, x2, lengthScale, signalStd)
distanceSquared = sum(x1.^2, 2) + sum(x2.^2, 2)' - ...
    2 .* (x1 * x2');
distance = sqrt(max(0, distanceSquared));
scaledDistance = sqrt(3) .* distance ./ lengthScale;
kernel = signalStd.^2 .* ...
    (1 + scaledDistance) .* exp(-scaledDistance);
end

function probability = stableLogistic(value)
probability = zeros(size(value));
nonnegative = value >= 0;
probability(nonnegative) = ...
    1 ./ (1 + exp(-value(nonnegative)));
exponential = exp(value(~nonnegative));
probability(~nonnegative) = ...
    exponential ./ (1 + exponential);
end

function probability = normalCdf(value)
probability = 0.5 .* erfc(-value ./ sqrt(2));
end

function probability = positiveClassScore(model, xQuery)
[~, score] = predict(model, xQuery);
classNames = model.ClassNames;
positiveColumn = find(logical(classNames), 1);
if isempty(positiveColumn)
    positiveColumn = find(string(classNames) == "1", 1);
end
assert(~isempty(positiveColumn), ...
    "The positive class was not found in the classifier.");
probability = score(:, positiveColumn);
probability = min(1, max(0, probability));
end

function bandwidth = estimateKnnBandwidth(xTraining, neighbourCount)
distance = pairwiseDistance(xTraining, xTraining);
distance(1:(size(distance, 1) + 1):end) = inf;
sortedDistance = sort(distance, 2, "ascend");
bandwidth = median(sortedDistance(:, neighbourCount));
bandwidth = max(bandwidth, 1e-6);
end

function probability = predictWeightedKnn( ...
        xTraining, labels, xQuery, neighbourCount, bandwidth)
distance = pairwiseDistance(xQuery, xTraining);
[sortedDistance, sortedIndex] = sort(distance, 2, "ascend");
selectedDistance = sortedDistance(:, 1:neighbourCount);
selectedLabels = double(labels(sortedIndex(:, 1:neighbourCount)));
weight = exp(-0.5 .* (selectedDistance ./ bandwidth).^2);
probability = sum(weight .* selectedLabels, 2) ./ ...
    max(sum(weight, 2), realmin);
probability = min(1, max(0, probability));
end

function distance = pairwiseDistance(x1, x2)
distanceSquared = sum(x1.^2, 2) + sum(x2.^2, 2)' - ...
    2 .* (x1 * x2');
distance = sqrt(max(0, distanceSquared));
end

function index = balancedBootstrap(labels)
observationCount = numel(labels);
for attempt = 1:100
    index = randi(observationCount, observationCount, 1);
    if numel(unique(labels(index))) == 2
        return
    end
end
error("Could not draw a bootstrap sample containing both labels.");
end

function probability = predictNetworkEnsemble(models, xQuery)
probability = zeros(size(xQuery, 1), 1);
for modelIndex = 1:numel(models)
    probability = probability + ...
        positiveClassScore(models{modelIndex}, xQuery);
end
probability = probability ./ numel(models);
end

function metrics = calculateMetrics( ...
        methodNames, methodScores, methodAnchorScores, ...
        truth, trainingLabels)
methodCount = numel(methodNames);
minimum = zeros(methodCount, 1);
maximum = zeros(methodCount, 1);
anchorMaximumError = zeros(methodCount, 1);
brierScore = zeros(methodCount, 1);
auc = zeros(methodCount, 1);
falseFeasibleAtTwoThirds = zeros(methodCount, 1);
falseInfeasibleAtOneThird = zeros(methodCount, 1);
for methodIndex = 1:methodCount
    score = min(1, max(0, double(methodScores{methodIndex}(:))));
    anchorScore = min(1, max(0, ...
        double(methodAnchorScores{methodIndex}(:))));
    minimum(methodIndex) = min(score);
    maximum(methodIndex) = max(score);
    anchorMaximumError(methodIndex) = ...
        max(abs(anchorScore - double(trainingLabels)));
    brierScore(methodIndex) = ...
        mean((score - double(truth)).^2);
    auc(methodIndex) = rocAuc(truth, score);
    falseFeasibleAtTwoThirds(methodIndex) = ...
        mean(score(~truth) > 2 / 3);
    falseInfeasibleAtOneThird(methodIndex) = ...
        mean(score(truth) < 1 / 3);
end
metrics = table( ...
    methodNames, minimum, maximum, anchorMaximumError, ...
    brierScore, auc, ...
    falseFeasibleAtTwoThirds, falseInfeasibleAtOneThird, ...
    VariableNames=[ ...
    "Method", "Minimum", "Maximum", "AnchorMaximumError", ...
    "BrierScore", "AUC", ...
    "FalseFeasibleAtTwoThirds", ...
    "FalseInfeasibleAtOneThird"]);
end

function value = rocAuc(truth, score)
truth = logical(truth(:));
score = double(score(:));
positiveCount = nnz(truth);
negativeCount = nnz(~truth);
if positiveCount == 0 || negativeCount == 0
    value = NaN;
    return
end
[~, order] = sort(score, "ascend");
rank = zeros(size(score));
rank(order) = 1:numel(score);
[uniqueScore, ~, group] = unique(score);
if numel(uniqueScore) < numel(score)
    for groupIndex = 1:numel(uniqueScore)
        selected = group == groupIndex;
        rank(selected) = mean(rank(selected));
    end
end
value = (sum(rank(truth)) - ...
    positiveCount .* (positiveCount + 1) ./ 2) ./ ...
    (positiveCount .* negativeCount);
end

function figureHandle = makeAtlasFigure( ...
        x1Grid, x2Grid, truthGrid, ...
        xTraining, yTraining, ...
        fields, panelTitles, panelDetails)
figureHandle = figure( ...
    "Color", "w", ...
    "Units", "inches", ...
    "Position", [0.25 0.25 7.2 8.6]);
layout = tiledlayout(figureHandle, 3, 2, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");
for panelIndex = 1:numel(fields)
    axesHandle = nexttile(layout, panelIndex);
    plotFeasibilityField( ...
        axesHandle, x1Grid, x2Grid, truthGrid, ...
        reshape(fields{panelIndex}, size(x1Grid)), ...
        xTraining, yTraining);
    title(axesHandle, panelTitles{panelIndex}, ...
        "FontWeight", "bold", "FontSize", 12);
    subtitle(axesHandle, panelDetails{panelIndex}, ...
        "FontSize", 9.5);
end
styleFigure(figureHandle);
end

function figureHandle = makeComparisonFigure( ...
        x1Grid, x2Grid, truthGrid, ...
        xTraining, yTraining, ...
        fields, panelTitles, panelDetails)
figureHandle = figure( ...
    "Color", "w", ...
    "Units", "inches", ...
    "Position", [0.25 0.25 10.0 5.4]);
layout = tiledlayout(figureHandle, 1, 2, ...
    "TileSpacing", "compact", ...
    "Padding", "compact");
for panelIndex = 1:numel(fields)
    axesHandle = nexttile(layout, panelIndex);
    plotFeasibilityField( ...
        axesHandle, x1Grid, x2Grid, truthGrid, ...
        reshape(fields{panelIndex}, size(x1Grid)), ...
        xTraining, yTraining);
    title(axesHandle, panelTitles{panelIndex}, ...
        "FontWeight", "bold", "FontSize", 12);
    subtitle(axesHandle, panelDetails{panelIndex}, ...
        "FontSize", 9.5);
end
styleFigure(figureHandle);
end

function plotFeasibilityField( ...
        axesHandle, x1Grid, x2Grid, truthGrid, ...
        field, xTraining, yTraining)
imagesc(axesHandle, x1Grid(1, :), x2Grid(:, 1), field);
set(axesHandle, "YDir", "normal");
hold(axesHandle, "on");
contour(axesHandle, x1Grid, x2Grid, field, [0.5 0.5], ...
    "-", "Color", [1 1 1], "LineWidth", 1.1, ...
    "HandleVisibility", "off");
contour(axesHandle, x1Grid, x2Grid, truthGrid, [0.5 0.5], ...
    "--", "Color", [0.08 0.08 0.08], "LineWidth", 1.25, ...
    "HandleVisibility", "off");
scatter(axesHandle, ...
    xTraining(yTraining, 1), xTraining(yTraining, 2), ...
    48, [0.05 0.55 0.25], "o", "filled", ...
    "MarkerEdgeColor", "w", "LineWidth", 0.9, ...
    "HandleVisibility", "off");
plot(axesHandle, ...
    xTraining(~yTraining, 1), xTraining(~yTraining, 2), ...
    "x", "Color", [0.80 0.08 0.08], ...
    "MarkerSize", 7.5, "LineWidth", 1.8, ...
    "HandleVisibility", "off");
hold(axesHandle, "off");
axis(axesHandle, "square");
xlim(axesHandle, [0 1]);
ylim(axesHandle, [0 1]);
xticks(axesHandle, 0:0.2:1);
yticks(axesHandle, 0:0.2:1);
clim(axesHandle, [0 1]);
colormap(axesHandle, turbo(256));
colorbarHandle = colorbar(axesHandle, "eastoutside");
colorbarHandle.Ticks = [0 0.5 1];
colorbarHandle.Label.String = "p_i(x)";
colorbarHandle.Label.Interpreter = "tex";
xlabel(axesHandle, "x_1");
ylabel(axesHandle, "x_2");
grid(axesHandle, "on");
box(axesHandle, "on");
end

function styleFigure(figureHandle)
set(findall(figureHandle, "-property", "FontName"), ...
    "FontName", "Arial");
set(findall(figureHandle, "Type", "axes"), ...
    "FontSize", 10.5, ...
    "LineWidth", 0.8, ...
    "GridAlpha", 0.12, ...
    "Layer", "top");
end

function writeSummary( ...
        pathValue, xTraining, yTraining, ...
        methodNames, metrics, gpcModel, ...
        gpcNegativeLogEvidence, knnBandwidth, ...
        ctsemoOptions, ctsemoFitDiagnostics)
fileId = fopen(pathValue, "w");
assert(fileId >= 0, "Could not open SUMMARY.txt for writing.");
closeFile = onCleanup(@() fclose(fileId));
fprintf(fileId, "Introduction PoF comparison\n");
fprintf(fileId, ...
    "Script: manuscript/introduction_pof_comparison/" + ...
    "run_introduction_pof_comparison.m\n\n");
fprintf(fileId, "Fixed random seed: 20260728\n");
fprintf(fileId, "Training observations: %d\n", size(xTraining, 1));
fprintf(fileId, "Feasible observations: %d\n", nnz(yTraining));
fprintf(fileId, "Violating observations: %d\n\n", nnz(~yTraining));
fprintf(fileId, "%s", ...
    "Constraint-wise product GP alone receives continuous " + ...
    "constraint margins. Every other method receives only the common " + ...
    "aggregate binary labels. The analytic boundary is displayed only " + ...
    "for diagnostics and is not used to tune any field." + newline + newline);
fprintf(fileId, "GPC length scale: %.8g\n", gpcModel.lengthScale);
fprintf(fileId, "GPC signal standard deviation: %.8g\n", ...
    gpcModel.signalStd);
fprintf(fileId, "GPC negative log evidence: %.8g\n", ...
    gpcNegativeLogEvidence);
fprintf(fileId, "Weighted kNN bandwidth: %.8g\n", knnBandwidth);
fprintf(fileId, "cTSEMO raw targets: %.8g, %.8g\n", ...
    ctsemoOptions.pof.rawInfeasible, ...
    ctsemoOptions.pof.rawFeasible);
fprintf(fileId, "cTSEMO prior mean: %.8g\n", ...
    ctsemoOptions.pof.priorMean);
fprintf(fileId, ...
    "cTSEMO maximum clipped anchor error before snap: %.8g\n\n", ...
    ctsemoFitDiagnostics.maximumClippedAnchorErrorBeforeSnap);
for methodIndex = 1:numel(methodNames)
    fprintf(fileId, "%s\n", methodNames(methodIndex));
    fprintf(fileId, "  range: %.8g to %.8g\n", ...
        metrics.Minimum(methodIndex), ...
        metrics.Maximum(methodIndex));
    fprintf(fileId, "  maximum anchor error: %.8g\n", ...
        metrics.AnchorMaximumError(methodIndex));
    fprintf(fileId, "  AUC on dense analytic grid: %.8g\n", ...
        metrics.AUC(methodIndex));
    fprintf(fileId, "  Brier score on dense analytic grid: %.8g\n", ...
        metrics.BrierScore(methodIndex));
end
fprintf(fileId, "%s", newline + ...
    "These single-design visual and scalar diagnostics are " + ...
    "descriptive. They do not establish optimizer-level superiority." + ...
    newline);
clear closeFile
end
