function results = run_release_tests
%RUN_RELEASE_TESTS Run the suite and refresh machine-readable test evidence.

repositoryRoot = setup_ctsemo();
testDirectory = fullfile(repositoryRoot, "src", "tests");
evidenceDirectory = fullfile( ...
    repositoryRoot, "manuscript", "artifacts", "tests");
if ~isfolder(evidenceDirectory)
    mkdir(evidenceDirectory);
end

originalDirectory = pwd;
workDirectory = tempname;
mkdir(workDirectory);
cleanup = onCleanup(@() restoreTestEnvironment( ...
    originalDirectory, workDirectory));
cd(workDirectory);

import matlab.unittest.TestRunner
import matlab.unittest.TestSuite
import matlab.unittest.plugins.XMLPlugin

suite = TestSuite.fromFolder(testDirectory, ...
    IncludingSubfolders=true);
runner = TestRunner.withTextOutput;
xmlPath = fullfile(evidenceDirectory, "test-results.xml");
runner.addPlugin(XMLPlugin.producingJUnitFormat(xmlPath));
results = runner.run(suite);

total = numel(results);
passed = nnz([results.Passed]);
failed = nnz([results.Failed]);
incomplete = nnz([results.Incomplete]);
issues = codeIssues(fullfile(repositoryRoot, "src"));
issueFiles = string(issues.Issues.FullFilename);
thirdParty = contains(issueFiles, fullfile("src", "vendor"));
ownedIssueCount = height(issues.Issues(~thirdParty, :));
thirdPartyIssueCount = nnz(thirdParty);
summary = [ ...
    "# cTSEMO release test summary"; ...
    ""; ...
    "- MATLAB: " + string(version); ...
    "- Date: " + string(datetime("today", Format="yyyy-MM-dd")); ...
    "- Total: " + total; ...
    "- Passed: " + passed; ...
    "- Failed: " + failed; ...
    "- Incomplete: " + incomplete; ...
    "- Repository-authored Code Analyzer findings: " + ownedIssueCount; ...
    "- Third-party provenance findings (reported, not modified): " + ...
        thirdPartyIssueCount; ...
    ""; ...
    "Generated by `run_release_tests.m`."];
writelines(summary, fullfile(evidenceDirectory, "TEST_SUMMARY.md"));

if failed > 0 || incomplete > 0 || ownedIssueCount > 0
    error("cTSEMO:ReleaseTests:Failure", ...
        ["%d failed and %d incomplete tests out of %d; " ...
         "%d repository-authored Code Analyzer findings."], ...
        failed, incomplete, total, ownedIssueCount);
end

clear cleanup
end

function restoreTestEnvironment(originalDirectory, workDirectory)
cd(originalDirectory);
if isfolder(workDirectory)
    rmdir(workDirectory, "s");
end
end
