function repositoryRoot = setup_ctsemo
%SETUP_CTSEMO Add the reader-facing cTSEMO paths to MATLAB.
%   REPOSITORYROOT = SETUP_CTSEMO validates the release layout before adding
%   the repository root, source, benchmarks, diagnostics, examples,
%   manuscript analyses, and study directories to the MATLAB path.

repositoryRoot = fileparts(mfilename("fullpath"));
sourceRoot = fullfile(repositoryRoot, "src");

requiredDirectories = [ ...
    string(repositoryRoot); ...
    string(sourceRoot); ...
    string(fullfile(sourceRoot, "benchmarks")); ...
    string(fullfile(sourceRoot, "diagnostics")); ...
    string(fullfile(sourceRoot, "examples")); ...
    string(fullfile(repositoryRoot, ...
        "manuscript", "introduction_pof_comparison")); ...
    string(fullfile(repositoryRoot, ...
        "manuscript", "artifacts")); ...
    string(fullfile(repositoryRoot, ...
        "studies", "dimension_matched_pof")); ...
    string(fullfile(repositoryRoot, ...
        "studies", "two_dimensional_pof")); ...
    string(fullfile(repositoryRoot, ...
        "studies", "hull_coverage"))];

for directory = requiredDirectories.'
    if ~isfolder(directory)
        error("cTSEMO:Setup:MissingDirectory", ...
            "Required repository directory is missing: %s", directory);
    end
end

for directory = requiredDirectories.'
    addpath(directory);
end

fprintf("cTSEMO repository paths added from:\n%s\n", repositoryRoot);
end
