function repositoryRoot = setup_ctsemo
%SETUP_CTSEMO Add the reader-facing cTSEMO source paths to MATLAB.
%   REPOSITORYROOT = SETUP_CTSEMO adds the public source, benchmarks,
%   diagnostics, examples, manuscript analyses, and studies to the path.

repositoryRoot = fileparts(mfilename("fullpath"));
sourceRoot = fullfile(repositoryRoot, "src");

requiredDirectories = [ ...
    string(sourceRoot); ...
    string(fullfile(sourceRoot, "benchmarks")); ...
    string(fullfile(sourceRoot, "diagnostics")); ...
    string(fullfile(sourceRoot, "examples")); ...
    string(fullfile(repositoryRoot, ...
        "manuscript", "introduction_pof_comparison")); ...
    string(fullfile(repositoryRoot, ...
        "studies", "dimension_matched_pof"))];

for directory = requiredDirectories.'
    if ~isfolder(directory)
        error("cTSEMO:Setup:MissingDirectory", ...
            "Required repository directory is missing: %s", directory);
    end
    addpath(directory);
end

fprintf("cTSEMO repository paths added from:\n%s\n", repositoryRoot);
end
