function manifest = generateReleaseFigures(options)
%GENERATERELEASEFIGURES Generate figures from a compatible v0.1 campaign.
%   MANIFEST = GENERATERELEASEFIGURES(CampaignRoot=PATH) reads the archived
%   campaign_sources.csv schema and writes its legacy diagnostic package.
%   Current manuscript figures use the entry points in docs/RESULTS_MAP.md.
%
%   The default welded-beam raster is exactly 50^4 cell-centered points.
%   Lower resolution is never substituted silently. Set RunWbRaster=false
%   only for a deliberate fast preflight.

    arguments
        options.CampaignRoot (1,1) string = ""
        options.FigureDirectory (1,1) string = ""
        options.DataDirectory (1,1) string = ""
        options.CompetitorSummaryFile (1,1) string = ""
        options.RunCompetitorOverlay (1,1) logical = false
        options.RunWbRaster (1,1) logical = true
        options.WbPointsPerDimension (1,1) double ...
            {mustBeInteger, mustBePositive} = 50
        options.WbChunkSize (1,1) double ...
            {mustBeInteger, mustBePositive} = 100000
        options.Resolution (1,1) double ...
            {mustBePositive, mustBeFinite} = 300
    end

    releaseRoot = fileparts(fileparts(mfilename("fullpath")));
    options = resolvePaths(options, releaseRoot);
    validateInputs(options);
    ensureDirectory(options.FigureDirectory);
    ensureDirectory(options.DataDirectory);

    previousPath = path;
    pathCleanup = onCleanup(@() path(previousPath));
    addpath(releaseRoot);
    addpath(fullfile(releaseRoot, "benchmarks"));
    addpath(fullfile(releaseRoot, "diagnostics"));

    definitions = campaignDefinitions(options.CampaignRoot, releaseRoot);
    fprintf("Loading %d shipped-profile campaign cases from %s\n", ...
        height(definitions), options.CampaignRoot);
    cases = loadCampaignCases(definitions);
    manifest = emptyManifest();
    captions = emptyCaptions();

    [summary, sourcePaths, optionsByCase] = campaignSummary(cases);
    sourcePaths = portableCampaignSourcePaths( ...
        sourcePaths, options, releaseRoot);
    optionsByCase = portableSolverOptions( ...
        optionsByCase, options, releaseRoot);
    summaryFile = fullfile(options.DataDirectory, ...
        "campaign_run_summary.csv");
    writetable(summary, summaryFile);
    manifest = addManifest(manifest, summaryFile, "data", ...
        strjoin(sourcePaths.SourceFile, "; "), ...
        "Measured campaign counts, hypervolume, selection, and timing summary.");

    sourceFile = fullfile(options.DataDirectory, ...
        "campaign_source_paths.csv");
    writetable(sourcePaths, sourceFile);
    manifest = addManifest(manifest, sourceFile, "provenance", ...
        options.CampaignRoot, ...
        "Exact campaign MAT-file and solver-output paths.");

    optionsMatFile = fullfile(options.DataDirectory, ...
        "campaign_solver_options.mat");
    save(optionsMatFile, "optionsByCase", "-v7");
    manifest = addManifest(manifest, optionsMatFile, "options", ...
        strjoin(sourcePaths.SourceFile, "; "), ...
        "Exact stored solver option structs for every case.");

    optionsJsonFile = fullfile(options.DataDirectory, ...
        "campaign_solver_options.json");
    writelines(jsonencode(optionsByCase, "PrettyPrint", true), ...
        optionsJsonFile);
    manifest = addManifest(manifest, optionsJsonFile, "options", ...
        optionsMatFile, "Human-readable serialization of stored options.");

    fprintf("Generating COSSIN2 final-iteration atlas.\n");
    cossin2 = caseByKey(cases, "COSSIN2");
    [atlasFigure, atlasMetadata] = plot2DIterationAtlas( ...
        cossin2.result, numel(cossin2.result.iterations), ...
        "Problem", cossin2.problem, ...
        "Title", "COSSIN2 final iteration: sampled acquisition decomposition");
    [atlasPng, atlasPdf] = exportFigurePair( ...
        atlasFigure, options.FigureDirectory, ...
        "fig_v4_cossin2_final_iteration_atlas", options.Resolution);
    close(atlasFigure);
    manifest = addFigurePair(manifest, atlasPng, atlasPdf, ...
        cossin2.sourceFile, atlasMetadata.caption);
    captions = addCaption(captions, atlasPng, ...
        atlasMetadata.caption, atlasMetadata.source);

    fprintf("Evaluating COSSIN2 post-run PoF on an independent grid.\n");
    [cossin2Model, cossin2FitDiagnostics] = ...
        fitFinalPofModel(cossin2.result);
    [cossin2ProbeX, cossin2ProbeUnit] = ...
        twoDimensionalCellCenters(cossin2.problem, 201);
    [cossin2Pof, cossin2Raw] = ctsemo.predictClippedBinaryPof( ...
        cossin2Model, cossin2ProbeUnit);
    cossin2Truth = logical(cossin2.problem.feasible(cossin2ProbeX));
    [validationFigure, validationMetrics, validationMetadata] = ...
        plotPofValidation(cossin2.result, ...
        "Score", cossin2Pof, ...
        "Truth", cossin2Truth, ...
        "Points", cossin2ProbeX, ...
        "Problem", cossin2.problem, ...
        "SampleDescription", ...
        "Independent uniform 201-by-201 cell-centered domain grid", ...
        "Title", "COSSIN2 post-run clipped-PoF validation");
    [validationPng, validationPdf] = exportFigurePair( ...
        validationFigure, options.FigureDirectory, ...
        "fig_v4_cossin2_pof_validation", options.Resolution);
    close(validationFigure);
    manifest = addFigurePair(manifest, validationPng, validationPdf, ...
        cossin2.sourceFile, validationMetadata.caption);
    captions = addCaption(captions, validationPng, ...
        validationMetadata.caption, cossin2.sourceFile);

    cossin2ProbeTable = table( ...
        cossin2ProbeX(:, 1), cossin2ProbeX(:, 2), ...
        cossin2Raw, cossin2Pof, cossin2Truth, ...
        'VariableNames', { ...
        'x1', 'x2', 'RawMean', 'p_i', 'IsFeasible'});
    cossin2ProbeFile = fullfile(options.DataDirectory, ...
        "cossin2_independent_grid_pof.csv");
    writetable(cossin2ProbeTable, cossin2ProbeFile);
    manifest = addManifest(manifest, cossin2ProbeFile, "data", ...
        cossin2.sourceFile, ...
        "Independent cell-centered probe coordinates, raw mean, p_i, and truth.");
    pofModelFile = fullfile(options.DataDirectory, ...
        "cossin2_postrun_pof_model.mat");
    [sourceFilePath, ~] = portablePath( ...
        cossin2.sourceFile, options, releaseRoot);
    save(pofModelFile, "cossin2Model", ...
        "cossin2FitDiagnostics", "sourceFilePath", "-v7");
    manifest = addManifest(manifest, pofModelFile, "model", ...
        cossin2.sourceFile, ...
        "PoF model refitted to all 80 stored binary labels.");
    [pofArtifacts, pofManifest] = writePofMetricArtifacts( ...
        validationMetrics, options.DataDirectory, "cossin2");
    manifest = [manifest; pofManifest];

    fprintf("Generating campaign history tables and combined history figure.\n");
    [feasibilityHistory, hypervolumeHistory, selectionCounts] = ...
        campaignHistories(cases);
    feasibilityFile = fullfile(options.DataDirectory, ...
        "campaign_feasibility_history.csv");
    hypervolumeFile = fullfile(options.DataDirectory, ...
        "campaign_fixed_reference_hypervolume_history.csv");
    selectionFile = fullfile(options.DataDirectory, ...
        "campaign_selection_source_counts.csv");
    writetable(feasibilityHistory, feasibilityFile);
    writetable(hypervolumeHistory, hypervolumeFile);
    writetable(selectionCounts, selectionFile);
    manifest = addManifest(manifest, feasibilityFile, "data", ...
        strjoin(sourcePaths.SourceFile, "; "), ...
        "Per-evaluation binary feasibility and cumulative rates.");
    manifest = addManifest(manifest, hypervolumeFile, "data", ...
        strjoin(sourcePaths.SourceFile, "; "), ...
        "Stored fixed-reference within-run hypervolume histories.");
    manifest = addManifest(manifest, selectionFile, "data", ...
        strjoin(sourcePaths.SourceFile, "; "), ...
        "Logged source counts excluding initial designs.");

    [historyFigure, historyCaption] = plotCampaignHistories( ...
        cases, feasibilityHistory, hypervolumeHistory, selectionCounts);
    [historyPng, historyPdf] = exportFigurePair( ...
        historyFigure, options.FigureDirectory, ...
        "fig_v4_campaign_histories", options.Resolution);
    close(historyFigure);
    manifest = addFigurePair(manifest, historyPng, historyPdf, ...
        strjoin(sourcePaths.SourceFile, "; "), historyCaption);
    captions = addCaption(captions, historyPng, ...
        historyCaption, strjoin(sourcePaths.SourceFile, "; "));

    fprintf("Generating BNH zero-initial-feasibility recovery timeline.\n");
    bnhStress = caseByKey(cases, "BNH_ALLINFEAS");
    [recoveryFigure, recoveryTable, recoveryCaption] = ...
        plotRecoveryTimeline(bnhStress);
    [recoveryPng, recoveryPdf] = exportFigurePair( ...
        recoveryFigure, options.FigureDirectory, ...
        "fig_v4_bnh_zero_initial_feasibility_recovery", ...
        options.Resolution);
    close(recoveryFigure);
    recoveryFile = fullfile(options.DataDirectory, ...
        "bnh_zero_initial_feasibility_recovery.csv");
    writetable(recoveryTable, recoveryFile);
    manifest = addFigurePair(manifest, recoveryPng, recoveryPdf, ...
        bnhStress.sourceFile, recoveryCaption);
    manifest = addManifest(manifest, recoveryFile, "data", ...
        bnhStress.sourceFile, ...
        "Iteration-level recovery state, source, reason, and observed label.");
    captions = addCaption(captions, recoveryPng, ...
        recoveryCaption, bnhStress.sourceFile);

    fprintf("Generating final Pareto panels across the core campaign.\n");
    [paretoFigure, paretoSummary, paretoCaption] = ...
        plotCampaignParetoPanels(cases);
    [paretoPng, paretoPdf] = exportFigurePair( ...
        paretoFigure, options.FigureDirectory, ...
        "fig_v4_campaign_final_pareto_panels", options.Resolution);
    close(paretoFigure);
    paretoFile = fullfile(options.DataDirectory, ...
        "campaign_final_pareto_summary.csv");
    writetable(paretoSummary, paretoFile);
    manifest = addFigurePair(manifest, paretoPng, paretoPdf, ...
        strjoin(sourcePaths.SourceFile, "; "), paretoCaption);
    manifest = addManifest(manifest, paretoFile, "data", ...
        strjoin(sourcePaths.SourceFile, "; "), ...
        "Measured final feasible and nondominated point counts.");
    captions = addCaption(captions, paretoPng, ...
        paretoCaption, strjoin(sourcePaths.SourceFile, "; "));

    weldedBeam = caseByKey(cases, "WELDEDBEAM");
    if options.RunCompetitorOverlay
        fprintf( ...
            "Generating unmatched welded-beam competitor pilot overlay.\n");
        [competitorFiles, competitorNames, competitorSourceTable] = ...
            weldedBeamCompetitorSources(options.CompetitorSummaryFile);
        unequalInformationNote = ...
            "Unmatched pilot: existing competitor runs received continuous " + ...
            "per-constraint margins, whereas this shipped cTSEMO run received " + ...
            "one aggregate binary label. Initial designs, seeds, and " + ...
            "implementations are not matched; no ranking is performed.";
        [competitorFigure, competitorMetrics, competitorMetadata] = ...
            plotWeldedBeamPilotComparison( ...
            weldedBeam.result, competitorFiles, ...
            "Names", competitorNames, ...
            "ObjectiveColumns", ["f1", "f2"], ...
            "Problem", weldedBeam.problem, ...
            "ComparisonNote", unequalInformationNote);
        [competitorPng, competitorPdf] = exportFigurePair( ...
            competitorFigure, options.FigureDirectory, ...
            "fig_v4_weldedbeam_unmatched_competitor_overlay", ...
            options.Resolution);
        close(competitorFigure);
        competitorSourceFile = fullfile(options.DataDirectory, ...
            "weldedbeam_unmatched_competitor_sources.csv");
        competitorSourceTable = portableCompetitorFileTable( ...
            competitorSourceTable, options, releaseRoot);
        writetable(competitorSourceTable, competitorSourceFile);
        manifest = addFigurePair(manifest, competitorPng, competitorPdf, ...
            strjoin([weldedBeam.sourceFile; competitorFiles], "; "), ...
            competitorMetadata.caption);
        manifest = addManifest(manifest, ...
            competitorSourceFile, "provenance", ...
            options.CompetitorSummaryFile, ...
            "Explicit competitor CSV paths and unequal-information status.");
        captions = addCaption(captions, competitorPng, ...
            competitorMetadata.caption, ...
            strjoin([weldedBeam.sourceFile; competitorFiles], "; "));
        competitorMetricsFile = fullfile(options.DataDirectory, ...
            "weldedbeam_unmatched_competitor_file_metrics.csv");
        competitorFileMetrics = portableCompetitorFileTable( ...
            competitorMetrics.competitorFiles, options, releaseRoot);
        writetable(competitorFileMetrics, competitorMetricsFile);
        manifest = addManifest(manifest, competitorMetricsFile, "data", ...
            options.CompetitorSummaryFile, ...
            "Rows and objective columns loaded for the unmatched overlay.");
    else
        fprintf("Skipping competitor overlay by explicit default.\n");
    end

    if options.RunWbRaster
        if options.WbPointsPerDimension ~= 50
            warning("cTSEMO:Diagnostics:NoncanonicalRasterResolution", ...
                "RunWbRaster is enabled with %d rather than the " + ...
                "canonical 50 points per dimension.", ...
                options.WbPointsPerDimension);
        end
        fprintf("Computing welded-beam %d^4 cell-centered PoF raster.\n", ...
            options.WbPointsPerDimension);
        rasterFile = fullfile(options.DataDirectory, ...
            "weldedbeam_sorted_pof_raster_50x4.mat");
        weldedBeamRaster = computeSortedPofRaster4D( ...
            weldedBeam.result, weldedBeam.problem, ...
            "PointsPerDimension", options.WbPointsPerDimension, ...
            "ChunkSize", options.WbChunkSize, ...
            "GridPlacement", "cellCenters", ...
            "UseFinalData", true, ...
            "Threshold", 0.5, ...
            "OutputFile", rasterFile, ...
            "ProgressFunction", @rasterProgress);
        manifest = addManifest(manifest, rasterFile, "data", ...
            weldedBeam.sourceFile, ...
            "Exact 4D score/truth/error rank raster with trace indices.");

        [rasterFigure, rasterMetadata] = ...
            plotSortedPofRaster4D(weldedBeamRaster, ...
            "Title", ...
            "Welded beam: 50^4 cell-centered clipped-PoF rank diagnostic");
        [rasterPng, rasterPdf] = exportFigurePair( ...
            rasterFigure, options.FigureDirectory, ...
            "fig_v4_weldedbeam_sorted_pof_raster_50x4", ...
            options.Resolution);
        close(rasterFigure);
        manifest = addFigurePair(manifest, rasterPng, rasterPdf, ...
            weldedBeam.sourceFile, rasterMetadata.caption);
        captions = addCaption(captions, rasterPng, ...
            rasterMetadata.caption, weldedBeam.sourceFile);

        fprintf("Computing welded-beam 50^4 PoF validation metrics.\n");
        [wbValidationFigure, wbValidationMetrics, wbValidationMetadata] = ...
            plotPofValidation(weldedBeam.result, ...
            "Score", weldedBeamRaster.score(:), ...
            "Truth", weldedBeamRaster.truth(:), ...
            "Threshold", weldedBeamRaster.threshold, ...
            "MaxCurvePoints", 6000, ...
            "SampleDescription", ...
            "Uniform 50^4 cell-centered welded-beam tensor grid", ...
            "Title", ...
            "Welded beam: clipped-PoF validation on 6,250,000 points");
        [wbValidationPng, wbValidationPdf] = exportFigurePair( ...
            wbValidationFigure, options.FigureDirectory, ...
            "fig_v4_weldedbeam_pof_validation_50x4", ...
            options.Resolution);
        close(wbValidationFigure);
        manifest = addFigurePair(manifest, ...
            wbValidationPng, wbValidationPdf, weldedBeam.sourceFile, ...
            wbValidationMetadata.caption);
        captions = addCaption(captions, wbValidationPng, ...
            wbValidationMetadata.caption, weldedBeam.sourceFile);

        [wbPofArtifacts, wbPofManifest] = writePofMetricArtifacts( ...
            wbValidationMetrics, options.DataDirectory, "weldedbeam_50x4");
        manifest = [manifest; wbPofManifest];
        rasterSummary = makeRasterSummary(weldedBeamRaster);
        rasterSummaryFile = fullfile(options.DataDirectory, ...
            "weldedbeam_sorted_pof_raster_summary.csv");
        writetable(rasterSummary, rasterSummaryFile);
        manifest = addManifest(manifest, rasterSummaryFile, "data", ...
            rasterFile, ...
            "Score distribution, truth volume, and threshold-error counts.");
    else
        fprintf("Skipping welded-beam 50^4 raster by explicit RunWbRaster=false.\n");
        wbPofArtifacts = strings(0, 1);
    end

    pathRoots = archivePathRoots(options);
    pathRootsFile = fullfile(options.DataDirectory, ...
        "archive_path_roots.csv");
    writetable(pathRoots, pathRootsFile);
    manifest = addManifest(manifest, pathRootsFile, "provenance", ...
        "Archive token declarations.", ...
        "Declared roots used by every portable path field.");

    captions = portableCaptionTable(captions, options, releaseRoot);
    captionsFile = fullfile(options.DataDirectory, ...
        "release_figure_captions_and_sources.csv");
    writetable(captions, captionsFile);
    manifest = addManifest(manifest, captionsFile, "provenance", ...
        strjoin(sourcePaths.SourceFile, "; "), ...
        "Cautious captions and exact source paths for generated figures.");

    manifestFile = fullfile(options.DataDirectory, ...
        "release_figure_manifest.csv");
    manifest = portableManifestTable(manifest, options, releaseRoot);
    writetable(manifest, manifestFile);
    pofArtifacts = portablePathVector( ...
        pofArtifacts, options, releaseRoot);
    wbPofArtifacts = portablePathVector( ...
        wbPofArtifacts, options, releaseRoot);
    generationOptions = portableGenerationOptions( ...
        options, releaseRoot);
    save(fullfile(options.DataDirectory, ...
        "release_generation_manifest.mat"), ...
        "manifest", "summary", "sourcePaths", ...
        "feasibilityHistory", "hypervolumeHistory", ...
        "selectionCounts", "paretoSummary", "pofArtifacts", ...
        "wbPofArtifacts", "generationOptions", "-v7");
    fprintf("Generated %d figure/data artifacts. Manifest: %s\n", ...
        height(manifest), manifestFile);

    clear pathCleanup
end

function options = resolvePaths(options, releaseRoot)
    if options.CampaignRoot == ""
        error("cTSEMO:Diagnostics:CampaignRootRequired", ...
            ["CampaignRoot is required for the archived v0.1 schema. " ...
             "See docs/RESULTS_MAP.md for current manuscript figures."]);
    end
    if options.FigureDirectory == ""
        options.FigureDirectory = fullfile( ...
            releaseRoot, "diagnostic-artifacts", "chap3-v4", "figures");
    end
    if options.DataDirectory == ""
        options.DataDirectory = fullfile( ...
            releaseRoot, "diagnostic-artifacts", "chap3-v4", "data");
    end
end

function validateInputs(options)
    if ~isfolder(options.CampaignRoot)
        error("cTSEMO:Diagnostics:MissingCampaignRoot", ...
            "Campaign root not found: %s", options.CampaignRoot);
    end
    sourceManifest = fullfile( ...
        options.CampaignRoot, "campaign_sources.csv");
    if ~isfile(sourceManifest)
        error("cTSEMO:Diagnostics:MissingCampaignSourceManifest", ...
            "Campaign source manifest not found: %s", sourceManifest);
    end
    if options.RunCompetitorOverlay && ...
            ~isfile(options.CompetitorSummaryFile)
        error("cTSEMO:Diagnostics:MissingCompetitorSummary", ...
            "RunCompetitorOverlay=true requires an explicit existing " + ...
            "CompetitorSummaryFile. Not found: %s", ...
            options.CompetitorSummaryFile);
    end
    if options.WbPointsPerDimension < 2
        error("cTSEMO:Diagnostics:RasterResolution", ...
            "WbPointsPerDimension must be at least two.");
    end
end

function ensureDirectory(directory)
    if isfolder(directory)
        return
    end
    [created, message] = mkdir(directory);
    if ~created
        error("cTSEMO:Diagnostics:DirectoryCreation", ...
            "Could not create directory '%s': %s", directory, message);
    end
end

function definitions = campaignDefinitions(campaignRoot, releaseRoot)
    sourceManifest = fullfile(campaignRoot, "campaign_sources.csv");
    definitions = readtable(sourceManifest, ...
        "TextType", "string", "VariableNamingRule", "preserve");
    required = [ ...
        "Key", "OfficialCaseId", "ProblemId", "DisplayName", ...
        "ResultFile", "CampaignSummaryFile", "CampaignManifestFile", ...
        "SourceManifestFile", "SourceManifestHashFile", ...
        "SourceManifestSHA256", ...
        "InitialSeed", "SolverSeed", "WallTimeSeconds", ...
        "LoggingLevel", "PrimaryCandidateCount", ...
        "ChallengerCandidateCount", "ObjectiveFeatureCount", ...
        "ExpectedInitialCount", "ExpectedSequentialBudget", ...
        "ExpectedTotalEvaluations", "ExpectedInitialFeasibleCount", ...
        "ExpectedFinalFeasibleCount"];
    if ~all(ismember(required, string(definitions.Properties.VariableNames)))
        error("cTSEMO:Diagnostics:InvalidCampaignSourceManifest", ...
            "The shipped-profile source manifest is missing required columns.");
    end
    definitions.ResultFile = makeAbsolutePaths( ...
        definitions.ResultFile, releaseRoot);
    definitions.CampaignSummaryFile = makeAbsolutePaths( ...
        definitions.CampaignSummaryFile, releaseRoot);
    definitions.CampaignManifestFile = makeAbsolutePaths( ...
        definitions.CampaignManifestFile, releaseRoot);
    definitions.SourceManifestFile = makeAbsolutePaths( ...
        definitions.SourceManifestFile, releaseRoot);
    definitions.SourceManifestHashFile = makeAbsolutePaths( ...
        definitions.SourceManifestHashFile, releaseRoot);
    if height(definitions) ~= 7 || numel(unique(definitions.Key)) ~= 7
        error("cTSEMO:Diagnostics:InvalidCampaignSourceSet", ...
            "Exactly seven uniquely keyed shipped-profile cases are required.");
    end
    if any(definitions.PrimaryCandidateCount ~= 1024) || ...
            any(definitions.ChallengerCandidateCount ~= 512) || ...
            any(definitions.ObjectiveFeatureCount ~= 256)
        error("cTSEMO:Diagnostics:WrongCampaignProfile", ...
            "Headline diagnostics require the shipped 1024/512/256 profile.");
    end
    if any(~isfile(definitions.ResultFile)) || ...
            any(~isfile(definitions.CampaignSummaryFile)) || ...
            any(~isfile(definitions.CampaignManifestFile)) || ...
            any(~isfile(definitions.SourceManifestFile)) || ...
            any(~isfile(definitions.SourceManifestHashFile))
        error("cTSEMO:Diagnostics:MissingCampaignSource", ...
            "At least one official result or campaign-authority file is missing.");
    end
    validateCampaignAuthority(definitions);
end

function validateCampaignAuthority(definitions)
    expectedHashes = lower(string(definitions.SourceManifestSHA256));
    if numel(unique(expectedHashes)) ~= 1 || ...
            isempty(regexp(char(expectedHashes(1)), ...
            "^[0-9a-f]{64}$", "once"))
        error("cTSEMO:Diagnostics:InvalidSourceManifestHash", ...
            "The source mapping must contain one valid SHA-256 authority.");
    end
    expectedHash = expectedHashes(1);
    hashFiles = unique(string(definitions.SourceManifestHashFile));
    manifestFiles = unique(string(definitions.CampaignManifestFile));
    sourceFiles = unique(string(definitions.SourceManifestFile));
    if numel(hashFiles) ~= 1 || numel(manifestFiles) ~= 1 || ...
            numel(sourceFiles) ~= 1
        error("cTSEMO:Diagnostics:MixedCampaignAuthority", ...
            "All diagnostic cases must share one sealed campaign authority.");
    end

    hashText = strtrim(fileread(hashFiles(1)));
    recordedHash = regexp(hashText, "^[0-9A-Fa-f]{64}", ...
        "match", "once");
    if isempty(recordedHash) || lower(string(recordedHash)) ~= expectedHash
        error("cTSEMO:Diagnostics:SourceManifestHashMismatch", ...
            "The declared digest does not match the campaign SHA-256 file.");
    end

    authority = jsondecode(fileread(manifestFiles(1)));
    if ~isfield(authority, "campaign") || ...
            string(authority.campaign.Status) ~= "completed" || ...
            lower(string(authority.campaign.SourceManifestSHA256)) ~= ...
            expectedHash
        error("cTSEMO:Diagnostics:CampaignAuthorityMismatch", ...
            "The campaign manifest is incomplete or has a different digest.");
    end
end

function paths = makeAbsolutePaths(paths, baseDirectory)
    paths = string(paths);
    for index = 1:numel(paths)
        value = paths(index);
        absolute = ~isempty(regexp(char(value), ...
            "^(?:[A-Za-z]:[\\/]|[\\/]{2}|/)", "once"));
        if ~absolute
            paths(index) = fullfile(baseDirectory, value);
        end
    end
end

function paths = portableCampaignSourcePaths( ...
        paths, options, releaseRoot)
    [paths.SourceFile, paths.SourceFilePathRoot] = ...
        portablePathVector(paths.SourceFile, options, releaseRoot);
    [paths.OfficialCampaignSummaryFile, ...
        paths.OfficialCampaignSummaryPathRoot] = portablePathVector( ...
        paths.OfficialCampaignSummaryFile, options, releaseRoot);
    [paths.OfficialCampaignManifestFile, ...
        paths.OfficialCampaignManifestPathRoot] = portablePathVector( ...
        paths.OfficialCampaignManifestFile, options, releaseRoot);
    [paths.OfficialReleaseSourceManifestFile, ...
        paths.OfficialReleaseSourceManifestPathRoot] = portablePathVector( ...
        paths.OfficialReleaseSourceManifestFile, options, releaseRoot);
    [paths.OfficialReleaseSourceManifestHashFile, ...
        paths.OfficialReleaseSourceManifestHashPathRoot] = ...
        portablePathVector( ...
        paths.OfficialReleaseSourceManifestHashFile, options, releaseRoot);
    [paths.SolverOutputDirectory, paths.SolverOutputPathRoot] = ...
        portablePathVector( ...
        paths.SolverOutputDirectory, options, releaseRoot);
end

function optionsByCase = portableSolverOptions( ...
        optionsByCase, generationOptions, releaseRoot)
    names = string(fieldnames(optionsByCase));
    for index = 1:numel(names)
        name = names(index);
        item = optionsByCase.(name);
        if isfield(item, "logging") && ...
                isfield(item.logging, "directory")
            [item.logging.directory, item.logging.directoryPathRoot] = ...
                portablePath( ...
                item.logging.directory, generationOptions, releaseRoot);
        end
        optionsByCase.(name) = item;
    end
end

function tableOut = portableCompetitorFileTable( ...
        tableIn, options, releaseRoot)
    tableOut = tableIn;
    names = string(tableOut.Properties.VariableNames);
    if ismember("Source", names)
        [tableOut.Source, tableOut.SourcePathRoot] = ...
            portablePathVector(tableOut.Source, options, releaseRoot);
    end
    if ismember("File", names)
        [tableOut.File, tableOut.FilePathRoot] = ...
            portablePathVector(tableOut.File, options, releaseRoot);
    end
end

function tableOut = portableCaptionTable(tableIn, options, releaseRoot)
    tableOut = tableIn;
    [tableOut.Figure, tableOut.FigurePathRoot] = ...
        portablePathVector(tableOut.Figure, options, releaseRoot);
    sourceRoot = strings(height(tableOut), 1);
    for index = 1:height(tableOut)
        [tableOut.Source(index), sourceRoot(index)] = ...
            portablePathList( ...
            tableOut.Source(index), options, releaseRoot);
    end
    tableOut.SourcePathRoot = sourceRoot;
end

function tableOut = portableManifestTable(tableIn, options, releaseRoot)
    tableOut = tableIn;
    [tableOut.Artifact, tableOut.ArtifactPathRoot] = ...
        portablePathVector(tableOut.Artifact, options, releaseRoot);
    sourceRoot = strings(height(tableOut), 1);
    for index = 1:height(tableOut)
        [tableOut.Source(index), sourceRoot(index)] = ...
            portablePathList( ...
            tableOut.Source(index), options, releaseRoot);
    end
    tableOut.SourcePathRoot = sourceRoot;
end

function roots = archivePathRoots(options)
    token = [ ...
        "@RELEASE_ROOT@"; "@FIGURE_ROOT@"; "@DATA_ROOT@"];
    meaning = [ ...
        "Root directory of the extracted cTSEMO-release package."; ...
        "Directory containing the generated figure archive."; ...
        "Directory containing the generated diagnostic-data archive."];
    if options.RunCompetitorOverlay
        token(end + 1, 1) = "@COMPETITOR_SUMMARY_DIR@";
        meaning(end + 1, 1) = ...
            "Directory containing the explicitly supplied competitor summary.";
    end
    roots = table(token, meaning, ...
        'VariableNames', {'PathRoot', 'Meaning'});
end

function generationOptions = portableGenerationOptions(options, releaseRoot)
    generationOptions = options;
    fields = [ ...
        "CampaignRoot", "FigureDirectory", "DataDirectory", ...
        "CompetitorSummaryFile"];
    for field = fields
        if isfield(generationOptions, field) && ...
                string(generationOptions.(field)) ~= ""
            [generationOptions.(field), ...
                generationOptions.(field + "PathRoot")] = ...
                portablePath( ...
                generationOptions.(field), options, releaseRoot);
        end
    end
end

function [paths, roots] = portablePathVector( ...
        paths, options, releaseRoot)
    paths = string(paths);
    roots = strings(size(paths));
    for index = 1:numel(paths)
        [paths(index), roots(index)] = portablePath( ...
            paths(index), options, releaseRoot);
    end
end

function [value, root] = portablePathList(value, options, releaseRoot)
    value = string(value);
    root = "";
    if value == ""
        return
    end
    parts = split(value, "; ");
    roots = strings(size(parts));
    for index = 1:numel(parts)
        [parts(index), roots(index)] = portablePath( ...
            parts(index), options, releaseRoot);
    end
    value = strjoin(parts, "; ");
    roots = unique(roots(roots ~= ""), "stable");
    root = strjoin(roots, "; ");
end

function [value, root] = portablePath(value, options, releaseRoot)
    value = string(value);
    root = pathToken(value);
    if value == "" || root ~= ""
        return
    end
    if ~isAbsolutePath(value)
        return
    end

    [inside, relative] = pathRelativeTo(value, options.FigureDirectory);
    if inside
        root = "@FIGURE_ROOT@";
        value = tokenPath(root, relative);
        return
    end
    [inside, relative] = pathRelativeTo(value, options.DataDirectory);
    if inside
        root = "@DATA_ROOT@";
        value = tokenPath(root, relative);
        return
    end
    [inside, relative] = pathRelativeTo(value, releaseRoot);
    if inside
        root = "@RELEASE_ROOT@";
        value = tokenPath(root, relative);
        return
    end
    if options.RunCompetitorOverlay && ...
            options.CompetitorSummaryFile ~= ""
        competitorDirectory = fileparts(options.CompetitorSummaryFile);
        relative = relativePath(value, competitorDirectory);
        root = "@COMPETITOR_SUMMARY_DIR@";
        value = tokenPath(root, relative);
        return
    end
    error("cTSEMO:Diagnostics:UnportableArchivePath", ...
        "No declared archive path root covers: %s", value);
end

function token = pathToken(value)
    match = regexp(char(value), "^(@[^@]+@)", "tokens", "once");
    if isempty(match)
        token = "";
    else
        token = string(match{1});
    end
end

function value = tokenPath(token, relative)
    relative = replace(string(relative), "\", "/");
    if relative == "" || relative == "."
        value = token;
    else
        value = token + "/" + relative;
    end
end

function absolute = isAbsolutePath(value)
    absolute = ~isempty(regexp(char(value), ...
        "^(?:[A-Za-z]:[\\/]|[\\/]{2}|/)", "once"));
end

function [inside, relative] = pathRelativeTo(value, root)
    value = normalizedPath(value);
    root = normalizedPath(root);
    inside = strcmpi(value, root);
    relative = "";
    if inside
        return
    end
    prefix = root + "/";
    inside = startsWith(lower(value), lower(prefix));
    if inside
        relative = extractAfter(value, strlength(prefix));
    end
end

function relative = relativePath(value, root)
    valueParts = split(normalizedPath(value), "/");
    rootParts = split(normalizedPath(root), "/");
    common = 0;
    maximum = min(numel(valueParts), numel(rootParts));
    while common < maximum && ...
            strcmpi(valueParts(common + 1), rootParts(common + 1))
        common = common + 1;
    end
    if common == 0
        error("cTSEMO:Diagnostics:DifferentArchiveVolumes", ...
            "External source and competitor summary are on different roots.");
    end
    up = repmat("..", numel(rootParts) - common, 1);
    down = valueParts(common + 1:end);
    parts = [up; down];
    if isempty(parts)
        relative = ".";
    else
        relative = strjoin(parts, "/");
    end
end

function value = normalizedPath(value)
    value = replace(string(value), "\", "/");
    value = regexprep(value, "/+$", "");
end

function cases = loadCampaignCases(definitions)
    template = struct( ...
        "key", "", "officialCaseId", "", ...
        "displayName", "", "sourceFile", "", ...
        "campaignSummaryFile", "", ...
        "campaignManifestFile", "", ...
        "sourceManifestFile", "", ...
        "sourceManifestHashFile", "", ...
        "sourceManifestSHA256", "", ...
        "problem", struct(), "result", struct(), ...
        "designSeed", NaN, "solverSeed", NaN, "wallTime", NaN, ...
        "primaryCandidateCount", NaN, ...
        "challengerCandidateCount", NaN, ...
        "objectiveFeatureCount", NaN);
    cases = repmat(template, height(definitions), 1);
    for index = 1:height(definitions)
        sourceFile = definitions.ResultFile(index);
        if ~isfile(sourceFile)
            error("cTSEMO:Diagnostics:MissingCampaignCase", ...
                "Campaign case not found: %s", sourceFile);
        end
        loaded = load(sourceFile);
        if ~isfield(loaded, "result")
            error("cTSEMO:Diagnostics:InvalidCampaignCase", ...
                "Official result MAT-file lacks result: %s", sourceFile);
        end
        validateOfficialResult(loaded.result, definitions(index, :), ...
            sourceFile);
        cases(index).key = definitions.Key(index);
        cases(index).officialCaseId = definitions.OfficialCaseId(index);
        cases(index).displayName = definitions.DisplayName(index);
        cases(index).sourceFile = string(sourceFile);
        cases(index).campaignSummaryFile = ...
            definitions.CampaignSummaryFile(index);
        cases(index).campaignManifestFile = ...
            definitions.CampaignManifestFile(index);
        cases(index).sourceManifestFile = ...
            definitions.SourceManifestFile(index);
        cases(index).sourceManifestHashFile = ...
            definitions.SourceManifestHashFile(index);
        cases(index).sourceManifestSHA256 = lower( ...
            string(definitions.SourceManifestSHA256(index)));
        cases(index).problem = getBenchmarkProblem( ...
            definitions.ProblemId(index));
        cases(index).result = loaded.result;
        cases(index).designSeed = double(definitions.InitialSeed(index));
        cases(index).solverSeed = double(definitions.SolverSeed(index));
        cases(index).wallTime = ...
            double(definitions.WallTimeSeconds(index));
        cases(index).primaryCandidateCount = ...
            double(definitions.PrimaryCandidateCount(index));
        cases(index).challengerCandidateCount = ...
            double(definitions.ChallengerCandidateCount(index));
        cases(index).objectiveFeatureCount = ...
            double(definitions.ObjectiveFeatureCount(index));
    end
end

function validateOfficialResult(result, definition, sourceFile)
    totalCount = size(result.data.X, 1);
    initialCount = result.data.nInitial;
    sequentialBudget = totalCount - initialCount;
    initialFeasible = nnz(result.data.isFeasible(1:initialCount));
    finalFeasible = nnz(result.data.isFeasible);
    observed = [ ...
        initialCount, sequentialBudget, totalCount, ...
        initialFeasible, finalFeasible];
    expected = [ ...
        definition.ExpectedInitialCount, ...
        definition.ExpectedSequentialBudget, ...
        definition.ExpectedTotalEvaluations, ...
        definition.ExpectedInitialFeasibleCount, ...
        definition.ExpectedFinalFeasibleCount];
    if ~isequal(double(observed), double(expected))
        error("cTSEMO:Diagnostics:CampaignSourceMismatch", ...
            "Stored counts do not match the source manifest: %s", ...
            sourceFile);
    end
    profile = [ ...
        result.options.candidates.primaryCount, ...
        result.options.challengers.count, ...
        result.options.objectiveGP.nFeatures];
    expectedProfile = [ ...
        definition.PrimaryCandidateCount, ...
        definition.ChallengerCandidateCount, ...
        definition.ObjectiveFeatureCount];
    if ~isequal(double(profile), double(expectedProfile))
        error("cTSEMO:Diagnostics:CampaignProfileMismatch", ...
            "Stored solver profile does not match the source manifest: %s", ...
            sourceFile);
    end
    if string(result.options.logging.level) ~= definition.LoggingLevel
        error("cTSEMO:Diagnostics:CampaignLoggingMismatch", ...
            "Stored logging level does not match the source manifest: %s", ...
            sourceFile);
    end
end

function selected = caseByKey(cases, key)
    index = find([cases.key] == key, 1);
    if isempty(index)
        error("cTSEMO:Diagnostics:MissingCase", ...
            "Campaign case '%s' is not loaded.", key);
    end
    selected = cases(index);
end

function [summary, paths, optionsByCase] = campaignSummary(cases)
    count = numel(cases);
    caseKey = strings(count, 1);
    officialCaseId = strings(count, 1);
    displayName = strings(count, 1);
    initialCount = zeros(count, 1);
    totalCount = zeros(count, 1);
    feasibleCount = zeros(count, 1);
    paretoCount = zeros(count, 1);
    fallbackCount = zeros(count, 1);
    primaryCount = zeros(count, 1);
    challengerCount = zeros(count, 1);
    finalHypervolume = zeros(count, 1);
    reference1 = NaN(count, 1);
    reference2 = NaN(count, 1);
    designSeed = zeros(count, 1);
    solverSeed = zeros(count, 1);
    wallTimeSeconds = zeros(count, 1);
    loggingLevel = strings(count, 1);
    sourceFile = strings(count, 1);
    campaignSummaryFile = strings(count, 1);
    campaignManifestFile = strings(count, 1);
    sourceManifestFile = strings(count, 1);
    sourceManifestHashFile = strings(count, 1);
    sourceManifestSHA256 = strings(count, 1);
    solverOutputDirectory = strings(count, 1);
    primaryCandidateCount = zeros(count, 1);
    challengerCandidateCount = zeros(count, 1);
    objectiveFeatureCount = zeros(count, 1);
    optionsByCase = struct();

    for index = 1:count
        item = cases(index);
        result = item.result;
        sources = string(result.data.selectionSource);
        caseKey(index) = item.key;
        officialCaseId(index) = item.officialCaseId;
        displayName(index) = item.displayName;
        initialCount(index) = result.data.nInitial;
        totalCount(index) = size(result.data.X, 1);
        feasibleCount(index) = nnz(result.data.isFeasible);
        paretoCount(index) = size(result.pareto.Y, 1);
        fallbackCount(index) = nnz(sources == "fallback");
        primaryCount(index) = nnz(sources == "primary");
        challengerCount(index) = nnz(sources == "challenger");
        finalHypervolume(index) = result.pareto.hypervolume;
        if ~isempty(result.pareto.referencePoint)
            reference1(index) = result.pareto.referencePoint(1);
            reference2(index) = result.pareto.referencePoint(2);
        end
        designSeed(index) = item.designSeed;
        solverSeed(index) = item.solverSeed;
        wallTimeSeconds(index) = item.wallTime;
        loggingLevel(index) = result.options.logging.level;
        sourceFile(index) = item.sourceFile;
        campaignSummaryFile(index) = item.campaignSummaryFile;
        campaignManifestFile(index) = item.campaignManifestFile;
        sourceManifestFile(index) = item.sourceManifestFile;
        sourceManifestHashFile(index) = item.sourceManifestHashFile;
        sourceManifestSHA256(index) = item.sourceManifestSHA256;
        solverOutputDirectory(index) = result.meta.outputDirectory;
        primaryCandidateCount(index) = item.primaryCandidateCount;
        challengerCandidateCount(index) = item.challengerCandidateCount;
        objectiveFeatureCount(index) = item.objectiveFeatureCount;
        optionsByCase.(item.key) = result.options;
    end

    summary = table( ...
        caseKey, officialCaseId, displayName, ...
        initialCount, totalCount, feasibleCount, ...
        paretoCount, fallbackCount, primaryCount, challengerCount, ...
        finalHypervolume, reference1, reference2, designSeed, solverSeed, ...
        wallTimeSeconds, loggingLevel, ...
        primaryCandidateCount, challengerCandidateCount, ...
        objectiveFeatureCount, ...
        'VariableNames', { ...
        'Case', 'OfficialCaseId', 'DisplayName', ...
        'InitialCount', 'TotalCount', ...
        'FeasibleCount', 'ParetoCount', 'FallbackCount', ...
        'PrimaryCount', 'ChallengerCount', 'FinalHypervolume', ...
        'ReferenceF1', 'ReferenceF2', 'DesignSeed', 'SolverSeed', ...
        'WallTimeSeconds', 'LoggingLevel', ...
        'PrimaryCandidateCount', 'ChallengerCandidateCount', ...
        'ObjectiveFeatureCount'});
    paths = table( ...
        caseKey, officialCaseId, sourceFile, campaignSummaryFile, ...
        campaignManifestFile, sourceManifestFile, ...
        sourceManifestHashFile, sourceManifestSHA256, ...
        solverOutputDirectory, primaryCandidateCount, ...
        challengerCandidateCount, objectiveFeatureCount, ...
        'VariableNames', { ...
        'Case', 'OfficialCaseId', 'SourceFile', ...
        'OfficialCampaignSummaryFile', ...
        'OfficialCampaignManifestFile', ...
        'OfficialReleaseSourceManifestFile', ...
        'OfficialReleaseSourceManifestHashFile', ...
        'SourceManifestSHA256', 'SolverOutputDirectory', ...
        'PrimaryCandidateCount', 'ChallengerCandidateCount', ...
        'ObjectiveFeatureCount'});
end

function [model, diagnostics] = fitFinalPofModel(result)
    XUnit = (result.data.X - result.problem.lowerBound) ./ ...
        (result.problem.upperBound - result.problem.lowerBound);
    if all(result.data.isFeasible)
        model = struct( ...
            "construction", "constant_all_feasible", ...
            "dimension", size(XUnit, 2), ...
            "rawValue", result.options.pof.rawFeasible, ...
            "clippedValue", 1);
        diagnostics = struct( ...
            "construction", model.construction, ...
            "observationCount", size(XUnit, 1));
    else
        [model, diagnostics] = ctsemo.fitClippedBinaryPof( ...
            XUnit, result.data.isFeasible, result.options);
    end
end

function [X, XUnit] = twoDimensionalCellCenters(problem, gridCount)
    centers = ((1:gridCount) - 0.5) ./ gridCount;
    [u1, u2] = meshgrid(centers, centers);
    XUnit = [u1(:), u2(:)];
    X = problem.lowerBound + XUnit .* ...
        (problem.upperBound - problem.lowerBound);
end

function [artifacts, manifest] = writePofMetricArtifacts( ...
        metrics, outputDirectory, prefix)
    ece = metrics.reliability.Properties.UserData. ...
        expectedCalibrationError;
    confusion = metrics.confusion;
    metricName = [ ...
        "SampleCount"; "FeasibleCount"; "InfeasibleCount"; ...
        "BrierScore"; "ROCAUC"; "EqualWidthECE"; ...
        "FalseFeasibleRate"; "FalseInfeasibleRate"; ...
        "Sensitivity"; "Specificity"; "BalancedAccuracy"; ...
        "Threshold"];
    value = [ ...
        metrics.sampleCount; metrics.feasibleCount; ...
        metrics.infeasibleCount; metrics.brierScore; metrics.auc; ece; ...
        metrics.falseFeasibleRate; metrics.falseInfeasibleRate; ...
        confusion.sensitivity; confusion.specificity; ...
        confusion.balancedAccuracy; metrics.threshold];
    summaryTable = table(metricName, value, ...
        'VariableNames', {'Metric', 'Value'});
    confusionTable = table( ...
        ["True infeasible"; "True feasible"], ...
        confusion.matrix(:, 1), confusion.matrix(:, 2), ...
        'VariableNames', { ...
        'TruthClass', 'PredictedInfeasible', 'PredictedFeasible'});
    rocTable = table( ...
        metrics.rocFalsePositiveRate, metrics.rocTruePositiveRate, ...
        metrics.rocThreshold, ...
        'VariableNames', { ...
        'FalseFeasibleRate', 'TrueFeasibleRate', 'Threshold'});

    summaryFile = fullfile(outputDirectory, prefix + "_pof_metrics.csv");
    confusionFile = fullfile( ...
        outputDirectory, prefix + "_pof_confusion.csv");
    reliabilityFile = fullfile( ...
        outputDirectory, prefix + "_pof_reliability.csv");
    rocFile = fullfile(outputDirectory, prefix + "_pof_roc.csv");
    writetable(summaryTable, summaryFile);
    writetable(confusionTable, confusionFile);
    writetable(metrics.reliability, reliabilityFile);
    writetable(rocTable, rocFile);

    artifacts = [summaryFile; confusionFile; reliabilityFile; rocFile];
    manifest = emptyManifest();
    for file = transpose(artifacts)
        manifest = addManifest(manifest, file, "data", ...
            "Calculated from supplied validation score/truth vectors.", ...
            "PoF validation metric artifact.");
    end
end

function [feasibility, hypervolume, sourceCounts] = ...
        campaignHistories(cases)
    feasibility = table();
    hypervolume = table();
    sourceRows = table();

    for caseIndex = 1:numel(cases)
        item = cases(caseIndex);
        result = item.result;
        n = size(result.data.X, 1);
        evaluation = (1:n).';
        sequentialIteration = max(0, evaluation - result.data.nInitial);
        label = logical(result.data.isFeasible);
        cumulativeCount = cumsum(double(label));
        cumulativeRate = cumulativeCount ./ evaluation;
        caseColumn = repmat(item.key, n, 1);
        block = table( ...
            caseColumn, evaluation, sequentialIteration, label, ...
            cumulativeCount, cumulativeRate, ...
            'VariableNames', { ...
            'Case', 'Evaluation', 'SequentialIteration', 'IsFeasible', ...
            'CumulativeFeasibleCount', 'CumulativeFeasibleRate'});
        feasibility = [feasibility; block]; %#ok<AGROW>

        history = result.pareto.history;
        finalValue = history.hypervolume(end);
        if finalValue > 0
            normalized = history.hypervolume ./ finalValue;
        else
            normalized = NaN(size(history.hypervolume));
        end
        block = table( ...
            repmat(item.key, numel(history.iteration), 1), ...
            history.iteration, history.evaluationCount, ...
            history.hypervolume, normalized, history.feasibleCount, ...
            repmat(result.pareto.referencePoint(1), ...
            numel(history.iteration), 1), ...
            repmat(result.pareto.referencePoint(2), ...
            numel(history.iteration), 1), ...
            'VariableNames', { ...
            'Case', 'SequentialIteration', 'EvaluationCount', ...
            'FixedReferenceHypervolume', 'FractionOfRunFinalHypervolume', ...
            'FeasibleCount', 'ReferenceF1', 'ReferenceF2'});
        hypervolume = [hypervolume; block]; %#ok<AGROW>

        sources = string(result.data.selectionSource( ...
            result.data.nInitial + 1:end));
        names = unique(sources, "stable");
        for sourceIndex = 1:numel(names)
            block = table(item.key, names(sourceIndex), ...
                nnz(sources == names(sourceIndex)), ...
                'VariableNames', {'Case', 'SelectionSource', 'Count'});
            sourceRows = [sourceRows; block]; %#ok<AGROW>
        end
    end
    sourceCounts = sourceRows;
end

function [figureHandle, caption] = plotCampaignHistories( ...
        cases, feasibility, hypervolume, sourceCounts)
    colors = lines(numel(cases));
    figureHandle = figure( ...
        "Visible", "off", "Color", "white", ...
        "Units", "pixels", "Position", [100, 100, 1500, 860]);
    layout = tiledlayout(figureHandle, 1, 3, ...
        "TileSpacing", "compact", "Padding", "compact");
    title(layout, "cTSEMO release campaign histories");

    axesHandle = nexttile(layout);
    hold(axesHandle, "on");
    for index = 1:numel(cases)
        selected = feasibility.Case == cases(index).key & ...
            feasibility.Evaluation >= cases(index).result.data.nInitial;
        sequential = feasibility.SequentialIteration(selected);
        rate = feasibility.CumulativeFeasibleRate(selected);
        plot(axesHandle, sequential, rate, "-", ...
            "Color", colors(index, :), "LineWidth", 1.35, ...
            "DisplayName", cases(index).displayName);
    end
    hold(axesHandle, "off");
    xlabel(axesHandle, "Sequential iteration");
    ylabel(axesHandle, "Cumulative feasible fraction");
    title(axesHandle, "Feasibility discovery");
    ylim(axesHandle, [0, 1]);
    grid(axesHandle, "on");
    axesHandle.GridAlpha = 0.15;
    historyLegendAxes = axesHandle;

    axesHandle = nexttile(layout);
    hold(axesHandle, "on");
    for index = 1:numel(cases)
        selected = hypervolume.Case == cases(index).key;
        plot(axesHandle, hypervolume.SequentialIteration(selected), ...
            hypervolume.FractionOfRunFinalHypervolume(selected), "-", ...
            "Color", colors(index, :), "LineWidth", 1.35, ...
            "DisplayName", cases(index).displayName);
    end
    hold(axesHandle, "off");
    xlabel(axesHandle, "Sequential iteration");
    ylabel(axesHandle, "Fraction of run-final fixed-reference HV");
    title(axesHandle, "Within-run hypervolume growth");
    ylim(axesHandle, [0, 1.02]);
    grid(axesHandle, "on");
    axesHandle.GridAlpha = 0.15;

    axesHandle = nexttile(layout);
    sourceNames = unique(sourceCounts.SelectionSource, "stable");
    countMatrix = zeros(numel(cases), numel(sourceNames));
    for caseIndex = 1:numel(cases)
        for sourceIndex = 1:numel(sourceNames)
            selected = sourceCounts.Case == cases(caseIndex).key & ...
                sourceCounts.SelectionSource == sourceNames(sourceIndex);
            countMatrix(caseIndex, sourceIndex) = ...
                sum(sourceCounts.Count(selected));
        end
    end
    bar(axesHandle, categorical([cases.displayName]), ...
        countMatrix, "stacked");
    ylabel(axesHandle, "Sequential selections");
    title(axesHandle, "Logged point-selection source");
    legend(axesHandle, sourceNames, ...
        "Location", "northoutside", "Box", "off");
    grid(axesHandle, "on");
    axesHandle.GridAlpha = 0.15;

    curveLegend = legend(historyLegendAxes, "show", ...
        "Orientation", "horizontal", "Box", "off");
    curveLegend.Layout.Tile = "south";
    caption = ...
        "Cumulative feasible fraction, within-run hypervolume growth at " + ...
        "each run's fixed final reference, and logged selection-source " + ...
        "counts. Hypervolume is normalized only to show convergence shape; " + ...
        "values are not compared across problems with different objectives.";
end

function [figureHandle, outputTable, caption] = ...
        plotRecoveryTimeline(item)
    iterations = item.result.iterations;
    count = numel(iterations);
    iteration = (1:count).';
    evaluationIndex = zeros(count, 1);
    selectionState = strings(count, 1);
    selectionSource = strings(count, 1);
    fallbackUsed = false(count, 1);
    fallbackReason = strings(count, 1);
    isFeasible = false(count, 1);
    for index = 1:count
        evaluationIndex(index) = iterations(index).evaluationIndex;
        selectionState(index) = iterations(index).selectionState;
        selectionSource(index) = iterations(index).selectionSource;
        fallbackUsed(index) = iterations(index).fallbackUsed;
        fallbackReason(index) = iterations(index).fallbackReason;
        isFeasible(index) = iterations(index).observation.isFeasible;
    end
    cumulativeFeasible = cumsum(double(isFeasible));
    outputTable = table( ...
        iteration, evaluationIndex, selectionState, selectionSource, ...
        fallbackUsed, fallbackReason, isFeasible, cumulativeFeasible, ...
        'VariableNames', { ...
        'Iteration', 'EvaluationIndex', 'SelectionState', ...
        'SelectionSource', 'FallbackUsed', 'FallbackReason', ...
        'ObservedFeasible', 'CumulativeSequentialFeasible'});
    firstFeasible = find(isFeasible, 1);

    palette = diagnosticPalette();
    figureHandle = figure( ...
        "Visible", "off", "Color", "white", ...
        "Units", "pixels", "Position", [100, 100, 1120, 900]);
    layout = tiledlayout(figureHandle, 3, 1, ...
        "TileSpacing", "compact", "Padding", "compact");
    title(layout, ...
        "BNH stress run: recovery from a zero-feasible initial design");

    axesHandle = nexttile(layout);
    stem(axesHandle, iteration, double(isFeasible), ...
        "filled", "Color", palette.blue, "MarkerSize", 4);
    hold(axesHandle, "on");
    if ~isempty(firstFeasible)
        xline(axesHandle, firstFeasible, "--", ...
            "First feasible observation", ...
            "LabelOrientation", "horizontal");
    end
    hold(axesHandle, "off");
    ylim(axesHandle, [-0.05, 1.15]);
    yticks(axesHandle, [0, 1]);
    yticklabels(axesHandle, ["Infeasible", "Feasible"]);
    ylabel(axesHandle, "Observed label");
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    states = unique(selectionState, "stable");
    stateIndex = zeros(count, 1);
    for index = 1:numel(states)
        stateIndex(selectionState == states(index)) = index;
    end
    scatter(axesHandle, iteration(~fallbackUsed), ...
        stateIndex(~fallbackUsed), 35, "o", ...
        "MarkerFaceColor", palette.blue, ...
        "MarkerEdgeColor", palette.ink);
    hold(axesHandle, "on");
    scatter(axesHandle, iteration(fallbackUsed), ...
        stateIndex(fallbackUsed), 50, "d", ...
        "MarkerFaceColor", palette.orange, ...
        "MarkerEdgeColor", palette.ink);
    hold(axesHandle, "off");
    yticks(axesHandle, 1:numel(states));
    yticklabels(axesHandle, states);
    ylabel(axesHandle, "Selection state");
    legend(axesHandle, ["Ordinary", "Fallback"], ...
        "Location", "best", "Box", "off");
    grid(axesHandle, "on");

    axesHandle = nexttile(layout);
    stairs(axesHandle, iteration, cumulativeFeasible, ...
        "-", "Color", palette.olive, "LineWidth", 1.5);
    xlabel(axesHandle, "Sequential iteration");
    ylabel(axesHandle, "Cumulative feasible points");
    title(axesHandle, ...
        compose("Initial design: %d/%d feasible", ...
        nnz(item.result.data.isFeasible( ...
        1:item.result.data.nInitial)), item.result.data.nInitial));
    grid(axesHandle, "on");

    caption = compose( ...
        "BNH stress-run timeline from an initial design containing %d " + ...
        "feasible points out of %d. The panels show the observed binary " + ...
        "label, the explicitly logged selection state/fallback, and the " + ...
        "cumulative number of feasible sequential evaluations.", ...
        nnz(item.result.data.isFeasible( ...
        1:item.result.data.nInitial)), item.result.data.nInitial);
end

function [figureHandle, summary, caption] = ...
        plotCampaignParetoPanels(cases)
    keys = ["COSSIN1", "COSSIN2", "BNH", ...
        "SRN", "C2DTLZ2", "WELDEDBEAM"];
    figureHandle = figure( ...
        "Visible", "off", "Color", "white", ...
        "Units", "pixels", "Position", [100, 100, 1450, 900]);
    layout = tiledlayout(figureHandle, 2, 3, ...
        "TileSpacing", "compact", "Padding", "compact");
    title(layout, "Final feasible Pareto-front approximations");
    palette = diagnosticPalette();

    caseColumn = strings(numel(keys), 1);
    observedCount = zeros(numel(keys), 1);
    feasibleCount = zeros(numel(keys), 1);
    paretoCount = zeros(numel(keys), 1);
    for index = 1:numel(keys)
        item = caseByKey(cases, keys(index));
        result = item.result;
        axesHandle = nexttile(layout);
        scatter(axesHandle, ...
            result.data.Y(result.data.isFeasible, 1), ...
            result.data.Y(result.data.isFeasible, 2), 18, "o", ...
            "MarkerFaceColor", "white", ...
            "MarkerEdgeColor", palette.blue);
        hold(axesHandle, "on");
        front = sortrows(result.pareto.Y, [1, 2]);
        plot(axesHandle, front(:, 1), front(:, 2), "-o", ...
            "Color", palette.blue, ...
            "MarkerFaceColor", palette.blue, "MarkerSize", 3.5, ...
            "LineWidth", 1.4);
        hold(axesHandle, "off");
        xlabel(axesHandle, objectiveLabel(item.problem, 1));
        ylabel(axesHandle, objectiveLabel(item.problem, 2));
        title(axesHandle, item.displayName, "Interpreter", "none");
        subtitle(axesHandle, compose( ...
            "%d feasible; %d nondominated", ...
            nnz(result.data.isFeasible), size(front, 1)));
        grid(axesHandle, "on");
        axesHandle.GridAlpha = 0.15;
        if index == 1
            legend(axesHandle, [ ...
                "Observed feasible", "Feasible nondominated"], ...
                "Location", "best", "Box", "off");
        end
        caseColumn(index) = item.key;
        observedCount(index) = size(result.data.Y, 1);
        feasibleCount(index) = nnz(result.data.isFeasible);
        paretoCount(index) = size(front, 1);
    end
    summary = table(caseColumn, observedCount, feasibleCount, paretoCount, ...
        'VariableNames', { ...
        'Case', 'ObservedCount', 'FeasibleCount', 'ParetoCount'});
    caption = ...
        "Final observed feasible objective vectors and nondominated sets " + ...
        "for the six core release cases. Each panel reports measured " + ...
        "feasible and nondominated counts; axes retain each benchmark's " + ...
        "native objective units and are not used for cross-problem ranking.";
end

function label = objectiveLabel(problem, index)
    name = string(problem.objectiveNames{index});
    unit = string(problem.objectiveUnits{index});
    if unit == ""
        label = name;
    else
        label = name + " (" + unit + ")";
    end
end

function [files, names, sourceTable] = ...
        weldedBeamCompetitorSources(summaryFile)
    summary = readtable(summaryFile, ...
        "TextType", "string", "VariableNamingRule", "preserve");
    requested = [ ...
        "BoTorch (150)"; "Trieste (150)"; "USeMOC (150)"; ...
        "COMBOO (150)"; "PAC-MOO (150)"];
    selected = ismember(summary.Solver, requested);
    sourceTable = summary(selected, [ ...
        "Solver", "Group", "EvaluationBudget", "Source"]);
    [~, order] = ismember(requested, sourceTable.Solver);
    if any(order == 0)
        error("cTSEMO:Diagnostics:MissingCompetitorSource", ...
            "The fixed welded-beam competitor source set is incomplete.");
    end
    sourceTable = sourceTable(order, :);
    sourceTable.InformationStatus = repmat( ...
        "continuous per-constraint margins", height(sourceTable), 1);
    sourceTable.ComparisonStatus = repmat( ...
        "unmatched exploratory overlay; no ranking", ...
        height(sourceTable), 1);
    files = string(sourceTable.Source);
    names = string(sourceTable.Solver);
    if any(~isfile(files))
        missing = files(~isfile(files));
        error("cTSEMO:Diagnostics:MissingCompetitorCsv", ...
            "Competitor CSV not found: %s", strjoin(missing, "; "));
    end
end

function summary = makeRasterSummary(raster)
    summary = table( ...
        raster.pointsPerDimension, raster.totalPoints, ...
        raster.gridPlacement, raster.threshold, ...
        raster.scoreSummary.minimum, raster.scoreSummary.maximum, ...
        raster.scoreSummary.mean, raster.scoreSummary.median, ...
        raster.scoreSummary.fractionAtZero, ...
        raster.scoreSummary.fractionAtOne, ...
        raster.errorSummary.truthFeasibleFraction, ...
        raster.errorSummary.predictedFeasibleFraction, ...
        raster.errorSummary.falseFeasibleCount, ...
        raster.errorSummary.falseInfeasibleCount, ...
        raster.errorSummary.correctCount, ...
        string(raster.ordering), ...
        'VariableNames', { ...
        'PointsPerDimension', 'TotalPoints', 'GridPlacement', ...
        'Threshold', 'MinimumP_i', 'MaximumP_i', 'MeanP_i', ...
        'MedianP_i', 'FractionAtZero', 'FractionAtOne', ...
        'TruthFeasibleFraction', 'PredictedFeasibleFraction', ...
        'FalseFeasibleCount', 'FalseInfeasibleCount', ...
        'CorrectCount', 'Ordering'});
end

function rasterProgress(fraction, stage)
    persistent lastStage lastDecile
    if isempty(lastStage) || string(stage) ~= lastStage
        lastStage = string(stage);
        lastDecile = -1;
    end
    decile = floor(10 * fraction);
    if decile > lastDecile || fraction >= 1
        fprintf("WB raster %s: %.0f%%\n", stage, 100 * fraction);
        lastDecile = decile;
    end
end

function [pngFile, pdfFile] = exportFigurePair( ...
        figureHandle, directory, baseName, resolution)
    pngFile = fullfile(directory, baseName + ".png");
    pdfFile = fullfile(directory, baseName + ".pdf");
    exportDiagnosticFigure(figureHandle, pngFile, resolution);
    exportDiagnosticFigure(figureHandle, pdfFile, resolution);
end

function manifest = emptyManifest()
    manifest = table( ...
        strings(0, 1), strings(0, 1), strings(0, 1), ...
        strings(0, 1), ...
        'VariableNames', {'Artifact', 'Type', 'Source', 'Description'});
end

function manifest = addManifest( ...
        manifest, artifact, type, source, description)
    row = table(string(artifact), string(type), ...
        string(source), string(description), ...
        'VariableNames', {'Artifact', 'Type', 'Source', 'Description'});
    manifest = [manifest; row];
end

function manifest = addFigurePair( ...
        manifest, pngFile, pdfFile, source, description)
    manifest = addManifest( ...
        manifest, pngFile, "figure", source, description);
    manifest = addManifest( ...
        manifest, pdfFile, "figure", source, description);
end

function captions = emptyCaptions()
    captions = table( ...
        strings(0, 1), strings(0, 1), strings(0, 1), ...
        'VariableNames', {'Figure', 'Caption', 'Source'});
end

function captions = addCaption(captions, figureFile, caption, source)
    row = table(string(figureFile), string(caption), string(source), ...
        'VariableNames', {'Figure', 'Caption', 'Source'});
    captions = [captions; row];
end
