function [runSummary, fieldMetrics, aggregate, paired, studyDirectory] = ...
        launch_full_study(outputRoot)
%LAUNCH_FULL_STUDY Run the complete matched-dimension PoF study.
%   LAUNCH_FULL_STUDY runs five replicates for seven benchmark instances
%   using 20 initial and 130 sequential evaluations per trajectory. Results
%   are written below the local results directory by default.
%
%   LAUNCH_FULL_STUDY(OUTPUTROOT) writes the study beneath OUTPUTROOT.

arguments
    outputRoot (1,1) string = fullfile( ...
        fileparts(mfilename("fullpath")), "results")
end

settings = struct( ...
    "ProblemIds", [ ...
        "WELDEDBEAM", ...
        "CF1_D4", "CF1_D10", ...
        "C2DTLZ2_D4_R02", "C2DTLZ2_D6_R02", ...
        "MW7_D4", "MW7_D6"], ...
    "Replicates", 1:5, ...
    "InitialCount", 20, ...
    "SequentialBudget", 130, ...
    "ProbeCount", 262144, ...
    "PredictionBatch", 5000, ...
    "PrimaryCount", 1024, ...
    "ChallengerCount", 512, ...
    "ObjectiveFeatures", 256, ...
    "RfTrees", 120, ...
    "RfMinLeafSize", 3, ...
    "StudyId", "matched_150eval_5seed", ...
    "OutputRoot", outputRoot, ...
    "ContinueOnFailure", true);

[runSummary, fieldMetrics, aggregate, paired, studyDirectory] = ...
    run_matched_dimension_pof_study(settings);

fprintf("STUDY_DIRECTORY=%s\n", studyDirectory);
fprintf("COMPLETED_RUNS=%d\n", nnz(runSummary.Status == "completed"));
fprintf("FAILED_RUNS=%d\n", nnz(runSummary.Status == "failed"));
fprintf("METRIC_ROWS=%d\n", height(fieldMetrics));
fprintf("AGGREGATE_ROWS=%d\n", height(aggregate));
fprintf("PAIRED_ROWS=%d\n", height(paired));
end
