function manifest = ...
        plot_manuscript_dimension_figures(resultDirectory)
%PLOT_MANUSCRIPT_DIMENSION_FIGURES Export chapter-ready PoF figures.
%   The figures use only the shipped clipped-GP-mean PoF. The rank plane
%   orders independent probe points by score and is not a geometric
%   projection of the original design space.

arguments
    resultDirectory (1,1) string
end

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(fileparts(scriptDirectory));
releaseRoot = fullfile(repositoryRoot, "src");
addpath(releaseRoot, fullfile(releaseRoot, "benchmarks"));

metricFile = fullfile(resultDirectory, "field_metrics.csv");
representativeFile = fullfile( ...
    resultDirectory, "figures", "d4_representative_runs.csv");
requireFile(metricFile, "field metrics");
requireFile(representativeFile, "representative-run registry");

metrics = readtable(metricFile, "TextType", "string");
representatives = readtable(representativeFile, "TextType", "string");
validateInputs(metrics, representatives);

outputDirectory = fullfile( ...
    resultDirectory, "figures", "manuscript_dimension");
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

pairedBase = fullfile( ...
    outputDirectory, "clipped_gp_paired_dimension_metrics");
rankBase = fullfile( ...
    outputDirectory, "clipped_gp_d4_ranked_score_truth");

exportPairedDimensionFigure(metrics, pairedBase);
exportRankTruthFigure( ...
    metrics, representatives, resultDirectory, rankBase);

artifactFiles = [ ...
    pairedBase + ".png"; ...
    pairedBase + ".pdf"; ...
    rankBase + ".png"; ...
    rankBase + ".pdf"];
figureIds = [ ...
    "paired_dimension"; ...
    "paired_dimension"; ...
    "ranked_score_truth"; ...
    "ranked_score_truth"];
formats = ["PNG"; "PDF"; "PNG"; "PDF"];
captions = [ ...
    "Paired clipped-GP feasibility-field metrics across dimensions."; ...
    "Paired clipped-GP feasibility-field metrics across dimensions."; ...
    "D4 ranked clipped-GP score and exact truth at identical ranks."; ...
    "D4 ranked clipped-GP score and exact truth at identical ranks."];
sources = [ ...
    metricFile; ...
    metricFile; ...
    metricFile + "; " + representativeFile + ...
        "; probes and GP predictions listed by representative run"; ...
    metricFile + "; " + representativeFile + ...
        "; probes and GP predictions listed by representative run"];
generatedUtc = repmat( ...
    string(datetime("now", ...
    "TimeZone", "UTC", "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'")), ...
    numel(artifactFiles), 1);
bytes = zeros(numel(artifactFiles), 1);
for artifactIndex = 1:numel(artifactFiles)
    requireFile(artifactFiles(artifactIndex), "exported figure");
    fileRecord = dir(artifactFiles(artifactIndex));
    bytes(artifactIndex) = fileRecord.bytes;
end

manifest = table( ...
    figureIds, artifactFiles, formats, bytes, captions, sources, ...
    generatedUtc, ...
    VariableNames=[ ...
    "FigureId", "Artifact", "Format", "Bytes", "Caption", ...
    "Source", "GeneratedUTC"]);
writetable(manifest, fullfile( ...
    outputDirectory, "manuscript_figure_manifest.csv"));
end

function validateInputs(metrics, representatives)
requiredMetricVariables = [ ...
    "ProblemId", "Family", "Dimension", "Replicate", "Method", ...
    "AUC", "FalsePositiveRate", "FalseNegativeRate", ...
    "BalancedError"];
requiredRepresentativeVariables = [ ...
    "ProblemId", "Dimension", "Replicate", "ProbeSeed", ...
    "ProbeCount", "PredictionFile"];
if ~all(ismember(requiredMetricVariables, ...
        string(metrics.Properties.VariableNames)))
    error("cTSEMO:ManuscriptDimensionFigure:MetricSchema", ...
        "field_metrics.csv does not have the required variables.");
end
if ~all(ismember(requiredRepresentativeVariables, ...
        string(representatives.Properties.VariableNames)))
    error("cTSEMO:ManuscriptDimensionFigure:RepresentativeSchema", ...
        "d4_representative_runs.csv does not have the required variables.");
end

gpMetrics = metrics(metrics.Method == "clipped_GP_mean", :);
requiredProblems = [ ...
    "WELDEDBEAM", "CF1_D4", "CF1_D10", ...
    "C2DTLZ2_D4_R02", "C2DTLZ2_D6_R02", ...
    "MW7_D4", "MW7_D6"];
for problemIndex = 1:numel(requiredProblems)
    selected = gpMetrics.ProblemId == requiredProblems(problemIndex);
    if nnz(selected) ~= 5
        error("cTSEMO:ManuscriptDimensionFigure:ReplicateCount", ...
            "Expected five clipped-GP rows for '%s'.", ...
            requiredProblems(problemIndex));
    end
end

bounded = [ ...
    gpMetrics.AUC, gpMetrics.FalsePositiveRate, ...
    gpMetrics.FalseNegativeRate, gpMetrics.BalancedError];
if any(~isfinite(bounded), "all") || ...
        any(bounded < 0 | bounded > 1, "all")
    error("cTSEMO:ManuscriptDimensionFigure:MetricBounds", ...
        "All plotted metrics must be finite and lie in [0,1].");
end
if height(representatives) ~= 4 || ...
        any(representatives.Dimension ~= 4) || ...
        ~all(ismember( ...
        ["WELDEDBEAM"; "CF1_D4"; "C2DTLZ2_D4_R02"; "MW7_D4"], ...
        representatives.ProblemId))
    error("cTSEMO:ManuscriptDimensionFigure:D4Registry", ...
        "The representative-run registry must contain the four D4 cases.");
end
end

function exportPairedDimensionFigure(metrics, outputBase)
gpMetrics = metrics(metrics.Method == "clipped_GP_mean", :);
metricNames = [ ...
    "FalsePositiveRate", "FalseNegativeRate", ...
    "BalancedError", "AUC"];
metricTitles = [ ...
    "(a) False-feasible rate (FPR)", ...
    "(b) False-infeasible rate (FNR)", ...
    "(c) Balanced error", ...
    "(d) Area under the ROC curve (AUC)"];
pairs = struct( ...
    "Family", {"CF1", "C2DTLZ2_R02", "MW7"}, ...
    "LowDimension", {4, 4, 4}, ...
    "HighDimension", {10, 6, 6}, ...
    "X", {[1, 2], [3.5, 4.5], [6, 7]}, ...
    "Label", {"CF1", "C2-DTLZ2", "MW7"});
colors = [ ...
    0.00, 0.35, 0.65; ...
    0.88, 0.40, 0.00; ...
    0.50, 0.20, 0.55];
markers = ["o", "s", "^"];
weldedBeamX = 8.5;
xTickPositions = [1, 2, 3.5, 4.5, 6, 7, weldedBeamX];
xTickLabels = [ ...
    "CF1 D4", "D10", "C2 D4", "D6", ...
    "MW7 D4", "D6", "WB D4"];

figureHandle = figure( ...
    "Visible", "off", "Color", "white", ...
    "Units", "inches", "Position", [0, 0, 7.2, 9.3]);
layout = tiledlayout(figureHandle, 2, 2, ...
    "TileSpacing", "compact", "Padding", "compact");

for metricIndex = 1:numel(metricNames)
    axisHandle = nexttile(layout);
    hold(axisHandle, "on");
    medianHandles = gobjects(numel(pairs), 1);
    for pairIndex = 1:numel(pairs)
        block = gpMetrics( ...
            gpMetrics.Family == string(pairs(pairIndex).Family), :);
        replicates = sort(unique(block.Replicate));
        lowValues = nan(numel(replicates), 1);
        highValues = nan(numel(replicates), 1);
        paleColor = 0.45 .* colors(pairIndex, :) + 0.55;
        for replicateIndex = 1:numel(replicates)
            replicate = replicates(replicateIndex);
            low = block( ...
                block.Replicate == replicate & ...
                block.Dimension == pairs(pairIndex).LowDimension, :);
            high = block( ...
                block.Replicate == replicate & ...
                block.Dimension == pairs(pairIndex).HighDimension, :);
            if height(low) ~= 1 || height(high) ~= 1
                error("cTSEMO:ManuscriptDimensionFigure:Pairing", ...
                    "Missing paired seed for '%s', replicate %d.", ...
                    pairs(pairIndex).Label, replicate);
            end
            lowValues(replicateIndex) = ...
                low.(metricNames(metricIndex));
            highValues(replicateIndex) = ...
                high.(metricNames(metricIndex));
            plot(axisHandle, pairs(pairIndex).X, ...
                [lowValues(replicateIndex), ...
                highValues(replicateIndex)], ...
                "-", "Color", paleColor, "LineWidth", 0.8, ...
                "Marker", markers(pairIndex), "MarkerSize", 3.5, ...
                "MarkerFaceColor", "white", ...
                "MarkerEdgeColor", paleColor, ...
                "HandleVisibility", "off");
        end
        medianHandles(pairIndex) = plot(axisHandle, ...
            pairs(pairIndex).X, ...
            [median(lowValues), median(highValues)], ...
            "-", "Color", colors(pairIndex, :), ...
            "LineWidth", 2.3, "Marker", markers(pairIndex), ...
            "MarkerSize", 6, ...
            "MarkerFaceColor", colors(pairIndex, :), ...
            "DisplayName", string(pairs(pairIndex).Label));
    end

    weldedBeam = gpMetrics( ...
        gpMetrics.ProblemId == "WELDEDBEAM", :);
    weldedBeamValues = weldedBeam.(metricNames(metricIndex));
    jitter = linspace(-0.10, 0.10, height(weldedBeam)).';
    scatter(axisHandle, weldedBeamX + jitter, ...
        weldedBeamValues, 17, [0.45, 0.45, 0.45], ...
        "d", "MarkerFaceColor", "white", ...
        "MarkerEdgeColor", [0.45, 0.45, 0.45], ...
        "LineWidth", 0.8, "HandleVisibility", "off");
    medianWeldedBeam = median(weldedBeamValues);
    weldedBeamHandle = plot(axisHandle, ...
        weldedBeamX + [-0.22, 0.22], ...
        [medianWeldedBeam, medianWeldedBeam], ...
        "-", "Color", [0.15, 0.15, 0.15], ...
        "LineWidth", 2.3, ...
        "DisplayName", "Welded beam (unpaired D4)");

    xline(axisHandle, 2.75, ":", ...
        "Color", [0.78, 0.78, 0.78], ...
        "HandleVisibility", "off");
    xline(axisHandle, 5.25, ":", ...
        "Color", [0.78, 0.78, 0.78], ...
        "HandleVisibility", "off");
    xline(axisHandle, 7.75, ":", ...
        "Color", [0.78, 0.78, 0.78], ...
        "HandleVisibility", "off");
    xlim(axisHandle, [0.65, 8.85]);
    ylim(axisHandle, [0, 1]);
    xticks(axisHandle, xTickPositions);
    xticklabels(axisHandle, xTickLabels);
    axisHandle.XTickLabelRotation = 24;
    axisHandle.FontName = "Arial";
    axisHandle.FontSize = 8.2;
    axisHandle.LineWidth = 0.7;
    axisHandle.GridColor = [0.83, 0.83, 0.83];
    axisHandle.GridAlpha = 0.55;
    grid(axisHandle, "on");
    box(axisHandle, "on");
    title(axisHandle, metricTitles(metricIndex), ...
        "FontWeight", "normal", "FontSize", 10);
    if metricIndex <= 3
        yticks(axisHandle, 0:0.2:1);
        yticklabels(axisHandle, compose("%d%%", 0:20:100));
    else
        yticks(axisHandle, 0:0.2:1);
        yticklabels(axisHandle, compose("%.1f", 0:0.2:1));
    end
    if metricIndex == 1
        legend(axisHandle, ...
            [medianHandles; weldedBeamHandle], ...
            "Location", "northwest", "FontSize", 7.2, ...
            "Box", "off");
    end
end

title(layout, ...
    "Clipped GP mean: paired field diagnostics across dimension", ...
    "FontName", "Arial", "FontSize", 12, "FontWeight", "bold");
subtitle(layout, ...
    "Five matched 20+130-evaluation seeds; thin lines are seeds, " + ...
    "thick lines are medians; WB is an unpaired D4 reference", ...
    "FontName", "Arial", "FontSize", 8.5);

exportgraphics(figureHandle, outputBase + ".png", ...
    "Resolution", 300);
exportgraphics(figureHandle, outputBase + ".pdf", ...
    "ContentType", "vector");
close(figureHandle);
end

function exportRankTruthFigure( ...
        metrics, representatives, resultDirectory, outputBase)
problemOrder = [ ...
    "WELDEDBEAM", "CF1_D4", "C2DTLZ2_D4_R02", "MW7_D4"];
problemLabels = [ ...
    "Welded beam", "CF1", "C2-DTLZ2", "MW7"];
representatives = sortRepresentativeRows( ...
    representatives, problemOrder);

figureHandle = figure( ...
    "Visible", "off", "Color", "white", ...
    "Units", "inches", "Position", [0, 0, 7.2, 10.1]);
layout = tiledlayout(figureHandle, 4, 2, ...
    "TileSpacing", "compact", "Padding", "compact");
scoreAxes = gobjects(numel(problemOrder), 1);

for problemIndex = 1:numel(problemOrder)
    selectedRow = representatives(problemIndex, :);
    problem = getBenchmarkProblem(selectedRow.ProblemId);
    probeFile = fullfile(resultDirectory, "probes", ...
        selectedRow.ProblemId + "_volume_probes.mat");
    requireFile(probeFile, "probe set");
    requireFile(selectedRow.PredictionFile, "GP prediction");

    probeRecord = load(probeFile, "probeX", "truth");
    predictionRecord = load( ...
        selectedRow.PredictionFile, "gpScore");
    exactTruth = logical(problem.feasible(probeRecord.probeX));
    if ~isequal(exactTruth, logical(probeRecord.truth))
        error("cTSEMO:ManuscriptDimensionFigure:TruthMismatch", ...
            "Stored truth differs from the benchmark for '%s'.", ...
            selectedRow.ProblemId);
    end
    if numel(exactTruth) ~= selectedRow.ProbeCount || ...
            numel(predictionRecord.gpScore) ~= numel(exactTruth)
        error("cTSEMO:ManuscriptDimensionFigure:ProbeCount", ...
            "Probe and prediction counts differ for '%s'.", ...
            selectedRow.ProblemId);
    end

    tieStream = RandStream( ...
        "mt19937ar", "Seed", double(selectedRow.ProbeSeed) + 991);
    tieKey = rand(tieStream, numel(exactTruth), 1);
    raster = constructRankRaster( ...
        predictionRecord.gpScore, exactTruth, tieKey);
    metricRow = metrics( ...
        metrics.ProblemId == selectedRow.ProblemId & ...
        metrics.Replicate == selectedRow.Replicate & ...
        metrics.Method == "clipped_GP_mean", :);
    if height(metricRow) ~= 1
        error("cTSEMO:ManuscriptDimensionFigure:MetricMultiplicity", ...
            "Expected one representative metric row for '%s'.", ...
            selectedRow.ProblemId);
    end

    scoreAxes(problemIndex) = nexttile(layout);
    plotScoreRaster(scoreAxes(problemIndex), raster.Score);
    title(scoreAxes(problemIndex), sprintf( ...
        "%s (replicate %d): clipped GP score\n" + ...
        "AUC %.3f; FPR %.1f%%; FNR %.1f%%", ...
        problemLabels(problemIndex), selectedRow.Replicate, ...
        metricRow.AUC, ...
        100 .* metricRow.FalsePositiveRate, ...
        100 .* metricRow.FalseNegativeRate), ...
        "FontWeight", "normal", "FontSize", 9);

    truthAxis = nexttile(layout);
    plotTruthRaster(truthAxis, raster.Truth);
    title(truthAxis, ...
        "Exact truth at identical rank positions", ...
        "FontWeight", "normal", "FontSize", 9);
end

colorbarHandle = colorbar(scoreAxes(1));
colorbarHandle.Layout.Tile = "east";
colorbarHandle.Label.String = "Clipped GP score, p_i";
colorbarHandle.FontName = "Arial";
colorbarHandle.FontSize = 8;

title(layout, ...
    "D4 clipped GP score versus exact binary feasibility", ...
    "FontName", "Arial", "FontSize", 12, "FontWeight", "bold");
subtitle(layout, ...
    "262,144 probes/problem; score descends from upper-left " + ...
    "to lower-right." + newline + ...
    "Rank-plane coordinates encode order only, not design-space " + ...
    "geometry. Truth: dark = violating; orange = feasible.", ...
    "FontName", "Arial", "FontSize", 7.8);

exportgraphics(figureHandle, outputBase + ".png", ...
    "Resolution", 300);
exportgraphics(figureHandle, outputBase + ".pdf", ...
    "ContentType", "vector");
close(figureHandle);
end

function representatives = sortRepresentativeRows( ...
        representatives, problemOrder)
rowOrder = zeros(numel(problemOrder), 1);
for problemIndex = 1:numel(problemOrder)
    selected = find( ...
        representatives.ProblemId == problemOrder(problemIndex));
    if numel(selected) ~= 1
        error("cTSEMO:ManuscriptDimensionFigure:RepresentativeCount", ...
            "Expected one representative row for '%s'.", ...
            problemOrder(problemIndex));
    end
    rowOrder(problemIndex) = selected;
end
representatives = representatives(rowOrder, :);
end

function raster = constructRankRaster(score, truth, tieKey)
score = min(1, max(0, double(score(:))));
truth = logical(truth(:));
tieKey = double(tieKey(:));
pointCount = numel(score);
sideLength = sqrt(pointCount);
if sideLength ~= floor(sideLength)
    error("cTSEMO:ManuscriptDimensionFigure:NonSquareProbeCount", ...
        "The rank raster requires a square probe count.");
end
sideLength = round(sideLength);
[~, order] = sortrows([-score, tieKey], [1, 2]);
sortedScore = score(order);
sortedTruth = truth(order);
scoreImage = zeros(sideLength);
truthImage = false(sideLength);
cursor = 1;
for diagonal = 2:(2 * sideLength)
    row = max(1, diagonal - sideLength): ...
        min(sideLength, diagonal - 1);
    column = diagonal - row;
    position = sub2ind([sideLength, sideLength], row, column);
    rank = cursor:(cursor + numel(position) - 1);
    scoreImage(position) = sortedScore(rank);
    truthImage(position) = sortedTruth(rank);
    cursor = cursor + numel(position);
end
if cursor ~= pointCount + 1
    error("cTSEMO:ManuscriptDimensionFigure:RankMapping", ...
        "The rank mapping did not consume every probe.");
end
raster = struct("Score", scoreImage, "Truth", truthImage);
end

function plotScoreRaster(axisHandle, scoreImage)
imagesc(axisHandle, [0, 1], [0, 1], scoreImage, [0, 1]);
axisHandle.YDir = "reverse";
axis(axisHandle, "image");
colormap(axisHandle, parula(256));
formatRasterAxis(axisHandle);
end

function plotTruthRaster(axisHandle, truthImage)
imagesc(axisHandle, ...
    [0, 1], [0, 1], double(truthImage), [0, 1]);
axisHandle.YDir = "reverse";
axis(axisHandle, "image");
colormap(axisHandle, [ ...
    0.16, 0.18, 0.20; ...
    0.95, 0.55, 0.10]);
formatRasterAxis(axisHandle);
end

function formatRasterAxis(axisHandle)
axisHandle.XTick = [];
axisHandle.YTick = [];
axisHandle.FontName = "Arial";
axisHandle.LineWidth = 0.7;
box(axisHandle, "on");
end

function requireFile(fileName, description)
if ~isfile(fileName)
    error("cTSEMO:ManuscriptDimensionFigure:MissingFile", ...
        "Missing %s: %s", description, fileName);
end
end
