function artifacts = ...
        plot_matched_dimension_pof_study(studyDirectory)
%PLOT_MATCHED_DIMENSION_POF_STUDY Plot fixed-budget PoF evidence.
%   The rank plane in the exported diagnostic figures is a score ordering,
%   not a geometric projection of the original design space.

arguments
    studyDirectory (1,1) string
end

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(fileparts(scriptDirectory));
releaseRoot = fullfile(repositoryRoot, "src");
addpath(releaseRoot, fullfile(releaseRoot, "benchmarks"));

runFile = fullfile(studyDirectory, "run_summary.csv");
metricFile = fullfile(studyDirectory, "field_metrics.csv");
if ~isfile(runFile) || ~isfile(metricFile)
    error("cTSEMO:DimensionStudyPlot:MissingInput", ...
        "The completed run_summary.csv and field_metrics.csv are required.");
end
runTable = readtable(runFile, "TextType", "string");
metricTable = readtable(metricFile, "TextType", "string");
validateCampaignTables(runTable, metricTable);

outputDirectory = fullfile(studyDirectory, "figures");
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

representatives = selectD4Representatives(runTable);
artifacts = strings(2 + height(representatives), 1);
artifacts(1) = plotPairedDimensionMetrics( ...
    metricTable, outputDirectory);
artifacts(2) = plotAllProblemMetrics( ...
    metricTable, outputDirectory);

writetable(representatives, ...
    fullfile(outputDirectory, "d4_representative_runs.csv"));
for rowIndex = 1:height(representatives)
    artifacts(2 + rowIndex) = plotD4Representative( ...
        representatives(rowIndex, :), metricTable, ...
        studyDirectory, outputDirectory);
end

writetable(table(artifacts, VariableNames="Artifact"), ...
    fullfile(outputDirectory, "figure_manifest.csv"));
end

function validateCampaignTables(runs, metrics)
requiredRun = [ ...
    "ProblemId", "Family", "Dimension", "Replicate", "Status", ...
    "TotalEvaluations", "FinalFeasibleCount", "FinalParetoCount", ...
    "ProbeSeed", "ProbeCount", "ResultFile", "PredictionFile"];
requiredMetric = [ ...
    "ProblemId", "Family", "Dimension", "Replicate", "Method", ...
    "AUC", "FalsePositiveRate", "FalseNegativeRate", ...
    "BalancedError", "Brier", "BalancedBrier", ...
    "ProbeFeasibleRate", "PredictionFile"];
if ~all(ismember(requiredRun, string(runs.Properties.VariableNames)))
    error("cTSEMO:DimensionStudyPlot:RunSchema", ...
        "run_summary.csv does not have the required schema.");
end
if ~all(ismember(requiredMetric, ...
        string(metrics.Properties.VariableNames)))
    error("cTSEMO:DimensionStudyPlot:MetricSchema", ...
        "field_metrics.csv does not have the required schema.");
end
if any(runs.Status ~= "completed")
    error("cTSEMO:DimensionStudyPlot:IncompleteCampaign", ...
        "All trajectories must be completed before plotting.");
end
if any(runs.TotalEvaluations ~= 150)
    error("cTSEMO:DimensionStudyPlot:EvaluationCount", ...
        "Every full-study trajectory must contain 150 evaluations.");
end
bounded = [ ...
    metrics.AUC, metrics.FalsePositiveRate, ...
    metrics.FalseNegativeRate, metrics.BalancedError, ...
    metrics.Brier, metrics.BalancedBrier, ...
    metrics.ProbeFeasibleRate];
if any(~isfinite(bounded), "all") || ...
        any(bounded < 0 | bounded > 1, "all")
    error("cTSEMO:DimensionStudyPlot:InvalidMetric", ...
        "Expected all plotted field metrics to lie in [0,1].");
end
end

function outputFile = plotPairedDimensionMetrics(metrics, outputDirectory)
methods = ["clipped_GP_mean", "offline_RF_proxy"];
methodTitles = ["Clipped GP mean", "Offline RF proxy"];
metricNames = [ ...
    "FalsePositiveRate", "FalseNegativeRate", ...
    "BalancedError", "AUC"];
metricTitles = [ ...
    "False-feasible rate (FPR)", ...
    "False-infeasible rate (FNR)", ...
    "Balanced error", "ROC AUC"];
pairs = struct( ...
    "Family", {"CF1", "C2DTLZ2_R02", "MW7"}, ...
    "LowDimension", {4, 4, 4}, ...
    "HighDimension", {10, 6, 6}, ...
    "Label", {"CF1", "C2-DTLZ2", "MW7"});
colors = [ ...
    0.00, 0.45, 0.70; ...
    0.84, 0.37, 0.00; ...
    0.00, 0.62, 0.45];
markers = ["o", "s", "^"];

figureHandle = figure( ...
    "Visible", "off", "Color", "white", ...
    "Position", [60, 60, 1680, 800]);
layout = tiledlayout(figureHandle, 2, 4, ...
    "TileSpacing", "compact", "Padding", "compact");
for methodIndex = 1:numel(methods)
    for metricIndex = 1:numel(metricNames)
        axisHandle = nexttile(layout);
        hold(axisHandle, "on");
        for pairIndex = 1:numel(pairs)
            family = string(pairs(pairIndex).Family);
            block = metrics( ...
                metrics.Method == methods(methodIndex) & ...
                metrics.Family == family, :);
            replicates = unique(block.Replicate, "stable");
            lowValues = nan(numel(replicates), 1);
            highValues = nan(numel(replicates), 1);
            for replicateIndex = 1:numel(replicates)
                selected = block.Replicate == ...
                    replicates(replicateIndex);
                low = block(selected & block.Dimension == ...
                    pairs(pairIndex).LowDimension, :);
                high = block(selected & block.Dimension == ...
                    pairs(pairIndex).HighDimension, :);
                if height(low) ~= 1 || height(high) ~= 1
                    continue
                end
                lowValues(replicateIndex) = ...
                    low.(metricNames(metricIndex));
                highValues(replicateIndex) = ...
                    high.(metricNames(metricIndex));
                plot(axisHandle, ...
                    [pairs(pairIndex).LowDimension, ...
                    pairs(pairIndex).HighDimension], ...
                    [lowValues(replicateIndex), ...
                    highValues(replicateIndex)], ...
                    "-", "Color", 0.65 .* colors(pairIndex, :) + 0.35, ...
                    "LineWidth", 0.8, "HandleVisibility", "off");
            end
            plot(axisHandle, ...
                [pairs(pairIndex).LowDimension, ...
                pairs(pairIndex).HighDimension], ...
                [median(lowValues, "omitnan"), ...
                median(highValues, "omitnan")], ...
                "-", "Color", colors(pairIndex, :), ...
                "Marker", markers(pairIndex), ...
                "MarkerFaceColor", colors(pairIndex, :), ...
                "LineWidth", 2.2, ...
                "DisplayName", string(pairs(pairIndex).Label));
        end

        weldedBeam = metrics( ...
            metrics.Method == methods(methodIndex) & ...
            metrics.ProblemId == "WELDEDBEAM", :);
        if ~isempty(weldedBeam)
            scatter(axisHandle, ...
                4 .* ones(height(weldedBeam), 1), ...
                weldedBeam.(metricNames(metricIndex)), ...
                22, [0.35, 0.35, 0.35], "d", "filled", ...
                "MarkerFaceAlpha", 0.55, ...
                "HandleVisibility", "off");
            scatter(axisHandle, 4, ...
                median(weldedBeam.(metricNames(metricIndex)), "omitnan"), ...
                70, [0.15, 0.15, 0.15], "d", "filled", ...
                "DisplayName", "Welded beam (unpaired D4)");
        end
        ylim(axisHandle, [0, 1]);
        xlim(axisHandle, [3.5, 10.5]);
        xticks(axisHandle, [4, 6, 10]);
        grid(axisHandle, "on");
        box(axisHandle, "on");
        if methodIndex == 2
            xlabel(axisHandle, "Input dimension");
        end
        if metricIndex == 1
            ylabel(axisHandle, methodTitles(methodIndex));
        end
        title(axisHandle, metricTitles(metricIndex));
        if methodIndex == 1 && metricIndex == 1
            legend(axisHandle, "Location", "best", ...
                "FontSize", 8);
        end
    end
end
title(layout, [ ...
    "Matched 20+130 evaluation PoF diagnostics; thin lines are seeds, " ...
    "thick lines are medians"]);
outputFile = string(fullfile(outputDirectory, ...
    "paired_dimension_gp_rf_metrics.png"));
exportgraphics(figureHandle, outputFile, "Resolution", 240);
exportgraphics(figureHandle, replace(outputFile, ".png", ".pdf"), ...
    "ContentType", "vector");
close(figureHandle);
end

function outputFile = plotAllProblemMetrics(metrics, outputDirectory)
problemIds = [ ...
    "WELDEDBEAM", "CF1_D4", "CF1_D10", ...
    "C2DTLZ2_D4_R02", "C2DTLZ2_D6_R02", ...
    "MW7_D4", "MW7_D6"];
problemLabels = [ ...
    "WB D4", "CF1 D4", "CF1 D10", ...
    "C2 D4", "C2 D6", "MW7 D4", "MW7 D6"];
methods = ["clipped_GP_mean", "offline_RF_proxy"];
methodTitles = ["Clipped GP mean", "Offline RF proxy"];
metricNames = [ ...
    "FalsePositiveRate", "FalseNegativeRate", ...
    "BalancedError", "AUC"];
metricTitles = ["FPR", "FNR", "Balanced error", "ROC AUC"];
colors = [0.00, 0.45, 0.70; 0.84, 0.37, 0.00];

figureHandle = figure( ...
    "Visible", "off", "Color", "white", ...
    "Position", [60, 60, 1680, 800]);
layout = tiledlayout(figureHandle, 2, 4, ...
    "TileSpacing", "compact", "Padding", "compact");
for methodIndex = 1:numel(methods)
    for metricIndex = 1:numel(metricNames)
        axisHandle = nexttile(layout);
        hold(axisHandle, "on");
        for problemIndex = 1:numel(problemIds)
            selected = metrics.Method == methods(methodIndex) & ...
                metrics.ProblemId == problemIds(problemIndex);
            values = metrics.(metricNames(metricIndex))(selected);
            jitter = linspace(-0.10, 0.10, numel(values)).';
            scatter(axisHandle, ...
                problemIndex + jitter, values, 24, ...
                colors(methodIndex, :), "filled", ...
                "MarkerFaceAlpha", 0.50, ...
                "HandleVisibility", "off");
            plot(axisHandle, ...
                [problemIndex - 0.22, problemIndex + 0.22], ...
                repmat(median(values, "omitnan"), 1, 2), ...
                "Color", 0.55 .* colors(methodIndex, :), ...
                "LineWidth", 2.4);
        end
        xlim(axisHandle, [0.5, numel(problemIds) + 0.5]);
        ylim(axisHandle, [0, 1]);
        xticks(axisHandle, 1:numel(problemIds));
        xticklabels(axisHandle, problemLabels);
        axisHandle.XTickLabelRotation = 25;
        grid(axisHandle, "on");
        box(axisHandle, "on");
        title(axisHandle, metricTitles(metricIndex));
        if metricIndex == 1
            ylabel(axisHandle, methodTitles(methodIndex));
        end
    end
end
title(layout, ...
    "Final feasibility-field metrics on 262,144 independent probes");
outputFile = string(fullfile(outputDirectory, ...
    "all_problem_gp_rf_metrics.png"));
exportgraphics(figureHandle, outputFile, "Resolution", 240);
exportgraphics(figureHandle, replace(outputFile, ".png", ".pdf"), ...
    "ContentType", "vector");
close(figureHandle);
end

function selected = selectD4Representatives(runs)
problemIds = [ ...
    "WELDEDBEAM", "CF1_D4", ...
    "C2DTLZ2_D4_R02", "MW7_D4"];
indices = zeros(numel(problemIds), 1);
for problemIndex = 1:numel(problemIds)
    candidates = find( ...
        runs.ProblemId == problemIds(problemIndex) & ...
        runs.Status == "completed");
    if isempty(candidates)
        error("cTSEMO:DimensionStudyPlot:MissingD4Run", ...
            "No completed run exists for '%s'.", ...
            problemIds(problemIndex));
    end
    feasibleTarget = median( ...
        runs.FinalFeasibleCount(candidates), "omitnan");
    paretoTarget = median( ...
        runs.FinalParetoCount(candidates), "omitnan");
    key = [ ...
        abs(runs.FinalFeasibleCount(candidates) - feasibleTarget), ...
        abs(runs.FinalParetoCount(candidates) - paretoTarget), ...
        runs.Replicate(candidates)];
    [~, localIndex] = sortrows(key, [1, 2, 3]);
    indices(problemIndex) = candidates(localIndex(1));
end
selected = runs(indices, :);
end

function outputFile = plotD4Representative( ...
        selectedRow, metrics, studyDirectory, outputDirectory)
problem = getBenchmarkProblem(selectedRow.ProblemId);
    resultFile = resolveCampaignFile( ...
        selectedRow.ResultFile, studyDirectory);
    resultRecord = load(resultFile, "result");
result = resultRecord.result;
probeFile = fullfile(studyDirectory, "probes", ...
    selectedRow.ProblemId + "_volume_probes.mat");
probeRecord = load(probeFile, "probeX", "truth");
    predictionFile = resolveCampaignFile( ...
        selectedRow.PredictionFile, studyDirectory);
    predictionRecord = load( ...
        predictionFile, "gpScore", "rfScore");
probeX = probeRecord.probeX;
probeTruth = logical(probeRecord.truth);
gpScore = predictionRecord.gpScore;
rfScore = predictionRecord.rfScore;

if numel(probeTruth) ~= selectedRow.ProbeCount || ...
        numel(gpScore) ~= numel(probeTruth) || ...
        numel(rfScore) ~= numel(probeTruth)
    error("cTSEMO:DimensionStudyPlot:PredictionCount", ...
        "Probe and prediction counts do not agree.");
end
exactTruth = logical(problem.feasible(probeX));
if ~isequal(probeTruth, exactTruth)
    error("cTSEMO:DimensionStudyPlot:TruthMismatch", ...
        "Stored and recomputed probe truth disagree.");
end

tieStream = RandStream( ...
    "mt19937ar", "Seed", double(selectedRow.ProbeSeed) + 991);
tieKey = rand(tieStream, numel(probeTruth), 1);
gpRaster = constructRankRaster( ...
    gpScore, probeTruth, tieKey, 0.5);
rfRaster = constructRankRaster( ...
    rfScore, probeTruth, tieKey, 0.5);

gpMetric = metrics( ...
    metrics.ProblemId == selectedRow.ProblemId & ...
    metrics.Replicate == selectedRow.Replicate & ...
    metrics.Method == "clipped_GP_mean", :);
rfMetric = metrics( ...
    metrics.ProblemId == selectedRow.ProblemId & ...
    metrics.Replicate == selectedRow.Replicate & ...
    metrics.Method == "offline_RF_proxy", :);
if height(gpMetric) ~= 1 || height(rfMetric) ~= 1
    error("cTSEMO:DimensionStudyPlot:MetricMultiplicity", ...
        "Exactly one metric row is required for each method.");
end

figureHandle = figure( ...
    "Visible", "off", "Color", "white", ...
    "Position", [20, 80, 2450, 570]);
layout = tiledlayout(figureHandle, 1, 7, ...
    "TileSpacing", "compact", "Padding", "compact");

axisHandle = nexttile(layout);
plotObjectiveEvidence(axisHandle, problem, probeX, ...
    probeTruth, result);
title(axisHandle, "Objective-space evidence");

plotScoreRaster(nexttile(layout), gpRaster.Score, ...
    "GP ranked score");
plotTruthRaster(nexttile(layout), gpRaster.Truth, ...
    "Truth at GP ranks");
plotConfusionRaster(nexttile(layout), gpRaster.Confusion, ...
    sprintf("GP: AUC %.3f, FPR %.1f%%, FNR %.1f%%", ...
    gpMetric.AUC, 100 .* gpMetric.FalsePositiveRate, ...
    100 .* gpMetric.FalseNegativeRate));

plotScoreRaster(nexttile(layout), rfRaster.Score, ...
    "RF ranked score");
plotTruthRaster(nexttile(layout), rfRaster.Truth, ...
    "Truth at RF ranks");
plotConfusionRaster(nexttile(layout), rfRaster.Confusion, ...
    sprintf("RF: AUC %.3f, FPR %.1f%%, FNR %.1f%%", ...
    rfMetric.AUC, 100 .* rfMetric.FalsePositiveRate, ...
    100 .* rfMetric.FalseNegativeRate));

title(layout, sprintf( ...
    "%s, representative replicate %d; " + ...
    "rank plane is not a geometric projection", ...
    strrep(selectedRow.ProblemId, "_", " "), ...
    selectedRow.Replicate));
outputFile = string(fullfile(outputDirectory, ...
    lower(selectedRow.ProblemId) + ...
    "_pf_gp_rf_rank_truth_confusion.png"));
exportgraphics(figureHandle, outputFile, "Resolution", 220);
exportgraphics(figureHandle, replace(outputFile, ".png", ".pdf"), ...
    "ContentType", "vector");
close(figureHandle);
end

function plotObjectiveEvidence(axisHandle, problem, probeX, truth, result)
probeY = problem.objective(probeX);
feasibleY = probeY(truth, :);
probeFront = ctsemo.pareto2d(feasibleY);
displayLimit = 25000;
if size(feasibleY, 1) > displayLimit
    displayIndex = unique(round(linspace( ...
        1, size(feasibleY, 1), displayLimit)));
else
    displayIndex = 1:size(feasibleY, 1);
end
scatter(axisHandle, ...
    feasibleY(displayIndex, 1), feasibleY(displayIndex, 2), ...
    3, [0.72, 0.82, 0.90], "filled", ...
    "MarkerFaceAlpha", 0.25, ...
    "DisplayName", "Exact-feasible probes");
hold(axisHandle, "on");
plot(axisHandle, probeFront(:, 1), probeFront(:, 2), ...
    "-", "Color", [0.00, 0.30, 0.55], ...
    "LineWidth", 1.8, "DisplayName", "Probe PF approximation");
observedTruth = logical(result.data.isFeasible);
scatter(axisHandle, ...
    result.data.Y(~observedTruth, 1), ...
    result.data.Y(~observedTruth, 2), ...
    18, [0.35, 0.35, 0.35], "x", ...
    "DisplayName", "Evaluated violating (clipped)");
scatter(axisHandle, ...
    result.data.Y(observedTruth, 1), ...
    result.data.Y(observedTruth, 2), ...
    22, [0.85, 0.33, 0.10], "filled", ...
    "DisplayName", "Evaluated feasible");
if ~isempty(result.pareto.Y)
    plot(axisHandle, ...
        result.pareto.Y(:, 1), result.pareto.Y(:, 2), ...
        "o-", "Color", [0.50, 0.00, 0.50], ...
        "MarkerFaceColor", [0.50, 0.00, 0.50], ...
        "LineWidth", 1.4, "MarkerSize", 3.5, ...
        "DisplayName", "Evaluated feasible PF");
end
feasibleView = [feasibleY; result.data.Y(observedTruth, :)];
xlim(axisHandle, paddedLimits(feasibleView(:, 1)));
ylim(axisHandle, paddedLimits(feasibleView(:, 2)));
xlabel(axisHandle, "f_1");
ylabel(axisHandle, "f_2");
grid(axisHandle, "on");
box(axisHandle, "on");
legend(axisHandle, "Location", "best", "FontSize", 6);
end

function limits = paddedLimits(values)
values = double(values(isfinite(values)));
if isempty(values)
    limits = [0, 1];
    return
end
lower = min(values);
upper = max(values);
span = upper - lower;
if span <= 100 * eps(max(1, max(abs([lower, upper]))))
    span = max(1, abs(lower));
end
padding = 0.04 .* span;
limits = [lower - padding, upper + padding];
end

function raster = constructRankRaster(score, truth, tieKey, threshold)
score = min(1, max(0, double(score(:))));
truth = logical(truth(:));
tieKey = double(tieKey(:));
pointCount = numel(score);
sideLength = sqrt(pointCount);
if sideLength ~= floor(sideLength)
    error("cTSEMO:DimensionStudyPlot:NonSquareProbeCount", ...
        "The rank raster requires a square probe count.");
end
sideLength = round(sideLength);
[~, order] = sortrows([-score, tieKey], [1, 2]);
sortedScore = score(order);
sortedTruth = truth(order);
scoreImage = zeros(sideLength);
truthImage = false(sideLength);
cursor = 1;
for diagonal = 2:(2 * sideLength)
    row = max(1, diagonal - sideLength): ...
        min(sideLength, diagonal - 1);
    column = diagonal - row;
    position = sub2ind([sideLength, sideLength], row, column);
    rank = cursor:(cursor + numel(position) - 1);
    scoreImage(position) = sortedScore(rank);
    truthImage(position) = sortedTruth(rank);
    cursor = cursor + numel(position);
end
if cursor ~= pointCount + 1
    error("cTSEMO:DimensionStudyPlot:RankMapping", ...
        "The rank mapping did not consume every probe.");
end
predicted = scoreImage >= threshold;
confusion = zeros(sideLength, sideLength, "uint8");
confusion(predicted & truthImage) = 1;
confusion(predicted & ~truthImage) = 2;
confusion(~predicted & truthImage) = 3;
raster = struct( ...
    "Score", scoreImage, ...
    "Truth", truthImage, ...
    "Confusion", confusion, ...
    "Order", order);
end

function plotScoreRaster(axisHandle, scoreImage, titleText)
imagesc(axisHandle, [0, 1], [0, 1], scoreImage, [0, 1]);
axisHandle.YDir = "reverse";
axis(axisHandle, "image");
colormap(axisHandle, turbo(256));
colorbar(axisHandle);
xlabel(axisHandle, "rank-plane x");
ylabel(axisHandle, "rank-plane y");
title(axisHandle, titleText);
end

function plotTruthRaster(axisHandle, truthImage, titleText)
imagesc(axisHandle, [0, 1], [0, 1], double(truthImage), [0, 1]);
axisHandle.YDir = "reverse";
axis(axisHandle, "image");
colormap(axisHandle, [0.16, 0.18, 0.20; 0.95, 0.55, 0.10]);
xlabel(axisHandle, "rank-plane x");
ylabel(axisHandle, "rank-plane y");
title(axisHandle, titleText);
end

function plotConfusionRaster(axisHandle, confusion, titleText)
imagesc(axisHandle, [0, 1], [0, 1], double(confusion), [-0.5, 3.5]);
axisHandle.YDir = "reverse";
axis(axisHandle, "image");
colormap(axisHandle, [ ...
    0.20, 0.22, 0.24; ...
    0.00, 0.62, 0.45; ...
    0.84, 0.15, 0.16; ...
    0.00, 0.45, 0.70]);
colorbarHandle = colorbar(axisHandle);
colorbarHandle.Ticks = 0:3;
colorbarHandle.TickLabels = ["TN", "TP", "false feasible", "false infeasible"];
xlabel(axisHandle, "rank-plane x");
ylabel(axisHandle, "rank-plane y");
title(axisHandle, titleText);
end

function pathValue = resolveCampaignFile(storedPath, studyDirectory)
pathValue = string(storedPath);
normalized = replace(pathValue, "/", filesep);
marker = filesep + "runs" + filesep;
location = strfind(lower(normalized), lower(marker));
if ~isempty(location)
    suffix = extractAfter(normalized, ...
        location(end) + strlength(marker) - 1);
    rebasedPath = fullfile(studyDirectory, "runs", suffix);
    if isfile(rebasedPath)
        pathValue = rebasedPath;
        return
    end
end
if isfile(pathValue)
    return
end
error("cTSEMO:DimensionStudyPlot:ArtifactMissing", ...
    "Cannot resolve campaign artifact '%s' below %s.", ...
    storedPath, studyDirectory);
end
