function [runSummary, fieldMetrics, aggregate, paired, studyDirectory] = ...
        run_matched_dimension_pof_study(settings)
%RUN_MATCHED_DIMENSION_POF_STUDY Fixed-budget PoF dimension screen.
%   This study runs the current complete-pool cTSEMO implementation on
%   matched 4-D/higher-dimensional benchmark-family pairs and on welded
%   beam as an unpaired 4-D engineering anchor. Every run uses 20
%   corner-free LHS observations plus 130 sequential evaluations by
%   default. The final shipped clipped GP-mean field and an offline random
%   forest proxy are evaluated on identical independent volume probes.
%
%   SETTINGS is an optional scalar struct with these fields:
%     ProblemIds         default WB, CF1 D4/D10, C2-DTLZ2 D4/D6, MW7 D4/D6
%     Replicates         default 1:5
%     InitialCount       default 20
%     SequentialBudget   default 130
%     ProbeCount         default 262144 (512^2)
%     PredictionBatch    default 5000
%     PrimaryCount       default 1024
%     ChallengerCount    default 512
%     ObjectiveFeatures  default 256
%     RfTrees            default 120
%     RfMinLeafSize      default 3
%     StudyId            default unique run identifier
%     OutputRoot         default results below this script
%     ContinueOnFailure  default true
%
%   The RF proxy is fitted offline to the final GP-guided data. It is a
%   fixed-data diagnostic, not an online comparison of optimizer policies.

if nargin < 1 || isempty(settings)
    settings = struct();
end
settings = resolveSettings(settings);

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(fileparts(scriptDirectory));
releaseRoot = fullfile(repositoryRoot, "src");
benchmarkRoot = fullfile(releaseRoot, "benchmarks");
previousPath = path;
restorePath = onCleanup(@() path(previousPath));
addpath(releaseRoot, benchmarkRoot);

studyDirectory = string(fullfile(settings.OutputRoot, settings.StudyId));
createDirectory(studyDirectory);
createDirectory(fullfile(studyDirectory, "runs"));
createDirectory(fullfile(studyDirectory, "probes"));

sourceSignature = sha256Text(fileread(mfilename("fullpath") + ".m"));
settingsSignature = sha256Text(jsonencode(orderfields(settings)));
manifest = makeManifest( ...
    settings, sourceSignature, settingsSignature);
ensureCompatibleManifest( ...
    fullfile(studyDirectory, "study_manifest.json"), manifest);

runRows = repmat(emptyRunRow(), 0, 1);
metricRows = repmat(emptyMetricRow(), 0, 1);
problemIds = string(settings.ProblemIds(:)).';
replicates = reshape(double(settings.Replicates), 1, []);

for problemIndex = 1:numel(problemIds)
    problem = getBenchmarkProblem(problemIds(problemIndex));
    family = familyForProblem(problem.id);
    probeSeed = probeSeedForProblem(problem.id);
    probeFile = fullfile(studyDirectory, "probes", ...
        problem.id + "_volume_probes.mat");
    [~, probeUnit, probeTruth] = loadOrCreateProbes( ...
        probeFile, problem, settings.ProbeCount, probeSeed);

    for replicate = replicates
        initialSeed = 2026073200 + replicate;
        solverSeed = 2026073300 + replicate;
        rfSeed = rfSeedForProblem(problem.id, replicate);
        runKey = sprintf("%s_rep%02d", problem.id, replicate);
        runRoot = fullfile(studyDirectory, "runs", runKey);
        createDirectory(runRoot);
        recordFile = fullfile(runRoot, "campaign_record.mat");

        [wasLoaded, loadedRun, loadedMetrics] = ...
            loadCompletedRecord( ...
            recordFile, settingsSignature, sourceSignature);
        if wasLoaded
            runRows(end + 1, 1) = loadedRun; %#ok<AGROW>
            metricRows = [metricRows; loadedMetrics(:)]; %#ok<AGROW>
            continue
        end

        runRow = emptyRunRow();
        runRow.ProblemId = string(problem.id);
        runRow.Family = family;
        runRow.Dimension = problem.dimension;
        runRow.Replicate = replicate;
        runRow.Status = "pending";
        runRow.InitialSeed = initialSeed;
        runRow.SolverSeed = solverSeed;
        runRow.ProbeSeed = probeSeed;
        runRow.RfSeed = rfSeed;
        runRow.InitialCount = settings.InitialCount;
        runRow.SequentialBudget = settings.SequentialBudget;
        runRow.ProbeCount = settings.ProbeCount;
        runRow.ProbeFeasibleCount = nnz(probeTruth);
        runRow.ProbeInfeasibleCount = nnz(~probeTruth);
        runRow.ProbeFeasibleRate = mean(probeTruth);

        try
            [X0, designInfo] = initialDesign( ...
                problem, settings.InitialCount, initialSeed, ...
                struct("IncludeCorners", false));
            Y0 = problem.objective(X0);
            C0 = problem.label01(X0);
            runRow.InitialFeasibleCount = designInfo.FeasibleCount;

            overrides = struct( ...
                "maxEvaluations", settings.SequentialBudget, ...
                "seed", solverSeed, ...
                "feasibility", struct( ...
                    "inputEncoding", "feasibleIsOne"), ...
                "candidates", struct( ...
                    "primaryCount", settings.PrimaryCount, ...
                    "includeCorners", false), ...
                "objectiveGP", struct( ...
                    "nFeatures", settings.ObjectiveFeatures), ...
                "challengers", struct( ...
                    "enabled", true, ...
                    "count", settings.ChallengerCount, ...
                    "scoreCompletePools", true), ...
                "logging", struct( ...
                    "level", "summary", ...
                    "directory", string(runRoot), ...
                    "checkpoint", true, ...
                    "saveEveryIteration", false));
            options = cTSEMOOptions(overrides);

            result = cTSEMO( ...
                problem.objective, problem.label01, ...
                X0, Y0, C0, ...
                problem.lowerBound, problem.upperBound, options);
            resultFile = fullfile(result.meta.outputDirectory, "result.mat");
            if ~isfile(resultFile)
                error("cTSEMO:DimensionStudy:MissingResult", ...
                    "The solver did not save the expected result.mat file.");
            end

            labels = logical(result.data.isFeasible);
            if size(result.data.X, 1) ~= ...
                    settings.InitialCount + settings.SequentialBudget
                error("cTSEMO:DimensionStudy:WrongEvaluationCount", ...
                    "Expected %d observations but found %d.", ...
                    settings.InitialCount + settings.SequentialBudget, ...
                    size(result.data.X, 1));
            end
            exactLabels = logical(problem.feasible(result.data.X));
            if ~isequal(labels, exactLabels)
                error("cTSEMO:DimensionStudy:StoredLabelMismatch", ...
                    "Stored feasibility labels disagree with benchmark truth.");
            end

            trainUnit = normalizeToUnit( ...
                result.data.X, problem.lowerBound, problem.upperBound);
            [gpModel, gpFit] = ctsemo.fitClippedBinaryPof( ...
                trainUnit, labels, result.options);
            gpScore = predictGpInBatches( ...
                gpModel, probeUnit, settings.PredictionBatch);
            rfScore = predictRfProxy( ...
                trainUnit, labels, probeUnit, ...
                problem.dimension, rfSeed, settings);

            gpMetrics = calculateFieldMetrics(probeTruth, gpScore);
            rfMetrics = calculateFieldMetrics(probeTruth, rfScore);
            gpRow = makeMetricRow( ...
                runRow, "clipped_GP_mean", gpMetrics);
            rfRow = makeMetricRow( ...
                runRow, "offline_RF_proxy", rfMetrics);
            perRunMetrics = [gpRow; rfRow];

            runRow = summarizeSolverRun( ...
                runRow, result, gpFit, resultFile);
            runRow.Status = "completed";

            predictionFile = fullfile(runRoot, "probe_predictions.mat");
            atomicSave(predictionFile, ...
                struct("gpScore", gpScore, "rfScore", rfScore), "-v7");
            runRow.PredictionFile = string(predictionFile);
            perRunMetrics(1).PredictionFile = string(predictionFile);
            perRunMetrics(2).PredictionFile = string(predictionFile);
            recordSettingsSignature = settingsSignature;
            recordSourceSignature = sourceSignature;
            atomicSave(recordFile, struct( ...
                "runRow", runRow, ...
                "perRunMetrics", perRunMetrics, ...
                "recordSettingsSignature", recordSettingsSignature, ...
                "recordSourceSignature", recordSourceSignature), "-v7");
        catch exception
            runRow.Status = "failed";
            runRow.ErrorIdentifier = string(exception.identifier);
            runRow.ErrorMessage = string(exception.message);
            failure = struct( ...
                "identifier", string(exception.identifier), ...
                "message", string(exception.message), ...
                "report", string(getReport(exception, "extended")));
            atomicSave(fullfile(runRoot, "campaign_failure.mat"), ...
                struct("runRow", runRow, "failure", failure), "-v7");
            perRunMetrics = repmat(emptyMetricRow(), 0, 1);
            if ~settings.ContinueOnFailure
                runRows(end + 1, 1) = runRow; %#ok<AGROW>
                writeCheckpoint( ...
                    studyDirectory, runRows, metricRows, settings);
                rethrow(exception)
            end
        end

        runRows(end + 1, 1) = runRow; %#ok<AGROW>
        metricRows = [metricRows; perRunMetrics(:)]; %#ok<AGROW>
        writeCheckpoint(studyDirectory, runRows, metricRows, settings);
    end
end

runSummary = struct2table(runRows);
fieldMetrics = struct2table(metricRows);
aggregate = aggregateMetrics(fieldMetrics);
paired = pairedDimensionDifferences(fieldMetrics);
pairedAggregate = aggregatePairedDifferences(paired);
atomicWriteTable(runSummary, ...
    fullfile(studyDirectory, "run_summary.csv"));
atomicWriteTable(fieldMetrics, ...
    fullfile(studyDirectory, "field_metrics.csv"));
atomicWriteTable(aggregate, ...
    fullfile(studyDirectory, "aggregate_summary.csv"));
atomicWriteTable(paired, ...
    fullfile(studyDirectory, "paired_dimension_differences.csv"));
atomicWriteTable(pairedAggregate, ...
    fullfile(studyDirectory, "paired_aggregate_summary.csv"));
atomicSave(fullfile(studyDirectory, "study_results.mat"), struct( ...
    "runSummary", runSummary, ...
    "fieldMetrics", fieldMetrics, ...
    "aggregate", aggregate, ...
    "paired", paired, ...
    "pairedAggregate", pairedAggregate, ...
    "settings", settings, ...
    "manifest", manifest), "-v7");
end

function settings = resolveSettings(overrides)
scriptDirectory = fileparts(mfilename("fullpath"));
defaults = struct( ...
    "ProblemIds", [ ...
        "WELDEDBEAM", ...
        "CF1_D4", "CF1_D10", ...
        "C2DTLZ2_D4_R02", "C2DTLZ2_D6_R02", ...
        "MW7_D4", "MW7_D6"], ...
    "Replicates", 1:5, ...
    "InitialCount", 20, ...
    "SequentialBudget", 130, ...
    "ProbeCount", 262144, ...
    "PredictionBatch", 5000, ...
    "PrimaryCount", 1024, ...
    "ChallengerCount", 512, ...
    "ObjectiveFeatures", 256, ...
    "RfTrees", 120, ...
    "RfMinLeafSize", 3, ...
    "StudyId", "", ...
    "OutputRoot", string(fullfile(scriptDirectory, "results")), ...
    "ContinueOnFailure", true);
validateattributes(overrides, {'struct'}, {'scalar'}, ...
    mfilename, "settings");
names = fieldnames(overrides);
settings = defaults;
for index = 1:numel(names)
    name = names{index};
    if ~isfield(defaults, name)
        error("cTSEMO:DimensionStudy:UnknownSetting", ...
            "Unknown setting '%s'.", name);
    end
    settings.(name) = overrides.(name);
end

validateattributes(settings.ProblemIds, {'char', 'string'}, ...
    {'nonempty'}, mfilename, "settings.ProblemIds");
integerFields = [ ...
    "InitialCount", "SequentialBudget", "ProbeCount", ...
    "PredictionBatch", "PrimaryCount", "ChallengerCount", ...
    "ObjectiveFeatures", "RfTrees", "RfMinLeafSize"];
for index = 1:numel(integerFields)
    validateattributes(settings.(integerFields(index)), {'numeric'}, ...
        {'scalar', 'integer', 'positive', 'finite'}, ...
        mfilename, "settings." + integerFields(index));
end
validateattributes(settings.Replicates, {'numeric'}, ...
    {'vector', 'integer', 'positive', 'finite'}, ...
    mfilename, "settings.Replicates");
validateattributes(settings.OutputRoot, {'char', 'string'}, ...
    {'scalartext'}, mfilename, "settings.OutputRoot");
validateattributes(settings.StudyId, {'char', 'string'}, ...
    {'scalartext'}, mfilename, "settings.StudyId");
if ~(islogical(settings.ContinueOnFailure) && ...
        isscalar(settings.ContinueOnFailure))
    error("cTSEMO:DimensionStudy:InvalidContinueOnFailure", ...
        "ContinueOnFailure must be a logical scalar.");
end
settings.ProblemIds = string(settings.ProblemIds);
if numel(unique(settings.ProblemIds)) ~= numel(settings.ProblemIds)
    error("cTSEMO:DimensionStudy:DuplicateProblem", ...
        "ProblemIds must not contain duplicates.");
end
if numel(unique(settings.Replicates)) ~= numel(settings.Replicates)
    error("cTSEMO:DimensionStudy:DuplicateReplicate", ...
        "Replicates must not contain duplicates.");
end
settings.OutputRoot = string(settings.OutputRoot);
settings.StudyId = string(settings.StudyId);
if strlength(settings.StudyId) == 0
    settings.StudyId = "matched_dimension_pof_" + ...
        string(datetime("now", "Format", "yyyyMMdd_HHmmss_SSS"));
end
end

function manifest = makeManifest( ...
        settings, sourceSignature, settingsSignature)
manifest = struct( ...
    "StudyId", settings.StudyId, ...
    "CreatedAt", string(datetime("now", "TimeZone", "local")), ...
    "MatlabRelease", string(version("-release")), ...
    "SourceSha256", sourceSignature, ...
    "SettingsSha256", settingsSignature, ...
    "ProblemIds", string(settings.ProblemIds), ...
    "Replicates", double(settings.Replicates), ...
    "InitialCount", settings.InitialCount, ...
    "SequentialBudget", settings.SequentialBudget, ...
    "TotalEvaluations", ...
        settings.InitialCount + settings.SequentialBudget, ...
    "ProbeCount", settings.ProbeCount, ...
    "ProbeDesign", ...
        "Independent deterministic randomized LHS; corners excluded.", ...
    "InitialDesign", ...
        "Deterministic randomized LHS; corners excluded.", ...
    "PrimaryCandidateCount", settings.PrimaryCount, ...
    "ChallengerCandidateCount", settings.ChallengerCount, ...
    "ObjectiveFeatureCount", settings.ObjectiveFeatures, ...
    "ChallengerPolicy", ...
        "Complete primary and challenger pools are acquisition-scored.", ...
    "GpField", ...
        "Shipped clipped locally variable-length exact GP mean.", ...
    "RfField", sprintf( ...
        "Offline %d-tree bagged proxy; MinLeafSize=%d; " + ...
        "ceil(sqrt(D)) split variables.", ...
        settings.RfTrees, settings.RfMinLeafSize), ...
    "DecisionThreshold", 0.5, ...
    "ConfidentThresholds", [1 / 3, 2 / 3], ...
    "EvidenceClass", [ ...
        "Five-seed fixed-budget engineering screen by default. " ...
        "RF is trajectory-conditioned offline evidence."]);
end

function family = familyForProblem(problemId)
id = string(problemId);
if startsWith(id, "CF1")
    family = "CF1";
elseif startsWith(id, "C2DTLZ2")
    family = "C2DTLZ2_R02";
elseif startsWith(id, "MW7")
    family = "MW7";
elseif id == "WELDEDBEAM"
    family = "WELDEDBEAM";
else
    error("cTSEMO:DimensionStudy:UnknownFamily", ...
        "No study family is defined for '%s'.", id);
end
end

function seed = probeSeedForProblem(problemId)
switch familyForProblem(problemId)
    case "WELDEDBEAM"
        seed = 2026073101;
    case "CF1"
        seed = 2026073102;
    case "C2DTLZ2_R02"
        seed = 2026073104;
    case "MW7"
        seed = 2026073106;
    otherwise
        error("cTSEMO:DimensionStudy:MissingProbeSeed", ...
            "No probe seed is registered for '%s'.", problemId);
end
end

function seed = rfSeedForProblem(problemId, replicate)
switch familyForProblem(problemId)
    case "WELDEDBEAM"
        base = 2026073500;
    case "CF1"
        base = 2026073600;
    case "C2DTLZ2_R02"
        base = 2026073800;
    case "MW7"
        base = 2026074000;
    otherwise
        error("cTSEMO:DimensionStudy:MissingRfSeed", ...
            "No RF seed is registered for '%s'.", problemId);
end
seed = base + replicate;
end

function ensureCompatibleManifest(pathValue, manifest)
if isfile(pathValue)
    existing = jsondecode(fileread(pathValue));
    hasSignatures = isfield(existing, "SourceSha256") && ...
        isfield(existing, "SettingsSha256");
    signaturesMatch = hasSignatures && ...
        string(existing.SourceSha256) == ...
        string(manifest.SourceSha256) && ...
        string(existing.SettingsSha256) == ...
        string(manifest.SettingsSha256);
    if ~signaturesMatch
        error("cTSEMO:DimensionStudy:IncompatibleResume", ...
            ["The existing study manifest does not match the current " ...
            "settings and source. Use a new StudyId."]);
    end
    return
end
writeJson(pathValue, manifest);
end

function [probeX, probeUnit, truth] = loadOrCreateProbes( ...
        pathValue, problem, count, seed)
if isfile(pathValue)
    stored = load(pathValue, "probeX", "probeUnit", "truth", ...
        "problemId", "probeSeed");
    probeX = stored.probeX;
    probeUnit = stored.probeUnit;
    truth = logical(stored.truth);
    if string(stored.problemId) ~= string(problem.id) || ...
            double(stored.probeSeed) ~= double(seed) || ...
            size(probeX, 1) ~= count || ...
            size(probeX, 2) ~= problem.dimension
        error("cTSEMO:DimensionStudy:ProbeRecordMismatch", ...
            "Stored probe record does not match the requested study.");
    end
    expectedUnit = normalizeToUnit( ...
        probeX, problem.lowerBound, problem.upperBound);
    if ~isequal(size(probeUnit), size(expectedUnit)) || ...
            max(abs(probeUnit - expectedUnit), [], "all") > 100 * eps
        error("cTSEMO:DimensionStudy:ProbeNormalizationMismatch", ...
            "Stored normalized probes disagree with current bounds.");
    end
    exactTruth = logical(problem.feasible(probeX));
    if ~isequal(truth, exactTruth)
        error("cTSEMO:DimensionStudy:ProbeTruthMismatch", ...
            "Stored probe truth disagrees with the benchmark.");
    end
    return
end

[probeX, ~] = initialDesign( ...
    problem, count, seed, struct("IncludeCorners", false));
probeUnit = normalizeToUnit( ...
    probeX, problem.lowerBound, problem.upperBound);
truth = logical(problem.feasible(probeX));
problemId = string(problem.id);
probeSeed = seed;
atomicSave(pathValue, struct( ...
    "probeX", probeX, ...
    "probeUnit", probeUnit, ...
    "truth", truth, ...
    "problemId", problemId, ...
    "probeSeed", probeSeed), "-v7.3");
end

function [loaded, runRow, metricRows] = loadCompletedRecord( ...
        pathValue, settingsSignature, sourceSignature)
loaded = false;
runRow = emptyRunRow();
metricRows = repmat(emptyMetricRow(), 0, 1);
if ~isfile(pathValue)
    return
end
try
    record = load(pathValue, ...
        "runRow", "perRunMetrics", ...
        "recordSettingsSignature", "recordSourceSignature");
catch
    return
end
if ~isfield(record, "runRow") || ...
        string(record.runRow.Status) ~= "completed"
    return
end
if ~isfield(record, "perRunMetrics") || ...
        numel(record.perRunMetrics) ~= 2
    return
end
if ~isfield(record, "recordSettingsSignature") || ...
        ~isfield(record, "recordSourceSignature") || ...
        string(record.recordSettingsSignature) ~= settingsSignature || ...
        string(record.recordSourceSignature) ~= sourceSignature || ...
        ~isfile(record.runRow.ResultFile) || ...
        ~isfile(record.runRow.PredictionFile)
    return
end
runRow = record.runRow;
metricRows = record.perRunMetrics;
loaded = true;
end

function score = predictGpInBatches(model, query, batchSize)
score = zeros(size(query, 1), 1);
for first = 1:batchSize:size(query, 1)
    last = min(size(query, 1), first + batchSize - 1);
    score(first:last) = ...
        ctsemo.predictClippedBinaryPof(model, query(first:last, :));
end
end

function probability = predictRfProxy( ...
        xTrain, labels, xQuery, dimension, seed, settings)
previousRandomState = rng;
restoreRandomState = onCleanup(@() rng(previousRandomState));
rng(double(seed), "twister");
if numel(unique(labels)) < 2
    background = (nnz(labels) + 1) ./ (numel(labels) + 2);
    probability = repmat(background, size(xQuery, 1), 1);
    return
end
learner = templateTree( ...
    "MinLeafSize", settings.RfMinLeafSize, ...
    "NumVariablesToSample", max(1, ceil(sqrt(dimension))));
model = fitcensemble( ...
    xTrain, labels, ...
    "Method", "Bag", ...
    "NumLearningCycles", settings.RfTrees, ...
    "Learners", learner, ...
    "ClassNames", [false true]);
positiveColumn = find(model.ClassNames == true, 1);
probability = zeros(size(xQuery, 1), 1);
for first = 1:settings.PredictionBatch:size(xQuery, 1)
    last = min(size(xQuery, 1), ...
        first + settings.PredictionBatch - 1);
    [~, score] = predict(model, xQuery(first:last, :));
    probability(first:last) = score(:, positiveColumn);
end
probability = min(1, max(0, probability));
clear restoreRandomState
end

function metrics = calculateFieldMetrics(truth, score)
truth = logical(truth(:));
score = double(score(:));
if isempty(truth) || numel(score) ~= numel(truth)
    error("cTSEMO:DimensionStudy:MetricInputSize", ...
        "Truth and score must be equal-length nonempty vectors.");
end
if any(~isfinite(score))
    error("cTSEMO:DimensionStudy:NonfiniteScore", ...
        "Field scores must be finite.");
end
score = min(1, max(0, score));
predicted = score >= 0.5;
positive = truth;
negative = ~truth;
tp = nnz(predicted & positive);
fp = nnz(predicted & negative);
fn = nnz(~predicted & positive);
tn = nnz(~predicted & negative);
positiveCount = nnz(positive);
negativeCount = nnz(negative);

metrics = struct( ...
    "TruePositive", tp, ...
    "FalsePositive", fp, ...
    "FalseNegative", fn, ...
    "TrueNegative", tn, ...
    "ProbeFeasibleCount", positiveCount, ...
    "ProbeInfeasibleCount", negativeCount, ...
    "ProbeFeasibleRate", mean(positive), ...
    "PredictedFeasibleRate", mean(predicted), ...
    "AUC", rocAuc(truth, score), ...
    "AveragePrecision", averagePrecision(truth, score), ...
    "Brier", mean((score - double(truth)) .^ 2), ...
    "BalancedBrier", 0.5 .* ( ...
        conditionalMean((score - 1) .^ 2, positive) + ...
        conditionalMean(score .^ 2, negative)), ...
    "ECE10", expectedCalibrationError(truth, score, 10), ...
    "FalsePositiveRate", safeDivide(fp, negativeCount), ...
    "FalseNegativeRate", safeDivide(fn, positiveCount), ...
    "FalseDiscoveryRate", safeDivide(fp, tp + fp), ...
    "BalancedAccuracy", 0.5 .* ( ...
        safeDivide(tp, positiveCount) + ...
        safeDivide(tn, negativeCount)), ...
    "BalancedError", 0.5 .* ( ...
        safeDivide(fp, negativeCount) + ...
        safeDivide(fn, positiveCount)), ...
    "DomainError", mean(predicted ~= truth), ...
    "ConfidentFalsePositiveRate", ...
        safeDivide(nnz(score > 2 / 3 & negative), negativeCount), ...
    "ConfidentFalseNegativeRate", ...
        safeDivide(nnz(score < 1 / 3 & positive), positiveCount), ...
    "AmbiguousRate", mean(score > 1 / 3 & score < 2 / 3), ...
    "ZeroMass", mean(score == 0), ...
    "OneMass", mean(score == 1));
end

function value = safeDivide(numerator, denominator)
if denominator == 0
    value = NaN;
else
    value = numerator ./ denominator;
end
end

function value = conditionalMean(values, selected)
if any(selected)
    value = mean(values(selected));
else
    value = NaN;
end
end

function value = rocAuc(truth, score)
positiveCount = nnz(truth);
negativeCount = nnz(~truth);
if positiveCount == 0 || negativeCount == 0
    value = NaN;
    return
end
[sortedScore, order] = sort(score, "ascend");
ranks = (1:numel(score)).';
first = 1;
while first <= numel(sortedScore)
    last = first;
    while last < numel(sortedScore) && ...
            sortedScore(last + 1) == sortedScore(first)
        last = last + 1;
    end
    ranks(first:last) = 0.5 .* (first + last);
    first = last + 1;
end
unsortedRanks = zeros(size(ranks));
unsortedRanks(order) = ranks;
value = (sum(unsortedRanks(truth)) - ...
    positiveCount .* (positiveCount + 1) ./ 2) ./ ...
    (positiveCount .* negativeCount);
end

function value = averagePrecision(truth, score)
if ~any(truth)
    value = NaN;
    return
end
[sortedScore, order] = sort(score, "descend");
orderedTruth = truth(order);
truePositive = cumsum(orderedTruth);
groupEnd = [find(diff(sortedScore) ~= 0); numel(sortedScore)];
precision = truePositive(groupEnd) ./ groupEnd;
recall = truePositive(groupEnd) ./ nnz(truth);
value = sum(diff([0; recall]) .* precision);
end

function value = expectedCalibrationError(truth, score, binCount)
edges = linspace(0, 1, binCount + 1);
value = 0;
for binIndex = 1:binCount
    if binIndex < binCount
        inBin = score >= edges(binIndex) & ...
            score < edges(binIndex + 1);
    else
        inBin = score >= edges(binIndex) & ...
            score <= edges(binIndex + 1);
    end
    if any(inBin)
        value = value + mean(inBin) .* abs( ...
            mean(score(inBin)) - mean(truth(inBin)));
    end
end
end

function row = makeMetricRow(runRow, method, metrics)
row = emptyMetricRow();
row.ProblemId = runRow.ProblemId;
row.Family = runRow.Family;
row.Dimension = runRow.Dimension;
row.Replicate = runRow.Replicate;
row.Method = string(method);
row.ProbeSeed = runRow.ProbeSeed;
row.RfSeed = runRow.RfSeed;
row.ProbeCount = runRow.ProbeCount;
names = fieldnames(metrics);
for index = 1:numel(names)
    row.(names{index}) = metrics.(names{index});
end
end

function row = summarizeSolverRun(row, result, gpFit, resultFile)
labels = logical(result.data.isFeasible);
nInitial = result.data.nInitial;
sequentialLabels = labels((nInitial + 1):end);
sources = reshape(string({result.iterations.selectionSource}), [], 1);
row.TotalEvaluations = size(result.data.X, 1);
row.FinalFeasibleCount = nnz(labels);
row.SequentialFeasibleCount = nnz(sequentialLabels);
row.SequentialFeasibleRate = mean(sequentialLabels);
row.FirstFeasibleEvaluation = firstTrueIndex(labels);
row.FinalParetoCount = result.pareto.nPoints;
row.PrimarySelections = nnz(sources == "primary");
row.ChallengerSelections = nnz(sources == "challenger");
row.FallbackSelections = nnz(sources == "fallback");
row.WallTimeSeconds = result.meta.wallTimeSeconds;
row.MeanAcquisitionSeconds = mean(arrayfun( ...
    @(record) record.timing.acquisitionSeconds, result.iterations));
row.PofTrainingLengthMinimum = gpFit.trainingLengthMinimum;
row.PofTrainingLengthMaximum = gpFit.trainingLengthMaximum;
row.ResultDirectory = string(result.meta.outputDirectory);
row.ResultFile = string(resultFile);
end

function index = firstTrueIndex(values)
index = find(values, 1, "first");
if isempty(index)
    index = NaN;
end
end

function aggregate = aggregateMetrics(metrics)
if isempty(metrics)
    aggregate = table();
    return
end
problems = unique(metrics.ProblemId, "stable");
methods = unique(metrics.Method, "stable");
rows = repmat(emptyAggregateRow(), ...
    numel(problems) .* numel(methods), 1);
rowIndex = 0;
metricNames = [ ...
    "AUC", "AveragePrecision", "Brier", "BalancedBrier", ...
    "ECE10", "BalancedAccuracy", "BalancedError", ...
    "FalsePositiveRate", "FalseNegativeRate", ...
    "FalseDiscoveryRate", "DomainError", ...
    "ConfidentFalsePositiveRate", ...
    "ConfidentFalseNegativeRate", ...
    "PredictedFeasibleRate", "AmbiguousRate", ...
    "ZeroMass", "OneMass"];
for problemIndex = 1:numel(problems)
    for methodIndex = 1:numel(methods)
        selected = metrics.ProblemId == problems(problemIndex) & ...
            metrics.Method == methods(methodIndex);
        if ~any(selected)
            continue
        end
        block = metrics(selected, :);
        rowIndex = rowIndex + 1;
        rows(rowIndex).ProblemId = problems(problemIndex);
        rows(rowIndex).Family = block.Family(1);
        rows(rowIndex).Dimension = block.Dimension(1);
        rows(rowIndex).Method = methods(methodIndex);
        rows(rowIndex).Replicates = height(block);
        rows(rowIndex).ProbeFeasibleRate = ...
            mean(block.ProbeFeasibleRate, "omitnan");
        for metricIndex = 1:numel(metricNames)
            name = metricNames(metricIndex);
            rows(rowIndex).("Mean" + name) = ...
                mean(block.(name), "omitnan");
            rows(rowIndex).("Std" + name) = ...
                std(block.(name), "omitnan");
        end
    end
end
aggregate = struct2table(rows(1:rowIndex));
end

function paired = pairedDimensionDifferences(metrics)
if isempty(metrics)
    paired = table();
    return
end
pairs = struct( ...
    "Family", {"CF1", "C2DTLZ2_R02", "MW7"}, ...
    "LowDimension", {4, 4, 4}, ...
    "HighDimension", {10, 6, 6});
methods = unique(metrics.Method, "stable");
replicates = unique(metrics.Replicate, "stable");
rows = repmat(emptyPairedRow(), ...
    numel(pairs) .* numel(methods) .* numel(replicates), 1);
rowIndex = 0;
metricNames = [ ...
    "AUC", "AveragePrecision", "Brier", "BalancedBrier", "ECE10", ...
    "BalancedAccuracy", "BalancedError", ...
    "FalsePositiveRate", "FalseNegativeRate", ...
    "FalseDiscoveryRate", "DomainError", ...
    "ConfidentFalsePositiveRate", ...
    "ConfidentFalseNegativeRate", ...
    "PredictedFeasibleRate", "AmbiguousRate", ...
    "ZeroMass", "OneMass"];
for pairIndex = 1:numel(pairs)
    for methodIndex = 1:numel(methods)
        for replicateIndex = 1:numel(replicates)
            common = metrics.Family == pairs(pairIndex).Family & ...
                metrics.Method == methods(methodIndex) & ...
                metrics.Replicate == replicates(replicateIndex);
            low = metrics(common & ...
                metrics.Dimension == pairs(pairIndex).LowDimension, :);
            high = metrics(common & ...
                metrics.Dimension == pairs(pairIndex).HighDimension, :);
            if height(low) ~= 1 || height(high) ~= 1
                continue
            end
            rowIndex = rowIndex + 1;
            rows(rowIndex).Family = string(pairs(pairIndex).Family);
            rows(rowIndex).Method = methods(methodIndex);
            rows(rowIndex).Replicate = replicates(replicateIndex);
            rows(rowIndex).LowDimension = ...
                pairs(pairIndex).LowDimension;
            rows(rowIndex).HighDimension = ...
                pairs(pairIndex).HighDimension;
            rows(rowIndex).LowPrevalence = low.ProbeFeasibleRate;
            rows(rowIndex).HighPrevalence = high.ProbeFeasibleRate;
            for metricIndex = 1:numel(metricNames)
                name = metricNames(metricIndex);
                rows(rowIndex).("Low" + name) = low.(name);
                rows(rowIndex).("High" + name) = high.(name);
                rows(rowIndex).("Delta" + name) = ...
                    high.(name) - low.(name);
            end
        end
    end
end
paired = struct2table(rows(1:rowIndex));
end

function aggregate = aggregatePairedDifferences(paired)
if isempty(paired)
    aggregate = table();
    return
end
metricNames = [ ...
    "AUC", "AveragePrecision", "Brier", "BalancedBrier", "ECE10", ...
    "BalancedAccuracy", "BalancedError", ...
    "FalsePositiveRate", "FalseNegativeRate", ...
    "FalseDiscoveryRate", "DomainError", ...
    "ConfidentFalsePositiveRate", ...
    "ConfidentFalseNegativeRate", ...
    "PredictedFeasibleRate", "AmbiguousRate", ...
    "ZeroMass", "OneMass"];
families = unique(paired.Family, "stable");
methods = unique(paired.Method, "stable");
rows = repmat(emptyPairedAggregateRow(), ...
    numel(families) .* numel(methods) .* numel(metricNames), 1);
rowIndex = 0;
for familyIndex = 1:numel(families)
    for methodIndex = 1:numel(methods)
        block = paired( ...
            paired.Family == families(familyIndex) & ...
            paired.Method == methods(methodIndex), :);
        if isempty(block)
            continue
        end
        for metricIndex = 1:numel(metricNames)
            metric = metricNames(metricIndex);
            low = block.("Low" + metric);
            high = block.("High" + metric);
            delta = block.("Delta" + metric);
            valid = isfinite(low) & isfinite(high) & isfinite(delta);
            rowIndex = rowIndex + 1;
            rows(rowIndex).Family = families(familyIndex);
            rows(rowIndex).Method = methods(methodIndex);
            rows(rowIndex).Metric = metric;
            rows(rowIndex).LowDimension = block.LowDimension(1);
            rows(rowIndex).HighDimension = block.HighDimension(1);
            rows(rowIndex).ValidN = nnz(valid);
            rows(rowIndex).LowMedian = median(low(valid), "omitnan");
            rows(rowIndex).HighMedian = median(high(valid), "omitnan");
            rows(rowIndex).MedianDelta = median(delta(valid), "omitnan");
            rows(rowIndex).MeanDelta = mean(delta(valid), "omitnan");
            rows(rowIndex).StdDelta = std(delta(valid), "omitnan");
            rows(rowIndex).PositiveDeltaCount = nnz(delta(valid) > 0);
            rows(rowIndex).NegativeDeltaCount = nnz(delta(valid) < 0);
            rows(rowIndex).ZeroDeltaCount = nnz(delta(valid) == 0);
        end
    end
end
aggregate = struct2table(rows(1:rowIndex));
end

function writeCheckpoint(directory, runRows, metricRows, settings)
runSummary = struct2table(runRows);
fieldMetrics = struct2table(metricRows);
atomicWriteTable(runSummary, ...
    fullfile(directory, "run_summary_in_progress.csv"));
atomicWriteTable(fieldMetrics, ...
    fullfile(directory, "field_metrics_in_progress.csv"));
atomicSave(fullfile(directory, "study_checkpoint.mat"), struct( ...
    "runSummary", runSummary, ...
    "fieldMetrics", fieldMetrics, ...
    "settings", settings), "-v7");
end

function normalized = normalizeToUnit(X, lower, upper)
normalized = (double(X) - lower) ./ (upper - lower);
end

function createDirectory(pathValue)
if ~isfolder(pathValue)
    mkdir(pathValue);
end
end

function writeJson(pathValue, value)
textValue = jsonencode(value, "PrettyPrint", true);
temporary = string(tempname(fileparts(pathValue))) + ".json";
fileId = fopen(temporary, "w");
if fileId < 0
    error("cTSEMO:DimensionStudy:JsonOpenFailure", ...
        "Could not open a temporary JSON file for '%s'.", pathValue);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s\n", textValue);
clear cleanup
[success, message] = movefile(temporary, pathValue, "f");
if ~success
    error("cTSEMO:DimensionStudy:JsonCommitFailure", ...
        "Could not commit '%s': %s", pathValue, message);
end
end

function atomicWriteTable(value, pathValue)
temporary = string(tempname(fileparts(pathValue))) + ".csv";
writetable(value, temporary);
[success, message] = movefile(temporary, pathValue, "f");
if ~success
    error("cTSEMO:DimensionStudy:TableCommitFailure", ...
        "Could not commit '%s': %s", pathValue, message);
end
end

function atomicSave(pathValue, payload, version)
temporary = string(tempname(fileparts(pathValue))) + ".mat";
save(temporary, "-struct", "payload", version);
[success, message] = movefile(temporary, pathValue, "f");
if ~success
    error("cTSEMO:DimensionStudy:MatCommitFailure", ...
        "Could not commit '%s': %s", pathValue, message);
end
end

function value = sha256Text(textValue)
engine = java.security.MessageDigest.getInstance("SHA-256");
bytes = unicode2native(char(textValue), "UTF-8");
engine.update(bytes);
raw = typecast(engine.digest(), "uint8");
value = lower(string(reshape(dec2hex(raw, 2).', 1, [])));
end

function row = emptyRunRow()
row = struct( ...
    "ProblemId", "", ...
    "Family", "", ...
    "Dimension", NaN, ...
    "Replicate", NaN, ...
    "Status", "pending", ...
    "InitialSeed", NaN, ...
    "SolverSeed", NaN, ...
    "ProbeSeed", NaN, ...
    "RfSeed", NaN, ...
    "InitialCount", NaN, ...
    "SequentialBudget", NaN, ...
    "TotalEvaluations", NaN, ...
    "InitialFeasibleCount", NaN, ...
    "FinalFeasibleCount", NaN, ...
    "SequentialFeasibleCount", NaN, ...
    "SequentialFeasibleRate", NaN, ...
    "FirstFeasibleEvaluation", NaN, ...
    "FinalParetoCount", NaN, ...
    "PrimarySelections", NaN, ...
    "ChallengerSelections", NaN, ...
    "FallbackSelections", NaN, ...
    "ProbeCount", NaN, ...
    "ProbeFeasibleCount", NaN, ...
    "ProbeInfeasibleCount", NaN, ...
    "ProbeFeasibleRate", NaN, ...
    "PofTrainingLengthMinimum", NaN, ...
    "PofTrainingLengthMaximum", NaN, ...
    "WallTimeSeconds", NaN, ...
    "MeanAcquisitionSeconds", NaN, ...
    "ResultDirectory", "", ...
    "ResultFile", "", ...
    "PredictionFile", "", ...
    "ErrorIdentifier", "", ...
    "ErrorMessage", "");
end

function row = emptyMetricRow()
row = struct( ...
    "ProblemId", "", ...
    "Family", "", ...
    "Dimension", NaN, ...
    "Replicate", NaN, ...
    "Method", "", ...
    "ProbeSeed", NaN, ...
    "RfSeed", NaN, ...
    "ProbeCount", NaN, ...
    "ProbeFeasibleCount", NaN, ...
    "ProbeInfeasibleCount", NaN, ...
    "ProbeFeasibleRate", NaN, ...
    "PredictedFeasibleRate", NaN, ...
    "TruePositive", NaN, ...
    "FalsePositive", NaN, ...
    "FalseNegative", NaN, ...
    "TrueNegative", NaN, ...
    "AUC", NaN, ...
    "AveragePrecision", NaN, ...
    "Brier", NaN, ...
    "BalancedBrier", NaN, ...
    "ECE10", NaN, ...
    "FalsePositiveRate", NaN, ...
    "FalseNegativeRate", NaN, ...
    "FalseDiscoveryRate", NaN, ...
    "BalancedAccuracy", NaN, ...
    "BalancedError", NaN, ...
    "DomainError", NaN, ...
    "ConfidentFalsePositiveRate", NaN, ...
    "ConfidentFalseNegativeRate", NaN, ...
    "AmbiguousRate", NaN, ...
    "ZeroMass", NaN, ...
    "OneMass", NaN, ...
    "PredictionFile", "");
end

function row = emptyAggregateRow()
row = struct( ...
    "ProblemId", "", ...
    "Family", "", ...
    "Dimension", NaN, ...
    "Method", "", ...
    "Replicates", NaN, ...
    "ProbeFeasibleRate", NaN, ...
    "MeanAUC", NaN, "StdAUC", NaN, ...
    "MeanAveragePrecision", NaN, "StdAveragePrecision", NaN, ...
    "MeanBrier", NaN, "StdBrier", NaN, ...
    "MeanBalancedBrier", NaN, "StdBalancedBrier", NaN, ...
    "MeanECE10", NaN, "StdECE10", NaN, ...
    "MeanBalancedAccuracy", NaN, "StdBalancedAccuracy", NaN, ...
    "MeanBalancedError", NaN, "StdBalancedError", NaN, ...
    "MeanFalsePositiveRate", NaN, "StdFalsePositiveRate", NaN, ...
    "MeanFalseNegativeRate", NaN, "StdFalseNegativeRate", NaN, ...
    "MeanFalseDiscoveryRate", NaN, "StdFalseDiscoveryRate", NaN, ...
    "MeanDomainError", NaN, "StdDomainError", NaN, ...
    "MeanConfidentFalsePositiveRate", NaN, ...
    "StdConfidentFalsePositiveRate", NaN, ...
    "MeanConfidentFalseNegativeRate", NaN, ...
    "StdConfidentFalseNegativeRate", NaN, ...
    "MeanPredictedFeasibleRate", NaN, ...
    "StdPredictedFeasibleRate", NaN, ...
    "MeanAmbiguousRate", NaN, "StdAmbiguousRate", NaN, ...
    "MeanZeroMass", NaN, "StdZeroMass", NaN, ...
    "MeanOneMass", NaN, "StdOneMass", NaN);
end

function row = emptyPairedAggregateRow()
row = struct( ...
    "Family", "", ...
    "Method", "", ...
    "Metric", "", ...
    "LowDimension", NaN, ...
    "HighDimension", NaN, ...
    "ValidN", NaN, ...
    "LowMedian", NaN, ...
    "HighMedian", NaN, ...
    "MedianDelta", NaN, ...
    "MeanDelta", NaN, ...
    "StdDelta", NaN, ...
    "PositiveDeltaCount", NaN, ...
    "NegativeDeltaCount", NaN, ...
    "ZeroDeltaCount", NaN);
end

function row = emptyPairedRow()
row = struct( ...
    "Family", "", ...
    "Method", "", ...
    "Replicate", NaN, ...
    "LowDimension", NaN, ...
    "HighDimension", NaN, ...
    "LowPrevalence", NaN, ...
    "HighPrevalence", NaN, ...
    "LowAUC", NaN, "HighAUC", NaN, "DeltaAUC", NaN, ...
    "LowAveragePrecision", NaN, ...
    "HighAveragePrecision", NaN, ...
    "DeltaAveragePrecision", NaN, ...
    "LowBrier", NaN, "HighBrier", NaN, "DeltaBrier", NaN, ...
    "LowBalancedBrier", NaN, ...
    "HighBalancedBrier", NaN, ...
    "DeltaBalancedBrier", NaN, ...
    "LowECE10", NaN, "HighECE10", NaN, "DeltaECE10", NaN, ...
    "LowBalancedAccuracy", NaN, ...
    "HighBalancedAccuracy", NaN, ...
    "DeltaBalancedAccuracy", NaN, ...
    "LowBalancedError", NaN, ...
    "HighBalancedError", NaN, ...
    "DeltaBalancedError", NaN, ...
    "LowFalsePositiveRate", NaN, ...
    "HighFalsePositiveRate", NaN, ...
    "DeltaFalsePositiveRate", NaN, ...
    "LowFalseNegativeRate", NaN, ...
    "HighFalseNegativeRate", NaN, ...
    "DeltaFalseNegativeRate", NaN, ...
    "LowFalseDiscoveryRate", NaN, ...
    "HighFalseDiscoveryRate", NaN, ...
    "DeltaFalseDiscoveryRate", NaN, ...
    "LowDomainError", NaN, ...
    "HighDomainError", NaN, ...
    "DeltaDomainError", NaN, ...
    "LowConfidentFalsePositiveRate", NaN, ...
    "HighConfidentFalsePositiveRate", NaN, ...
    "DeltaConfidentFalsePositiveRate", NaN, ...
    "LowConfidentFalseNegativeRate", NaN, ...
    "HighConfidentFalseNegativeRate", NaN, ...
    "DeltaConfidentFalseNegativeRate", NaN, ...
    "LowPredictedFeasibleRate", NaN, ...
    "HighPredictedFeasibleRate", NaN, ...
    "DeltaPredictedFeasibleRate", NaN, ...
    "LowAmbiguousRate", NaN, ...
    "HighAmbiguousRate", NaN, ...
    "DeltaAmbiguousRate", NaN, ...
    "LowZeroMass", NaN, ...
    "HighZeroMass", NaN, ...
    "DeltaZeroMass", NaN, ...
    "LowOneMass", NaN, ...
    "HighOneMass", NaN, ...
    "DeltaOneMass", NaN);
end
