function artifacts = summarize_dimension_trend(studyDirectory)
%SUMMARIZE_DIMENSION_TREND Summarize matched PoF dimension evidence.
%   ARTIFACTS = SUMMARIZE_DIMENSION_TREND(STUDYDIRECTORY) reads
%   the completed field_metrics.csv and paired_aggregate_summary.csv in
%   STUDYDIRECTORY. It writes descriptive CSV summaries and a concise
%   Markdown report into the same directory.
%
%   The five paired seeds are summarized by medians and direction counts.
%   No hypothesis tests or statistical-significance claims are made.

arguments
    studyDirectory (1,1) string {mustBeFolder}
end

fieldFile = fullfile(studyDirectory, "field_metrics.csv");
pairedFile = fullfile(studyDirectory, ...
    "paired_aggregate_summary.csv");
if ~isfile(fieldFile) || ~isfile(pairedFile)
    error("cTSEMO:DimensionTrendSummary:MissingInput", ...
        ["Completed field_metrics.csv and " ...
        "paired_aggregate_summary.csv are required."]);
end

fieldMetrics = readtable(fieldFile, "TextType", "string");
pairedAggregate = readtable(pairedFile, "TextType", "string");
validateInputs(fieldMetrics, pairedAggregate);

problemMedians = summarizeProblemMedians(fieldMetrics);
pairedSummary = summarizePairedChanges(pairedAggregate);
spearmanSummary = summarizeRawSpearman(problemMedians);

problemFile = fullfile(studyDirectory, ...
    "dimension_trend_problem_method_medians.csv");
pairedSummaryFile = fullfile(studyDirectory, ...
    "dimension_trend_paired_summary.csv");
spearmanFile = fullfile(studyDirectory, ...
    "dimension_trend_spearman.csv");
markdownFile = fullfile(studyDirectory, ...
    "DIMENSION_TREND_SUMMARY.md");

writetable(problemMedians, problemFile);
writetable(pairedSummary, pairedSummaryFile);
writetable(spearmanSummary, spearmanFile);
writeMarkdown(markdownFile, fieldFile, pairedFile, ...
    problemMedians, pairedSummary, spearmanSummary);

artifacts = table( ...
    ["problem_method_medians"; "paired_summary"; ...
    "raw_spearman"; "markdown_report"], ...
    [problemFile; pairedSummaryFile; spearmanFile; markdownFile], ...
    VariableNames=["Artifact", "File"]);
end

function validateInputs(fieldMetrics, pairedAggregate)
requiredField = [ ...
    "ProblemId", "Family", "Dimension", "Replicate", "Method", ...
    "ProbeFeasibleRate", "PredictedFeasibleRate", ...
    "AUC", "AveragePrecision", "Brier", "BalancedBrier", ...
    "ECE10", "FalsePositiveRate", "FalseNegativeRate", ...
    "FalseDiscoveryRate", "BalancedAccuracy", "BalancedError", ...
    "DomainError", "AmbiguousRate", "ZeroMass"];
requiredPaired = [ ...
    "Family", "Method", "Metric", "LowDimension", ...
    "HighDimension", "ValidN", "LowMedian", "HighMedian", ...
    "MedianDelta", "PositiveDeltaCount", ...
    "NegativeDeltaCount", "ZeroDeltaCount"];
requireVariables(fieldMetrics, requiredField, "field_metrics.csv");
requireVariables(pairedAggregate, requiredPaired, ...
    "paired_aggregate_summary.csv");

if isempty(fieldMetrics) || isempty(pairedAggregate)
    error("cTSEMO:DimensionTrendSummary:EmptyInput", ...
        "Completed input tables must contain data.");
end

boundedNames = [ ...
    "ProbeFeasibleRate", "PredictedFeasibleRate", ...
    "AUC", "AveragePrecision", "Brier", "BalancedBrier", ...
    "ECE10", "FalsePositiveRate", "FalseNegativeRate", ...
    "BalancedAccuracy", "BalancedError", ...
    "DomainError", "AmbiguousRate", "ZeroMass"];
bounded = fieldMetrics{:, cellstr(boundedNames)};
if any(~isfinite(bounded), "all") || ...
        any(bounded < 0 | bounded > 1, "all")
    error("cTSEMO:DimensionTrendSummary:InvalidMetric", ...
        "All field metrics used by the summary must lie in [0,1].");
end
validFdr = ( ...
    isfinite(fieldMetrics.FalseDiscoveryRate) & ...
    fieldMetrics.FalseDiscoveryRate >= 0 & ...
    fieldMetrics.FalseDiscoveryRate <= 1) | ...
    isnan(fieldMetrics.FalseDiscoveryRate);
if ~all(validFdr)
    error("cTSEMO:DimensionTrendSummary:InvalidFDR", ...
        "FDR must lie in [0,1] when it is available.");
end

keys = unique(fieldMetrics(:, ...
    {'ProblemId', 'Method'}), "rows", "stable");
groupCounts = zeros(height(keys), 1);
for keyIndex = 1:height(keys)
    selected = ...
        fieldMetrics.ProblemId == keys.ProblemId(keyIndex) & ...
        fieldMetrics.Method == keys.Method(keyIndex);
    groupCounts(keyIndex) = nnz(selected);
end
expectedReplicates = 5;
if any(groupCounts ~= expectedReplicates)
    error("cTSEMO:DimensionTrendSummary:IncompleteFieldMetrics", ...
        "Each problem-method group must contain five completed seeds.");
end

selectedMetrics = pairedMetricNames();
selected = ismember(pairedAggregate.Metric, selectedMetrics);
completeMetrics = selectedMetrics( ...
    selectedMetrics ~= "FalseDiscoveryRate");
completeSelected = ismember(pairedAggregate.Metric, completeMetrics);
if ~any(selected) || ...
        any(pairedAggregate.ValidN(completeSelected) ~= expectedReplicates)
    error("cTSEMO:DimensionTrendSummary:IncompletePairedMetrics", ...
        "Each selected paired metric must contain five valid seeds.");
end
end

function requireVariables(value, required, fileName)
available = string(value.Properties.VariableNames);
missing = required(~ismember(required, available));
if ~isempty(missing)
    error("cTSEMO:DimensionTrendSummary:Schema", ...
        "%s is missing required variables: %s.", ...
        fileName, strjoin(missing, ", "));
end
end

function summary = summarizeProblemMedians(fieldMetrics)
keys = unique(fieldMetrics(:, ...
    {'ProblemId', 'Family', 'Dimension', 'Method'}), ...
    "rows", "stable");
rows = repmat(emptyProblemMedianRow(), height(keys), 1);
metricNames = problemMetricNames();

for keyIndex = 1:height(keys)
    selected = ...
        fieldMetrics.ProblemId == keys.ProblemId(keyIndex) & ...
        fieldMetrics.Method == keys.Method(keyIndex);
    block = fieldMetrics(selected, :);
    rows(keyIndex).ProblemId = keys.ProblemId(keyIndex);
    rows(keyIndex).Family = keys.Family(keyIndex);
    rows(keyIndex).Dimension = keys.Dimension(keyIndex);
    rows(keyIndex).Method = keys.Method(keyIndex);
    rows(keyIndex).ValidN = height(block);
    rows(keyIndex).EvidenceLabel = ...
        evidenceLabel(keys.Family(keyIndex), ...
        keys.ProblemId(keyIndex));
    for metricIndex = 1:numel(metricNames)
        metric = metricNames(metricIndex);
        rows(keyIndex).("Median" + metric) = ...
            median(block.(metric), "omitnan");
    end
end

summary = struct2table(rows);
summary = sortrows(summary, ...
    {'Method', 'Family', 'Dimension', 'ProblemId'});
end

function summary = summarizePairedChanges(pairedAggregate)
selectedMetrics = pairedMetricNames();
selected = ismember(pairedAggregate.Metric, selectedMetrics);
source = pairedAggregate(selected, :);

summary = source(:, { ...
    'Family', 'Method', 'Metric', 'LowDimension', ...
    'HighDimension', 'ValidN', 'LowMedian', 'HighMedian', ...
    'MedianDelta', 'PositiveDeltaCount', ...
    'NegativeDeltaCount', 'ZeroDeltaCount'});
summary = renamevars(summary, "MedianDelta", ...
    "MedianHighMinusLow");

labels = strings(height(summary), 1);
directions = strings(height(summary), 1);
for rowIndex = 1:height(summary)
    labels(rowIndex) = evidenceLabel( ...
        summary.Family(rowIndex), "");
    directions(rowIndex) = describeDirection( ...
        summary.Metric(rowIndex), ...
        summary.MedianHighMinusLow(rowIndex));
end
summary = addvars(summary, labels, directions, ...
    After="Family", ...
    NewVariableNames=["EvidenceLabel", "MedianDirection"]);
summary = sortrows(summary, {'Method', 'Family', 'Metric'});
end

function summary = summarizeRawSpearman(problemMedians)
methods = unique(problemMedians.Method, "stable");
metricNames = spearmanMetricNames();
scopeNames = ["all_including_WB", "paired_families_excluding_WB"];
maximumRows = numel(methods)*numel(metricNames)*numel(scopeNames);
rows = repmat(emptySpearmanRow(), maximumRows, 1);
rowIndex = 0;

for methodIndex = 1:numel(methods)
    methodRows = problemMedians( ...
        problemMedians.Method == methods(methodIndex), :);
    for scopeIndex = 1:numel(scopeNames)
        block = methodRows;
        if scopeNames(scopeIndex) == ...
                "paired_families_excluding_WB"
            block = block(block.ProblemId ~= "WELDEDBEAM", :);
        end
        for metricIndex = 1:numel(metricNames)
            metric = metricNames(metricIndex);
            values = block.("Median" + metric);
            valid = isfinite(block.Dimension) & isfinite(values);
            rowIndex = rowIndex + 1;
            rows(rowIndex).Scope = scopeNames(scopeIndex);
            rows(rowIndex).Method = methods(methodIndex);
            rows(rowIndex).Metric = metric;
            rows(rowIndex).ProblemCount = nnz(valid);
            rows(rowIndex).SpearmanRho = spearmanRho( ...
                block.Dimension(valid), values(valid));
            rows(rowIndex).Interpretation = ...
                "descriptive_raw_no_significance_test";
        end
    end
end

summary = struct2table(rows(1:rowIndex));
summary = sortrows(summary, {'Method', 'Scope', 'Metric'});
end

function rho = spearmanRho(x, y)
x = x(:);
y = y(:);
if numel(x) < 3 || numel(y) ~= numel(x)
    rho = NaN;
    return
end

xRank = averageRanks(x);
yRank = averageRanks(y);
xCentered = xRank - mean(xRank);
yCentered = yRank - mean(yRank);
denominator = sqrt(sum(xCentered.^2)*sum(yCentered.^2));
if denominator == 0
    rho = NaN;
else
    rho = sum(xCentered.*yCentered)/denominator;
end
end

function ranks = averageRanks(values)
[sortedValues, order] = sort(values);
ranks = zeros(size(values));
first = 1;
while first <= numel(values)
    last = first;
    while last < numel(values) && ...
            sortedValues(last + 1) == sortedValues(first)
        last = last + 1;
    end
    ranks(order(first:last)) = 0.5*(first + last);
    first = last + 1;
end
end

function writeMarkdown(fileName, fieldFile, pairedFile, ...
        problemMedians, pairedSummary, spearmanSummary)
fileId = fopen(fileName, "w", "n", "UTF-8");
if fileId < 0
    error("cTSEMO:DimensionTrendSummary:FileOpen", ...
        "Could not open %s for writing.", fileName);
end
cleanup = onCleanup(@() fclose(fileId));

fprintf(fileId, "# Dimension-matched PoF trend summary\n\n");
fprintf(fileId, "## Scope and evidence labels\n\n");
fprintf(fileId, ...
    "This report is a descriptive summary of five paired seeds. " + ...
    "**No hypothesis tests, p-values, or statistical-significance " + ...
    "claims are made at n=5.**\n\n");
fprintf(fileId, ...
    "- **CF1 is the cleanest dimension contrast** in this campaign. " + ...
    "Its D4-D10 comparison should nevertheless be interpreted as " + ...
    "descriptive rather than causal proof.\n");
fprintf(fileId, ...
    "- **C2-DTLZ2-R02 and MW7 are prevalence-confounded.** " + ...
    "Their high-low metric changes must be read together with the " + ...
    "probe feasible rates.\n");
fprintf(fileId, ...
    "- **Welded beam is an unpaired D4 reference.** It enters only " + ...
    "the all-problem raw Spearman sensitivity; the second sensitivity " + ...
    "excludes it.\n\n");
fprintf(fileId, "Sources: `%s` and `%s`.\n\n", ...
    fileNameOnly(fieldFile), fileNameOnly(pairedFile));

fprintf(fileId, "## Median diagnostics by problem and method\n\n");
fprintf(fileId, ...
    "| Problem | D | Method | n | Feasible rate | AUC | FPR | FNR | Balanced error | Balanced Brier | Zero mass |\n");
fprintf(fileId, ...
    "|---|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|\n");
for rowIndex = 1:height(problemMedians)
    row = problemMedians(rowIndex, :);
    fprintf(fileId, ...
        "| %s | %d | %s | %d | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f |\n", ...
        row.ProblemId, row.Dimension, row.Method, row.ValidN, ...
        row.MedianProbeFeasibleRate, row.MedianAUC, ...
        row.MedianFalsePositiveRate, ...
        row.MedianFalseNegativeRate, row.MedianBalancedError, ...
        row.MedianBalancedBrier, row.MedianZeroMass);
end

fprintf(fileId, "\n## Paired high-minus-low dimension summaries\n\n");
fprintf(fileId, ...
    "The delta is the high-dimensional value minus the " + ...
    "low-dimensional value for the same family and seed.\n\n");
fprintf(fileId, ...
    "| Family | Method | Metric | D low-high | Median low | Median high | Median delta | + / - / 0 seeds | Direction |\n");
fprintf(fileId, ...
    "|---|---|---|---|---:|---:|---:|---:|---|\n");
for rowIndex = 1:height(pairedSummary)
    row = pairedSummary(rowIndex, :);
    fprintf(fileId, ...
        "| %s | %s | %s | %d-%d | %.4f | %.4f | %+.4f | %d / %d / %d | %s |\n", ...
        row.Family, row.Method, row.Metric, ...
        row.LowDimension, row.HighDimension, ...
        row.LowMedian, row.HighMedian, ...
        row.MedianHighMinusLow, row.PositiveDeltaCount, ...
        row.NegativeDeltaCount, row.ZeroDeltaCount, ...
        row.MedianDirection);
end

fprintf(fileId, "\n## Raw dimension correlations\n\n");
fprintf(fileId, ...
    "These Spearman correlations use problem-method medians. They are " + ...
    "descriptive sensitivities, not adjusted dimension effects. " + ...
    "Problem family, feasible prevalence, and dimension remain " + ...
    "partly confounded.\n\n");
fprintf(fileId, ...
    "| Scope | Method | Metric | Problems | Spearman rho |\n");
fprintf(fileId, "|---|---|---|---:|---:|\n");
for rowIndex = 1:height(spearmanSummary)
    row = spearmanSummary(rowIndex, :);
    fprintf(fileId, "| %s | %s | %s | %d | %.4f |\n", ...
        row.Scope, row.Method, row.Metric, ...
        row.ProblemCount, row.SpearmanRho);
end

fprintf(fileId, "\n## Interpretation limits\n\n");
fprintf(fileId, ...
    "- FPR, FNR, balanced error, AUC, and balanced Brier should be " + ...
    "considered together; domain error and FDR are prevalence-sensitive.\n");
fprintf(fileId, ...
    "- Direction counts show seed consistency but do not establish " + ...
    "statistical significance with five pairs.\n");
fprintf(fileId, ...
    "- A general dimension claim would require additional matched " + ...
    "dimension levels or substantially more independent benchmark " + ...
    "families.\n");

clear cleanup
end

function name = fileNameOnly(fileName)
[~, base, extension] = fileparts(fileName);
name = base + extension;
end

function label = evidenceLabel(family, problemId)
if family == "CF1"
    label = "cleanest_dimension_contrast";
elseif family == "C2DTLZ2_R02" || family == "MW7"
    label = "prevalence_confounded";
elseif problemId == "WELDEDBEAM"
    label = "unpaired_D4_reference";
else
    label = "descriptive_other";
end
end

function label = describeDirection(metric, delta)
if delta == 0
    label = "no_median_change";
    return
end

higherIsBetter = ismember(metric, ...
    ["AUC", "AveragePrecision", "BalancedAccuracy"]);
if delta > 0 && higherIsBetter
    label = "higher_dimension_better_metric";
elseif delta < 0 && higherIsBetter
    label = "higher_dimension_worse_metric";
elseif delta > 0
    label = "higher_dimension_higher_error_or_mass";
else
    label = "higher_dimension_lower_error_or_mass";
end
end

function names = problemMetricNames()
names = [ ...
    "ProbeFeasibleRate", "PredictedFeasibleRate", ...
    "AUC", "AveragePrecision", "Brier", "BalancedBrier", ...
    "ECE10", "FalsePositiveRate", "FalseNegativeRate", ...
    "FalseDiscoveryRate", "BalancedAccuracy", "BalancedError", ...
    "DomainError", "AmbiguousRate", "ZeroMass"];
end

function names = pairedMetricNames()
names = [ ...
    "AUC", "AveragePrecision", "BalancedBrier", "ECE10", ...
    "FalsePositiveRate", "FalseNegativeRate", ...
    "FalseDiscoveryRate", "BalancedError", "DomainError", ...
    "ZeroMass"];
end

function names = spearmanMetricNames()
names = [ ...
    "ProbeFeasibleRate", "AUC", "AveragePrecision", ...
    "BalancedBrier", "ECE10", "FalsePositiveRate", ...
    "FalseNegativeRate", "FalseDiscoveryRate", ...
    "BalancedError", "DomainError", "ZeroMass"];
end

function row = emptyProblemMedianRow()
row = struct( ...
    "ProblemId", "", "Family", "", "Dimension", NaN, ...
    "Method", "", "ValidN", NaN, "EvidenceLabel", "", ...
    "MedianProbeFeasibleRate", NaN, ...
    "MedianPredictedFeasibleRate", NaN, ...
    "MedianAUC", NaN, "MedianAveragePrecision", NaN, ...
    "MedianBrier", NaN, "MedianBalancedBrier", NaN, ...
    "MedianECE10", NaN, "MedianFalsePositiveRate", NaN, ...
    "MedianFalseNegativeRate", NaN, ...
    "MedianFalseDiscoveryRate", NaN, ...
    "MedianBalancedAccuracy", NaN, ...
    "MedianBalancedError", NaN, "MedianDomainError", NaN, ...
    "MedianAmbiguousRate", NaN, "MedianZeroMass", NaN);
end

function row = emptySpearmanRow()
row = struct( ...
    "Scope", "", "Method", "", "Metric", "", ...
    "ProblemCount", NaN, "SpearmanRho", NaN, ...
    "Interpretation", "");
end
