function checks = ...
        validate_matched_dimension_pof_study(studyDirectory)
%VALIDATE_MATCHED_DIMENSION_POF_STUDY Audit campaign artifacts.

arguments
    studyDirectory (1,1) string
end

scriptDirectory = fileparts(mfilename("fullpath"));
repositoryRoot = fileparts(fileparts(scriptDirectory));
releaseRoot = fullfile(repositoryRoot, "src");
addpath(releaseRoot, fullfile(releaseRoot, "benchmarks"));

runs = readtable( ...
    fullfile(studyDirectory, "run_summary.csv"), ...
    "TextType", "string");
metrics = readtable( ...
    fullfile(studyDirectory, "field_metrics.csv"), ...
    "TextType", "string");
manifest = jsondecode(fileread( ...
    fullfile(studyDirectory, "study_manifest.json")));

rows = repmat(emptyCheck(), 0, 1);
expectedRuns = numel(manifest.ProblemIds) .* ...
    numel(manifest.Replicates);
rows(end + 1) = makeCheck( ...
    "expected run count", height(runs) == expectedRuns, ...
    sprintf("%d observed; %d expected", height(runs), expectedRuns));
rows(end + 1) = makeCheck( ...
    "all runs completed", all(runs.Status == "completed"), ...
    sprintf("%d failed or incomplete", nnz(runs.Status ~= "completed")));
rows(end + 1) = makeCheck( ...
    "two field methods per run", ...
    height(metrics) == 2 .* expectedRuns, ...
    sprintf("%d metric rows; %d expected", ...
    height(metrics), 2 .* expectedRuns));
rows(end + 1) = makeCheck( ...
    "evaluation count", ...
    all(runs.TotalEvaluations == manifest.TotalEvaluations), ...
    sprintf("expected %d per trajectory", manifest.TotalEvaluations));
rows(end + 1) = makeCheck( ...
    "unique run keys", ...
    height(unique(runs(:, ...
    {'ProblemId', 'Replicate'}), "rows")) == height(runs), ...
    "one trajectory per problem and replicate");
rows(end + 1) = makeCheck( ...
    "unique metric keys", ...
    height(unique(metrics(:, ...
    {'ProblemId', 'Replicate', 'Method'}), "rows")) == ...
    height(metrics), ...
    "one field record per problem, replicate, and method");

countSum = metrics.TruePositive + metrics.FalsePositive + ...
    metrics.FalseNegative + metrics.TrueNegative;
rows(end + 1) = makeCheck( ...
    "confusion count total", all(countSum == metrics.ProbeCount), ...
    "TP+FP+FN+TN equals the probe count");
rows(end + 1) = makeCheck( ...
    "class count total", ...
    all(metrics.ProbeFeasibleCount + ...
    metrics.ProbeInfeasibleCount == metrics.ProbeCount), ...
    "feasible plus infeasible equals the probe count");
rows(end + 1) = makeCheck( ...
    "positive count identity", ...
    all(metrics.TruePositive + metrics.FalseNegative == ...
    metrics.ProbeFeasibleCount), ...
    "TP+FN equals the feasible probe count");
rows(end + 1) = makeCheck( ...
    "negative count identity", ...
    all(metrics.TrueNegative + metrics.FalsePositive == ...
    metrics.ProbeInfeasibleCount), ...
    "TN+FP equals the infeasible probe count");

tolerance = 5e-13;
calculatedFpr = metrics.FalsePositive ./ ...
    metrics.ProbeInfeasibleCount;
calculatedFnr = metrics.FalseNegative ./ ...
    metrics.ProbeFeasibleCount;
calculatedDomainError = ...
    (metrics.FalsePositive + metrics.FalseNegative) ./ ...
    metrics.ProbeCount;
calculatedBalancedAccuracy = 0.5 .* ( ...
    metrics.TruePositive ./ metrics.ProbeFeasibleCount + ...
    metrics.TrueNegative ./ metrics.ProbeInfeasibleCount);
rows(end + 1) = makeCheck( ...
    "FPR calculation", ...
    max(abs(calculatedFpr - metrics.FalsePositiveRate)) < tolerance, ...
    "recomputed from confusion counts");
rows(end + 1) = makeCheck( ...
    "FNR calculation", ...
    max(abs(calculatedFnr - metrics.FalseNegativeRate)) < tolerance, ...
    "recomputed from confusion counts");
rows(end + 1) = makeCheck( ...
    "domain error calculation", ...
    max(abs(calculatedDomainError - metrics.DomainError)) < tolerance, ...
    "recomputed from confusion counts");
rows(end + 1) = makeCheck( ...
    "balanced accuracy calculation", ...
    max(abs(calculatedBalancedAccuracy - ...
    metrics.BalancedAccuracy)) < tolerance, ...
    "recomputed from confusion counts");
rows(end + 1) = makeCheck( ...
    "balanced error complement", ...
    max(abs(metrics.BalancedError - ...
    (1 - metrics.BalancedAccuracy))) < tolerance, ...
    "balanced error equals one minus balanced accuracy");
rows(end + 1) = makeCheck( ...
    "prevalence calculation", ...
    max(abs(metrics.ProbeFeasibleRate - ...
    metrics.ProbeFeasibleCount ./ metrics.ProbeCount)) < tolerance, ...
    "recomputed from class counts");

boundedNames = [ ...
    "ProbeFeasibleRate", "PredictedFeasibleRate", ...
    "AUC", "AveragePrecision", "Brier", "BalancedBrier", ...
    "ECE10", "FalsePositiveRate", "FalseNegativeRate", ...
    "BalancedAccuracy", "BalancedError", ...
    "DomainError", "ConfidentFalsePositiveRate", ...
    "ConfidentFalseNegativeRate", "AmbiguousRate", ...
    "ZeroMass", "OneMass"];
bounded = metrics{:, cellstr(boundedNames)};
rows(end + 1) = makeCheck( ...
    "metric bounds", ...
    all(isfinite(bounded), "all") && ...
    all(bounded >= 0 & bounded <= 1, "all"), ...
    "all reported field metrics are finite and in [0,1]");
predictedPositiveCount = ...
    metrics.TruePositive + metrics.FalsePositive;
validFdr = ( ...
    isfinite(metrics.FalseDiscoveryRate) & ...
    metrics.FalseDiscoveryRate >= 0 & ...
    metrics.FalseDiscoveryRate <= 1) | ( ...
    isnan(metrics.FalseDiscoveryRate) & ...
    predictedPositiveCount == 0);
rows(end + 1) = makeCheck( ...
    "FDR availability", all(validFdr), ...
    "FDR is NaN only when no probe is predicted feasible");

filesExist = true;
labelsAgree = true;
anchorValuesAgree = true;
predictionBounds = true;
predictionCount = true;
probeRecordsAgree = true;
problemIds = unique(runs.ProblemId, "stable");
for problemIndex = 1:numel(problemIds)
    selectedRuns = runs(runs.ProblemId == problemIds(problemIndex), :);
    if numel(unique(selectedRuns.ProbeSeed)) ~= 1 || ...
            numel(unique(selectedRuns.ProbeCount)) ~= 1
        probeRecordsAgree = false;
    end
    probeFile = fullfile(studyDirectory, "probes", ...
        problemIds(problemIndex) + "_volume_probes.mat");
    filesExist = filesExist && isfile(probeFile);
    if isfile(probeFile)
        probeRecord = load(probeFile, "probeX", "truth");
        problem = getBenchmarkProblem(problemIds(problemIndex));
        probeRecordsAgree = probeRecordsAgree && ...
            isequal(logical(probeRecord.truth), ...
            logical(problem.feasible(probeRecord.probeX)));
    end
end

for runIndex = 1:height(runs)
    filesExist = filesExist && ...
        isfile(runs.ResultFile(runIndex)) && ...
        isfile(runs.PredictionFile(runIndex));
    if ~filesExist
        continue
    end
    problem = getBenchmarkProblem(runs.ProblemId(runIndex));
    resultRecord = load(runs.ResultFile(runIndex), "result");
    result = resultRecord.result;
    exactLabels = logical(problem.feasible(result.data.X));
    labelsAgree = labelsAgree && ...
        isequal(exactLabels, logical(result.data.isFeasible));
    trainUnit = normalizeToUnit( ...
        result.data.X, problem.lowerBound, problem.upperBound);
    model = ctsemo.fitClippedBinaryPof( ...
        trainUnit, logical(result.data.isFeasible), result.options);
    anchorScore = ctsemo.predictClippedBinaryPof(model, trainUnit);
    anchorValuesAgree = anchorValuesAgree && ...
        max(abs(anchorScore - ...
        double(result.data.isFeasible))) <= 10 * eps;
    predictionRecord = load( ...
        runs.PredictionFile(runIndex), "gpScore", "rfScore");
    predictionBounds = predictionBounds && ...
        all(isfinite(predictionRecord.gpScore)) && ...
        all(isfinite(predictionRecord.rfScore)) && ...
        all(predictionRecord.gpScore >= 0 & ...
        predictionRecord.gpScore <= 1) && ...
        all(predictionRecord.rfScore >= 0 & ...
        predictionRecord.rfScore <= 1);
    predictionCount = predictionCount && ...
        numel(predictionRecord.gpScore) == runs.ProbeCount(runIndex) && ...
        numel(predictionRecord.rfScore) == runs.ProbeCount(runIndex);
end

rows(end + 1) = makeCheck( ...
    "artifact files exist", filesExist, ...
    "every result, prediction, and probe file is present");
rows(end + 1) = makeCheck( ...
    "stored labels match benchmark", labelsAgree, ...
    "recomputed at all 150 observations in every trajectory");
rows(end + 1) = makeCheck( ...
    "GP anchor interpolation", anchorValuesAgree, ...
    "clipped GP score equals every observed binary label");
rows(end + 1) = makeCheck( ...
    "prediction bounds", predictionBounds, ...
    "all stored GP and RF scores are finite and in [0,1]");
rows(end + 1) = makeCheck( ...
    "prediction counts", predictionCount, ...
    "each stored prediction vector matches its probe count");
rows(end + 1) = makeCheck( ...
    "probe truth consistency", probeRecordsAgree, ...
    "one shared exact probe record per problem across all runs");

checks = struct2table(rows);
writetable(checks, ...
    fullfile(studyDirectory, "validation_checks.csv"));
passed = nnz(checks.Passed);
summaryText = sprintf( ...
    "Matched dimension PoF study validation\n" + ...
    "Passed: %d/%d checks\n" + ...
    "Failed: %d\n" + ...
    "Validation status: %s\n", ...
    passed, height(checks), height(checks) - passed, ...
    string(all(checks.Passed)));
writeText(fullfile(studyDirectory, "VALIDATION_SUMMARY.txt"), ...
    summaryText);
if ~all(checks.Passed)
    error("cTSEMO:DimensionStudyValidation:Failed", ...
        "%d of %d validation checks failed.", ...
        height(checks) - passed, height(checks));
end
end

function normalized = normalizeToUnit(X, lower, upper)
normalized = (double(X) - lower) ./ (upper - lower);
end

function row = makeCheck(name, passed, details)
row = emptyCheck();
row.Check = string(name);
row.Passed = logical(passed);
row.Details = string(details);
end

function row = emptyCheck()
row = struct("Check", "", "Passed", false, "Details", "");
end

function writeText(pathValue, textValue)
fileId = fopen(pathValue, "w");
if fileId < 0
    error("cTSEMO:DimensionStudyValidation:WriteFailure", ...
        "Could not open '%s' for writing.", pathValue);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s", textValue);
clear cleanup
end
