% Matched comparison of the current GA-primary and archived finite-pool runs.
% The old optimizer is not rerun. All quality metrics are recomputed from
% evaluated feasible observations under one pooled normalization and fixed
% reference point per problem.

artifactRoot = string(fileparts(mfilename("fullpath")));
repo = string(fileparts(fileparts(fileparts(artifactRoot))));
newRoot = fullfile(repo, "manuscript", "artifacts", ...
    "ga_primary_dimension");
outputRoot = fullfile(repo, "generated", "finite_primary_ablation");
if ~isfolder(outputRoot)
    mkdir(outputRoot);
end
normalizationFile = fullfile(artifactRoot, ...
    "comparison_normalization_reference.csv");
normalizationReference = readtable(normalizationFile, "TextType", "string");
addpath(fullfile(repo, "src"));
addpath(fullfile(repo, "src", "benchmarks"));

oldSummary = readtable(fullfile(artifactRoot, ...
    "finite_primary_run_summary.csv"), ...
    "TextType", "string");
oldEvaluations = readtable(fullfile(artifactRoot, ...
    "finite_primary_evaluations.csv"), ...
    "TextType", "string", VariableNamingRule="preserve");
oldCoreOptions = jsondecode(fileread(fullfile(artifactRoot, ...
    "finite_primary_core_options.json")));
newSummary = readtable(fullfile(newRoot, "run_summary.csv"), ...
    "TextType", "string");
problemIds = ["WELDEDBEAM"; "CF1_D4"; "CF1_D10"; ...
    "C2DTLZ2_D4_R02"; "C2DTLZ2_D6_R02"; "MW7_D4"; "MW7_D6"];
referencePoint = [1.1, 1.1];
comparisonTolerance = 1e-10;

assert(height(oldSummary) == 35 && height(newSummary) == 35, ...
    "Expected 35 archived and 35 current trajectories.");
assert(all(oldSummary.Status == "completed") && ...
    all(newSummary.Status == "completed"), ...
    "Every trajectory must be completed before comparison.");

pairedRows = repmat(emptyPairedRow(), 0, 1);
problemLower = cell(numel(problemIds), 1);
problemScale = cell(numel(problemIds), 1);
normalizationRows = repmat(struct( ...
    "ProblemId", "", "Lower1", NaN, "Lower2", NaN, ...
    "Scale1", NaN, "Scale2", NaN, ...
    "Reference1", referencePoint(1), ...
    "Reference2", referencePoint(2)), numel(problemIds), 1);

for problemIndex = 1:numel(problemIds)
    problemId = problemIds(problemIndex);
    oldRows = sortrows(oldSummary(oldSummary.ProblemId == problemId, :), ...
        "Replicate");
    newRows = sortrows(newSummary(newSummary.ProblemId == problemId, :), ...
        "Replicate");
    assert(height(oldRows) == 5 && height(newRows) == 5, ...
        "Expected five matched replicates for %s.", problemId);
    assert(isequal(oldRows.Replicate, newRows.Replicate) && ...
        isequal(oldRows.InitialSeed, newRows.InitialSeed) && ...
        isequal(oldRows.SolverSeed, newRows.SolverSeed), ...
        "Replicate or seed pairing differs for %s.", problemId);

    pooledFeasibleParts = cell(10, 1);
    for replicateIndex = 1:5
        newFile = resolveResultFile( ...
            newRows.ResultFile(replicateIndex), newRoot);
        newLoaded = load(newFile, "result");
        oldResult = compactFiniteResult(oldEvaluations, ...
            oldRows(replicateIndex, :), oldCoreOptions);
        newResult = newLoaded.result;
        pooledFeasibleParts{2 .* replicateIndex - 1} = ...
            oldResult.data.Y(logical(oldResult.data.isFeasible), :);
        pooledFeasibleParts{2 .* replicateIndex} = ...
            newResult.data.Y(logical(newResult.data.isFeasible), :);
    end
    pooledFeasible = vertcat(pooledFeasibleParts{:});
    assert(~isempty(pooledFeasible), ...
        "No feasible objective observations exist for %s.", problemId);
    storedReference = normalizationReference( ...
        normalizationReference.ProblemId == problemId, :);
    assert(height(storedReference) == 1, ...
        "Normalization reference is missing or duplicated for %s.", problemId);
    lower = [storedReference.Lower1, storedReference.Lower2];
    scale = [storedReference.Scale1, storedReference.Scale2];
    problemLower{problemIndex} = lower;
    problemScale{problemIndex} = scale;
    normalizationRows(problemIndex, 1) = struct( ...
        "ProblemId", problemId, ...
        "Lower1", lower(1), "Lower2", lower(2), ...
        "Scale1", scale(1), "Scale2", scale(2), ...
        "Reference1", referencePoint(1), ...
        "Reference2", referencePoint(2));

    for replicateIndex = 1:5
        newFile = resolveResultFile( ...
            newRows.ResultFile(replicateIndex), newRoot);
        newLoaded = load(newFile, "result");
        oldResult = compactFiniteResult(oldEvaluations, ...
            oldRows(replicateIndex, :), oldCoreOptions);
        newResult = newLoaded.result;

        nInitial = double(oldResult.data.nInitial);
        assert(double(newResult.data.nInitial) == nInitial, ...
            "Initial count differs for %s replicate %d.", ...
            problemId, replicateIndex);
        assert(size(oldResult.data.Y, 1) == size(newResult.data.Y, 1), ...
            "Evaluation count differs for %s replicate %d.", ...
            problemId, replicateIndex);
        initialRows = 1:nInitial;
        assert(max(abs(oldResult.data.X(initialRows, :) - ...
            newResult.data.X(initialRows, :)), [], "all") < 1e-10, ...
            "Initial X differs for %s replicate %d.", ...
            problemId, replicateIndex);
        assert(max(abs(oldResult.data.Y(initialRows, :) - ...
            newResult.data.Y(initialRows, :)), [], "all") < 1e-10, ...
            "Initial Y differs for %s replicate %d.", ...
            problemId, replicateIndex);
        assert(isequal(logical(oldResult.data.isFeasible(initialRows)), ...
            logical(newResult.data.isFeasible(initialRows))), ...
            "Initial labels differ for %s replicate %d.", ...
            problemId, replicateIndex);
        assertEquivalentCoreOptions( ...
            oldResult.options, newResult.options, problemId, replicateIndex);

        oldLabels = logical(oldResult.data.isFeasible);
        newLabels = logical(newResult.data.isFeasible);
        oldFront = ctsemo.pareto2d(oldResult.data.Y(oldLabels, :));
        newFront = ctsemo.pareto2d(newResult.data.Y(newLabels, :));
        oldFrontNormalized = normalizeValues(oldFront, lower, scale);
        newFrontNormalized = normalizeValues(newFront, lower, scale);
        oldFeasibleNormalized = normalizeValues( ...
            oldResult.data.Y(oldLabels, :), lower, scale);
        newFeasibleNormalized = normalizeValues( ...
            newResult.data.Y(newLabels, :), lower, scale);
        assert(all(oldFeasibleNormalized < referencePoint, "all") && ...
            all(newFeasibleNormalized < referencePoint, "all"), ...
            "Fixed reference does not dominate all observations for " + ...
            "%s replicate %d.", problemId, replicateIndex);

        oldHistory = fixedHypervolumeHistory( ...
            oldResult.data.Y, oldLabels, nInitial, lower, scale, ...
            referencePoint);
        newHistory = fixedHypervolumeHistory( ...
            newResult.data.Y, newLabels, nInitial, lower, scale, ...
            referencePoint);
        initialHV = oldHistory(1);
        assert(abs(initialHV - newHistory(1)) < 1e-12, ...
            "Initial hypervolume differs for %s replicate %d.", ...
            problemId, replicateIndex);
        oldFinalHV = oldHistory(end);
        newFinalHV = newHistory(end);
        oldAUC = trapz(0:(numel(oldHistory) - 1), oldHistory) ./ ...
            max(1, numel(oldHistory) - 1);
        newAUC = trapz(0:(numel(newHistory) - 1), newHistory) ./ ...
            max(1, numel(newHistory) - 1);

        [newOverOld, oldOverNew] = bidirectionalCoverage( ...
            newFrontNormalized, oldFrontNormalized, comparisonTolerance);
        oldTiming = extractTiming(oldResult);
        newTiming = extractTiming(newResult);
        newSources = reshape(string( ...
            {newResult.iterations.selectionSource}), [], 1);
        ga = extractGaDiagnostics(newResult);

        row = emptyPairedRow();
        row.ProblemId = problemId;
        row.Dimension = size(oldResult.data.X, 2);
        row.Replicate = double(oldRows.Replicate(replicateIndex));
        row.InitialCount = nInitial;
        row.TotalEvaluations = size(oldResult.data.Y, 1);
        row.OldFeasibleCount = nnz(oldLabels);
        row.NewFeasibleCount = nnz(newLabels);
        row.OldUniqueFrontCount = size(oldFront, 1);
        row.NewUniqueFrontCount = size(newFront, 1);
        row.InitialHV = initialHV;
        row.OldFinalHV = oldFinalHV;
        row.NewFinalHV = newFinalHV;
        row.FinalHVDelta = newFinalHV - oldFinalHV;
        row.FinalHVChangePct = relativeChange( ...
            oldFinalHV, newFinalHV, comparisonTolerance);
        row.ZeroBaselineHVGain = ...
            oldFinalHV <= comparisonTolerance && ...
            newFinalHV > comparisonTolerance;
        row.OldHVGrowth = oldFinalHV - initialHV;
        row.NewHVGrowth = newFinalHV - initialHV;
        row.OldHVAUC = oldAUC;
        row.NewHVAUC = newAUC;
        row.HVAUCDelta = newAUC - oldAUC;
        row.HVAUCChangePct = relativeChange( ...
            oldAUC, newAUC, comparisonTolerance);
        row.ZeroBaselineHVAUCGain = ...
            all(oldAUC <= comparisonTolerance, "all") && ...
            all(newAUC > comparisonTolerance, "all");
        row.NewStrictlyDominatesOldPct = newOverOld;
        row.OldStrictlyDominatesNewPct = oldOverNew;
        row.OldWallTimeSeconds = oldTiming.wall;
        row.NewWallTimeSeconds = newTiming.wall;
        row.OldMeanAcquisitionSeconds = oldTiming.acquisition;
        row.NewMeanAcquisitionSeconds = newTiming.acquisition;
        row.NewPrimarySelections = nnz(newSources == "primary");
        row.NewChallengerSelections = nnz(newSources == "challenger");
        row.NewFallbackSelections = nnz(newSources == "fallback");
        row.GAEligibleIterations = ga.eligible;
        row.GAImprovedOverSeedCount = ga.improved;
        row.GAReturnedSeedBestCount = ga.returnedSeedBest;
        row.GAMeanImprovementOverSeed = ga.meanImprovement;
        pairedRows(end + 1, 1) = row; %#ok<SAGROW>
    end
end

paired = struct2table(pairedRows);
expectedPaired = readtable(fullfile(artifactRoot, ...
    "paired_ga_vs_finite_pool_pf_comparison.csv"), TextType="string");
assertTablesEquivalent(paired, expectedPaired, 1e-9);
writetable(paired, fullfile(outputRoot, ...
    "paired_ga_vs_finite_pool_pf_comparison.csv"));
writetable(struct2table(normalizationRows), normalizationFile);

aggregateRows = repmat(emptyAggregateRow(), 0, 1);
for problemIndex = 1:numel(problemIds)
    problemId = problemIds(problemIndex);
    subset = paired(paired.ProblemId == problemId, :);
    delta = subset.FinalHVDelta;
    oldMedian = median(subset.OldFinalHV);
    newMedian = median(subset.NewFinalHV);
    pairedChangePct = median( ...
        subset.FinalHVChangePct, "omitmissing");
    aucOldMedian = median(subset.OldHVAUC);
    aucNewMedian = median(subset.NewHVAUC);
    pairedAUCChangePct = median( ...
        subset.HVAUCChangePct, "omitmissing");
    wins = nnz(delta > comparisonTolerance);
    losses = nnz(delta < -comparisonTolerance);
    ties = height(subset) - wins - losses;

    row = emptyAggregateRow();
    row.ProblemId = problemId;
    row.Dimension = subset.Dimension(1);
    row.Replicates = height(subset);
    row.OldMedianFinalHV = oldMedian;
    row.NewMedianFinalHV = newMedian;
    row.MedianPairedHVDelta = median(delta);
    row.MedianPairedHVChangePct = pairedChangePct;
    row.HVWins = wins;
    row.HVTies = ties;
    row.HVLosses = losses;
    row.OldMedianHVAUC = aucOldMedian;
    row.NewMedianHVAUC = aucNewMedian;
    row.MedianPairedHVAUCDelta = median(subset.HVAUCDelta);
    row.MedianPairedHVAUCChangePct = pairedAUCChangePct;
    row.ZeroBaselineHVGainCount = nnz(subset.ZeroBaselineHVGain);
    row.ZeroBaselineHVAUCGainCount = nnz(subset.ZeroBaselineHVAUCGain);
    row.MedianNewStrictlyDominatesOldPct = ...
        median(subset.NewStrictlyDominatesOldPct, "omitmissing");
    row.MedianOldStrictlyDominatesNewPct = ...
        median(subset.OldStrictlyDominatesNewPct, "omitmissing");
    row.OldMedianFeasibleCount = median(subset.OldFeasibleCount);
    row.NewMedianFeasibleCount = median(subset.NewFeasibleCount);
    row.ChallengerOverrideRate = sum(subset.NewChallengerSelections) ./ ...
        max(1, sum(subset.NewPrimarySelections + ...
        subset.NewChallengerSelections));
    row.FallbackRate = sum(subset.NewFallbackSelections) ./ ...
        sum(subset.TotalEvaluations - subset.InitialCount);
    row.GAImprovedOverSeedRate = sum(subset.GAImprovedOverSeedCount) ./ ...
        max(1, sum(subset.GAEligibleIterations));
    row.MedianAcquisitionTimeRatio = median( ...
        subset.NewMeanAcquisitionSeconds ./ ...
        subset.OldMeanAcquisitionSeconds);
    row.Assessment = classifyResult( ...
        pairedChangePct, median(subset.HVAUCDelta), wins, losses, ...
        row.ZeroBaselineHVGainCount);
    aggregateRows(end + 1, 1) = row; %#ok<SAGROW>
end

aggregate = struct2table(aggregateRows);
expectedAggregate = readtable(fullfile(artifactRoot, ...
    "problem_ga_vs_finite_pool_pf_comparison.csv"), TextType="string");
assertTablesEquivalent(aggregate, expectedAggregate, 1e-9);
writetable(aggregate, fullfile(outputRoot, ...
    "problem_ga_vs_finite_pool_pf_comparison.csv"));

interaction = makeDimensionInteractions(paired, comparisonTolerance);
writetable(interaction, fullfile(outputRoot, ...
    "dimension_interaction_ga_benefit.csv"));

% Front overlays require the private raw finite-primary MAT records and are
% intentionally excluded. The public paired tables retain the same reductions.
plotHypervolumeChanges(paired, problemIds, outputRoot);
plotDimensionInteractions(interaction, outputRoot);

disp(aggregate(:, ["ProblemId", "Dimension", ...
    "OldMedianFinalHV", "NewMedianFinalHV", ...
    "MedianPairedHVChangePct", "HVWins", "HVTies", "HVLosses", ...
    "MedianPairedHVAUCChangePct", "ChallengerOverrideRate", ...
    "GAImprovedOverSeedRate", "Assessment"]));

function assertTablesEquivalent(actual, expected, tolerance)
assert(isequal(actual.Properties.VariableNames, ...
    expected.Properties.VariableNames) && height(actual) == height(expected), ...
    "Recomputed ablation table schema differs from the retained authority.");
for variable = string(actual.Properties.VariableNames)
    a = actual.(variable);
    b = expected.(variable);
    if isnumeric(a) || islogical(a)
        a = double(a);
        b = double(b);
        equal = (isnan(a) & isnan(b)) | abs(a - b) <= tolerance;
        assert(all(equal, "all"), ...
            "Recomputed values differ for column %s.", variable);
    else
        assert(isequal(string(a), string(b)), ...
            "Recomputed text differs for column %s.", variable);
    end
end
end

function result = compactFiniteResult(evaluations, summaryRow, coreOptions)
problemId = string(summaryRow.ProblemId);
replicate = double(summaryRow.Replicate);
rows = evaluations(evaluations.ProblemId == problemId & ...
    evaluations.Replicate == replicate, :);
rows = sortrows(rows, "EvaluationIndex");
assert(height(rows) == double(summaryRow.TotalEvaluations), ...
    "Finite-primary row count differs for %s replicate %d.", ...
    problemId, replicate);
dimension = double(summaryRow.Dimension);
inputNames = "X" + string(1:dimension);
result = struct();
result.meta = struct("wallTimeSeconds", double(summaryRow.WallTimeSeconds));
result.data = struct( ...
    "X", table2array(rows(:, inputNames)), ...
    "Y", [rows.Objective1, rows.Objective2], ...
    "constraintValues", rows.ConstraintValue, ...
    "isFeasible", logical(rows.IsFeasible), ...
    "nInitial", double(summaryRow.InitialCount));

sequential = rows(~logical(rows.IsInitial), :);
iterationTemplate = struct( ...
    "selectionSource", "", ...
    "timing", struct("acquisitionSeconds", NaN));
result.iterations = repmat(iterationTemplate, height(sequential), 1);
for index = 1:height(sequential)
    result.iterations(index).selectionSource = ...
        string(sequential.SelectionSource(index));
    result.iterations(index).timing.acquisitionSeconds = ...
        double(sequential.AcquisitionSeconds(index));
end
result.options = coreOptions;
if isfield(result.options, "primarySearchMethod")
    result.options = rmfield(result.options, "primarySearchMethod");
end
result.options.seed = double(summaryRow.SolverSeed);
result.options.primarySearch = struct("method", "pool");
end

function row = emptyPairedRow()
row = struct( ...
    "ProblemId", "", "Dimension", NaN, "Replicate", NaN, ...
    "InitialCount", NaN, "TotalEvaluations", NaN, ...
    "OldFeasibleCount", NaN, "NewFeasibleCount", NaN, ...
    "OldUniqueFrontCount", NaN, "NewUniqueFrontCount", NaN, ...
    "InitialHV", NaN, "OldFinalHV", NaN, "NewFinalHV", NaN, ...
    "FinalHVDelta", NaN, "FinalHVChangePct", NaN, ...
    "OldHVGrowth", NaN, "NewHVGrowth", NaN, ...
    "OldHVAUC", NaN, "NewHVAUC", NaN, ...
    "HVAUCDelta", NaN, "HVAUCChangePct", NaN, ...
    "ZeroBaselineHVGain", false, "ZeroBaselineHVAUCGain", false, ...
    "NewStrictlyDominatesOldPct", NaN, ...
    "OldStrictlyDominatesNewPct", NaN, ...
    "OldWallTimeSeconds", NaN, "NewWallTimeSeconds", NaN, ...
    "OldMeanAcquisitionSeconds", NaN, ...
    "NewMeanAcquisitionSeconds", NaN, ...
    "NewPrimarySelections", NaN, "NewChallengerSelections", NaN, ...
    "NewFallbackSelections", NaN, "GAEligibleIterations", NaN, ...
    "GAImprovedOverSeedCount", NaN, ...
    "GAReturnedSeedBestCount", NaN, ...
    "GAMeanImprovementOverSeed", NaN);
end

function row = emptyAggregateRow()
row = struct( ...
    "ProblemId", "", "Dimension", NaN, "Replicates", NaN, ...
    "OldMedianFinalHV", NaN, "NewMedianFinalHV", NaN, ...
    "MedianPairedHVDelta", NaN, "MedianPairedHVChangePct", NaN, ...
    "HVWins", NaN, "HVTies", NaN, "HVLosses", NaN, ...
    "OldMedianHVAUC", NaN, "NewMedianHVAUC", NaN, ...
    "MedianPairedHVAUCDelta", NaN, ...
    "MedianPairedHVAUCChangePct", NaN, ...
    "ZeroBaselineHVGainCount", NaN, ...
    "ZeroBaselineHVAUCGainCount", NaN, ...
    "MedianNewStrictlyDominatesOldPct", NaN, ...
    "MedianOldStrictlyDominatesNewPct", NaN, ...
    "OldMedianFeasibleCount", NaN, "NewMedianFeasibleCount", NaN, ...
    "ChallengerOverrideRate", NaN, "FallbackRate", NaN, ...
    "GAImprovedOverSeedRate", NaN, ...
    "MedianAcquisitionTimeRatio", NaN, "Assessment", "");
end

function pathValue = resolveResultFile(storedPath, campaignRoot)
pathValue = string(storedPath);
normalized = replace(pathValue, "/", filesep);
marker = filesep + "runs" + filesep;
location = strfind(lower(normalized), lower(marker));
if ~isempty(location)
    suffix = extractAfter(normalized, ...
        location(end) + strlength(marker) - 1);
    rebasedPath = fullfile(campaignRoot, "runs", suffix);
    if isfile(rebasedPath)
        pathValue = rebasedPath;
        return
    end
end
if isfile(pathValue)
    return
end
error("cTSEMO:Comparison:CannotResolveResult", ...
    "Cannot resolve stored result path '%s' below %s.", ...
    storedPath, campaignRoot);
end

function assertEquivalentCoreOptions(oldOptions, newOptions, ...
        problemId, replicate)
assert(double(oldOptions.maxEvaluations) == ...
    double(newOptions.maxEvaluations), ...
    "Sequential budget option differs for %s replicate %d.", ...
    problemId, replicate);
assert(double(oldOptions.seed) == double(newOptions.seed), ...
    "Solver seed option differs for %s replicate %d.", ...
    problemId, replicate);
commonFields = ["feasibility", "candidates", "objectiveGP", "pof", ...
    "acquisition", "masks", "challengers", "fallback"];
for fieldIndex = 1:numel(commonFields)
    field = commonFields(fieldIndex);
    assert(isfield(oldOptions, field) && isfield(newOptions, field) && ...
        strcmp(jsonencode(oldOptions.(field)), ...
        jsonencode(newOptions.(field))), ...
        "Core option '%s' differs for %s replicate %d.", ...
        field, problemId, replicate);
end
oldMethod = "pool";
if isfield(oldOptions, "primarySearch") && ...
        isfield(oldOptions.primarySearch, "method")
    oldMethod = string(oldOptions.primarySearch.method);
end
assert(oldMethod == "pool", ...
    "Archived primary method is not finite-pool for %s replicate %d.", ...
    problemId, replicate);
assert(isfield(newOptions, "primarySearch") && ...
    isfield(newOptions.primarySearch, "method") && ...
    string(newOptions.primarySearch.method) == "ga", ...
    "Current primary method is not GA for %s replicate %d.", ...
    problemId, replicate);
end

function values = normalizeValues(values, lower, scale)
values = (double(values) - lower) ./ scale;
end

function history = fixedHypervolumeHistory( ...
        Y, labels, nInitial, lower, scale, referencePoint)
nSequential = size(Y, 1) - nInitial;
history = zeros(nSequential + 1, 1);
for step = 0:nSequential
    lastRow = nInitial + step;
    feasible = Y(1:lastRow, :);
    feasible = feasible(labels(1:lastRow), :);
    history(step + 1) = ctsemo.hypervolume2d( ...
        normalizeValues(feasible, lower, scale), referencePoint);
end
end

function [aOverB, bOverA] = bidirectionalCoverage(A, B, tolerance)
aOverB = strictCoverage(A, B, tolerance);
bOverA = strictCoverage(B, A, tolerance);
end

function percentage = strictCoverage(A, B, tolerance)
if isempty(B)
    percentage = NaN;
    return
end
dominated = false(size(B, 1), 1);
for pointIndex = 1:size(B, 1)
    target = B(pointIndex, :);
    dominated(pointIndex) = any( ...
        all(A <= target + tolerance, 2) & ...
        any(A < target - tolerance, 2));
end
percentage = 100 .* mean(dominated);
end

function timing = extractTiming(result)
timing = struct("wall", double(result.meta.wallTimeSeconds), ...
    "acquisition", NaN);
if ~isempty(result.iterations) && ...
        isfield(result.iterations, "timing")
    values = arrayfun(@(record) ...
        double(record.timing.acquisitionSeconds), result.iterations);
    timing.acquisition = mean(values);
end
end

function diagnostics = extractGaDiagnostics(result)
diagnostics = struct("eligible", 0, "improved", 0, ...
    "returnedSeedBest", 0, "meanImprovement", NaN);
improvements = zeros(0, 1);
for iterationIndex = 1:numel(result.iterations)
    record = result.iterations(iterationIndex);
    if ~isfield(record, "primarySearch") || ...
            ~isstruct(record.primarySearch)
        continue
    end
    search = record.primarySearch;
    if ~isfield(search, "method") || ~isfield(search, "status") || ...
            string(search.method) ~= "ga" || ...
            string(search.status) ~= "completed" || ...
            ~isfield(search, "improvementOverSeed") || ...
            isempty(search.improvementOverSeed) || ...
            ~isscalar(search.improvementOverSeed) || ...
            ~isfinite(double(search.improvementOverSeed))
        continue
    end
    improvement = double(search.improvementOverSeed);
    diagnostics.eligible = diagnostics.eligible + 1;
    diagnostics.improved = diagnostics.improved + (improvement > 1e-12);
    improvements(end + 1, 1) = improvement; %#ok<AGROW>
    if isfield(search, "returnedSeedBest") && ...
            isscalar(search.returnedSeedBest)
        diagnostics.returnedSeedBest = diagnostics.returnedSeedBest + ...
            logical(search.returnedSeedBest);
    end
end
if ~isempty(improvements)
    diagnostics.meanImprovement = mean(improvements);
end
end

function assessment = classifyResult( ...
        changePct, aucDelta, wins, losses, zeroBaselineGains)
if zeroBaselineGains > 0 && wins >= 4 && losses == 0 && aucDelta >= 0
    assessment = "directional improvement with zero-baseline cases";
elseif zeroBaselineGains > 0
    assessment = "mixed; includes zero-baseline gains";
elseif isfinite(changePct) && changePct >= 5 && wins >= 4 && aucDelta >= 0
    assessment = "strong improvement";
elseif isfinite(changePct) && changePct >= 2 && wins >= 4 && aucDelta >= 0
    assessment = "practical improvement";
elseif isfinite(changePct) && changePct <= -5 && losses >= 4
    assessment = "material regression";
elseif isfinite(changePct) && changePct <= -2 && losses >= 4
    assessment = "regression concern";
elseif isfinite(changePct) && abs(changePct) < 2
    assessment = "effectively tied";
else
    assessment = "mixed";
end
end

function interaction = makeDimensionInteractions(paired, tolerance)
families = ["CF1"; "C2DTLZ2"; "MW7"];
lowIds = ["CF1_D4"; "C2DTLZ2_D4_R02"; "MW7_D4"];
highIds = ["CF1_D10"; "C2DTLZ2_D6_R02"; "MW7_D6"];
rows = repmat(struct("Family", "", "Replicate", NaN, ...
    "LowDimension", NaN, "HighDimension", NaN, ...
    "LowDimensionRelativeHVChangePct", NaN, ...
    "HighDimensionRelativeHVChangePct", NaN, ...
    "InteractionPctPoints", NaN), 0, 1);
for familyIndex = 1:numel(families)
    low = sortrows(paired(paired.ProblemId == lowIds(familyIndex), :), ...
        "Replicate");
    high = sortrows(paired(paired.ProblemId == highIds(familyIndex), :), ...
        "Replicate");
    assert(isequal(low.Replicate, high.Replicate), ...
        "Dimension-pair replicate identities differ for %s.", ...
        families(familyIndex));
    for replicateIndex = 1:height(low)
        lowRelative = relativeChange( ...
            low.OldFinalHV(replicateIndex), ...
            low.NewFinalHV(replicateIndex), tolerance);
        highRelative = relativeChange( ...
            high.OldFinalHV(replicateIndex), ...
            high.NewFinalHV(replicateIndex), tolerance);
        row = struct("Family", families(familyIndex), ...
            "Replicate", low.Replicate(replicateIndex), ...
            "LowDimension", low.Dimension(replicateIndex), ...
            "HighDimension", high.Dimension(replicateIndex), ...
            "LowDimensionRelativeHVChangePct", lowRelative, ...
            "HighDimensionRelativeHVChangePct", highRelative, ...
            "InteractionPctPoints", highRelative - lowRelative);
        rows(end + 1, 1) = row; %#ok<AGROW>
    end
end
interaction = struct2table(rows);
end

function value = relativeChange(oldValue, newValue, tolerance)
value = NaN;
if oldValue > tolerance
    value = 100 .* (newValue - oldValue) ./ oldValue;
elseif oldValue <= tolerance && newValue <= tolerance
    value = 0;
end
end

function plotHypervolumeChanges(paired, problemIds, outputRoot)
figureHandle = figure("Visible", "off", "Color", "w", ...
    "Position", [100, 100, 1450, 800]);
layout = tiledlayout(figureHandle, 2, 1, ...
    "TileSpacing", "compact", "Padding", "compact");
labels = strings(numel(problemIds), 1);
dimensions = zeros(numel(problemIds), 1);
displayNames = ["Welded beam"; "CF1"; "CF1"; ...
    "C2-DTLZ2"; "C2-DTLZ2"; "MW7"; "MW7"];
for index = 1:numel(problemIds)
    subset = paired(paired.ProblemId == problemIds(index), :);
    dimensions(index) = subset.Dimension(1);
    labels(index) = displayNames(index) + " D" + string(dimensions(index));
end

metrics = {"FinalHVDelta", "HVAUCDelta"};
yLabels = {"final normalized HV change", ...
    "normalized HV-history AUC change"};
for panel = 1:2
    axesHandle = nexttile(layout);
    hold(axesHandle, "on");
    for problemIndex = 1:numel(problemIds)
        subset = sortrows( ...
            paired(paired.ProblemId == problemIds(problemIndex), :), ...
            "Replicate");
        values = subset.(metrics{panel});
        jitter = linspace(-0.11, 0.11, numel(values)).';
        scatter(axesHandle, problemIndex + jitter, values, 36, ...
            [0.15, 0.43, 0.72], "filled");
        plot(axesHandle, problemIndex, median(values), "_", ...
            "Color", [0.85, 0.20, 0.10], ...
            "MarkerSize", 20, "LineWidth", 2.2);
    end
    yline(axesHandle, 0, "k-");
    xlim(axesHandle, [0.5, numel(problemIds) + 0.5]);
    xticks(axesHandle, 1:numel(problemIds));
    xticklabels(axesHandle, labels);
    grid(axesHandle, "on");
    ylabel(axesHandle, yLabels{panel});
end
exportgraphics(figureHandle, fullfile(outputRoot, ...
    "ga_vs_finite_pool_highdim_hv_changes.png"), "Resolution", 300);
exportgraphics(figureHandle, fullfile(outputRoot, ...
    "ga_vs_finite_pool_highdim_hv_changes.pdf"), ...
    "ContentType", "vector");
close(figureHandle);
end

function plotDimensionInteractions(interaction, outputRoot)
families = ["CF1"; "C2DTLZ2"; "MW7"];
labels = ["CF1: D4 to D10"; ...
    "C2-DTLZ2: D4 to D6"; "MW7: D4 to D6"];
figureHandle = figure("Visible", "off", "Color", "w", ...
    "Position", [120, 120, 1050, 520]);
axesHandle = axes(figureHandle);
hold(axesHandle, "on");
for familyIndex = 1:numel(families)
    subset = sortrows( ...
        interaction(interaction.Family == families(familyIndex), :), ...
        "Replicate");
    values = subset.InteractionPctPoints;
    valid = isfinite(values);
    jitter = linspace(-0.10, 0.10, numel(values)).';
    scatter(axesHandle, familyIndex + jitter(valid), values(valid), 44, ...
        [0.15, 0.43, 0.72], "filled");
    if any(valid)
        plot(axesHandle, familyIndex, median(values(valid)), "_", ...
            "Color", [0.85, 0.20, 0.10], ...
            "MarkerSize", 22, "LineWidth", 2.2);
    end
end
yline(axesHandle, 0, "k-");
xlim(axesHandle, [0.5, numel(families) + 0.5]);
xticks(axesHandle, 1:numel(families));
xticklabels(axesHandle, labels);
ylabel(axesHandle, ...
    "high-D minus low-D relative HV change (percentage points)");
title(axesHandle, ...
    "Dimension interaction of GA-primary hypervolume change", ...
    "FontWeight", "bold");
subtitle(axesHandle, ...
    "Positive values indicate a larger GA benefit in the higher-dimensional family member");
grid(axesHandle, "on");
exportgraphics(figureHandle, fullfile(outputRoot, ...
    "ga_dimension_interaction.png"), "Resolution", 300);
exportgraphics(figureHandle, fullfile(outputRoot, ...
    "ga_dimension_interaction.pdf"), "ContentType", "vector");
close(figureHandle);
end
