function options = cTSEMOOptions(varargin)
%CTSEMOOPTIONS Create and validate lightweight cTSEMO options.
%   OPTIONS = CTSEMOOPTIONS() returns the release defaults.
%
%   OPTIONS = CTSEMOOPTIONS(OVERRIDES) applies a scalar structure of
%   overrides. Nested fields are merged recursively. Unknown fields are
%   rejected so that misspelled settings cannot silently change a run.
%
%   OPTIONS = CTSEMOOPTIONS("release", OVERRIDES) also accepts an explicit
%   profile name. The shipped implementation currently has one canonical
%   profile: "release".
%
%   RELEASE SCHEMA
%   General:
%     profile, maxEvaluations, seed
%   Feasibility input:
%     feasibility.inputEncoding
%   Candidate search:
%     candidates.primaryCount, includeCorners, maxCornerDimension,
%     duplicateTolerance
%     challengers.enabled, count, scoreCompletePools
%   Objective Gaussian processes:
%     objectiveGP.kernel, nFeatures, jitter, standardizeY
%   Clipped binary feasibility score:
%     pof.rawInfeasible, rawFeasible, priorMean, kernel,
%     baseLengthScale, localStrength, localNeighbors,
%     maxLengthScaleMultiplier, jitter, clipBounds
%   Acquisition and anti-clustering:
%     acquisition.pofPower, epsilon, backgroundQuantile,
%     backgroundScale, minPositiveHVI
%     masks.design.enabled, radiusScale, floor
%     masks.codomain.enabled, radiusScale, floor
%   Liveness fallback:
%     fallback.enabled, triggerTolerance, minPoF, distanceScale,
%     distanceWeight
%   Logging:
%     logging.level, directory, checkpoint, saveEveryIteration
%
%   maxEvaluations counts new sequential evaluations after X0. An empty
%   pof.baseLengthScale and pof.localNeighbors request data-adaptive values;
%   pof.localStrength = 0 gives the stationary-length special case. Raw PoF
%   targets must bracket [0,1], the prior must be strictly between them, and
%   pof.jitter must lie in [0,1e-4]. See also cTSEMO.

    [profile, overrides] = parseInputs(varargin{:});

    switch profile
        case "release"
            options = releaseDefaults();
        otherwise
            error("cTSEMO:Options:UnknownProfile", ...
                "Unknown cTSEMO profile '%s'. The supported profile is 'release'.", ...
                profile);
    end

    options.profile = profile;
    options = mergeKnownFields(options, overrides, "options");
    options = canonicalizeText(options);
    validateOptions(options);
end

function [profile, overrides] = parseInputs(varargin)
    profile = "release";
    overrides = struct();

    if nargin > 2
        error("cTSEMO:Options:TooManyInputs", ...
            "cTSEMOOptions accepts at most a profile and an override structure.");
    end

    if nargin == 1
        value = varargin{1};
        if isstruct(value)
            overrides = value;
        else
            profile = textScalar(value, "profile");
        end
    elseif nargin == 2
        profile = textScalar(varargin{1}, "profile");
        overrides = varargin{2};
    end

    if ~(isstruct(overrides) && isscalar(overrides))
        error("cTSEMO:Options:InvalidOverrides", ...
            "Option overrides must be a scalar structure.");
    end
end

function options = releaseDefaults()
    options = struct();
    options.profile = "release";

    % Number of new sequential evaluations after the supplied initial data.
    options.maxEvaluations = 60;
    options.seed = 1;

    options.feasibility = struct( ...
        "inputEncoding", "auto");

    options.candidates = struct( ...
        "primaryCount", 1024, ...
        "includeCorners", true, ...
        "maxCornerDimension", 4, ...
        "duplicateTolerance", 1.0e-9);

    options.objectiveGP = struct( ...
        "kernel", "matern32", ...
        "nFeatures", 256, ...
        "jitter", 1.0e-8, ...
        "standardizeY", true);

    options.pof = struct( ...
        "rawInfeasible", -0.25, ...
        "rawFeasible", 1.25, ...
        "priorMean", 0.5, ...
        "kernel", "matern32", ...
        "baseLengthScale", [], ...
        "localStrength", 1.0, ...
        "localNeighbors", [], ...
        "maxLengthScaleMultiplier", 3.0, ...
        "jitter", 1.0e-10, ...
        "clipBounds", [0.0, 1.0]);

    options.acquisition = struct( ...
        "pofPower", 1.0, ...
        "epsilon", 0.0, ...
        "backgroundQuantile", 0.25, ...
        "backgroundScale", 0.25, ...
        "minPositiveHVI", 1.0e-12);

    options.masks = struct();
    options.masks.design = struct( ...
        "enabled", true, ...
        "radiusScale", 0.02, ...
        "floor", 0.0);
    options.masks.codomain = struct( ...
        "enabled", true, ...
        "radiusScale", 0.05, ...
        "floor", 0.0);

    options.challengers = struct( ...
        "enabled", true, ...
        "count", 512, ...
        "scoreCompletePools", true);

    options.fallback = struct( ...
        "enabled", true, ...
        "triggerTolerance", 1.0e-12, ...
        "minPoF", 0.60, ...
        "distanceScale", 0.10, ...
        "distanceWeight", 1.0);

    options.logging = struct( ...
        "level", "summary", ...
        "directory", "", ...
        "checkpoint", true, ...
        "saveEveryIteration", false);
end

function merged = mergeKnownFields(defaults, overrides, path)
    merged = defaults;
    names = fieldnames(overrides);

    for index = 1:numel(names)
        name = names{index};
        childPath = path + "." + string(name);
        if ~isfield(defaults, name)
            error("cTSEMO:Options:UnknownField", ...
                "Unknown option '%s'. Check the field name and nesting.", ...
                childPath);
        end

        defaultValue = defaults.(name);
        overrideValue = overrides.(name);
        if isstruct(defaultValue)
            if ~(isstruct(overrideValue) && isscalar(overrideValue))
                error("cTSEMO:Options:InvalidNestedValue", ...
                    "Option '%s' must be a scalar structure.", childPath);
            end
            merged.(name) = mergeKnownFields(defaultValue, overrideValue, childPath);
        else
            merged.(name) = overrideValue;
        end
    end
end

function options = canonicalizeText(options)
    options.profile = textScalar(options.profile, "options.profile");
    options.feasibility.inputEncoding = textScalar( ...
        options.feasibility.inputEncoding, "options.feasibility.inputEncoding");
    options.objectiveGP.kernel = textScalar( ...
        options.objectiveGP.kernel, "options.objectiveGP.kernel");
    options.pof.kernel = textScalar(options.pof.kernel, "options.pof.kernel");
    options.logging.level = textScalar( ...
        options.logging.level, "options.logging.level");
    options.logging.directory = textScalar( ...
        options.logging.directory, "options.logging.directory");
end

function validateOptions(options)
    mustBeMember(options.profile, "release");

    validateattributes(options.maxEvaluations, {'numeric'}, ...
        {'scalar', 'integer', 'nonnegative', 'finite'}, ...
        mfilename, "options.maxEvaluations");
    validateattributes(options.seed, {'numeric'}, ...
        {'scalar', 'integer', 'nonnegative', 'finite', '<=', 2^32 - 1}, ...
        mfilename, "options.seed");

    mustBeMember(options.feasibility.inputEncoding, ...
        ["auto", "continuousInequality", "feasibleIsOne", "feasibleIsZero"]);

    validateattributes(options.candidates.primaryCount, {'numeric'}, ...
        {'scalar', 'integer', 'positive', 'finite'}, ...
        mfilename, "options.candidates.primaryCount");
    validateLogicalScalar(options.candidates.includeCorners, ...
        "options.candidates.includeCorners");
    validateattributes(options.candidates.maxCornerDimension, {'numeric'}, ...
        {'scalar', 'integer', 'nonnegative', 'finite'}, ...
        mfilename, "options.candidates.maxCornerDimension");
    validateattributes(options.candidates.duplicateTolerance, {'numeric'}, ...
        {'scalar', 'positive', 'finite'}, ...
        mfilename, "options.candidates.duplicateTolerance");

    mustBeMember(options.objectiveGP.kernel, "matern32");
    validateattributes(options.objectiveGP.nFeatures, {'numeric'}, ...
        {'scalar', 'integer', 'positive', 'finite'}, ...
        mfilename, "options.objectiveGP.nFeatures");
    validateattributes(options.objectiveGP.jitter, {'numeric'}, ...
        {'scalar', 'positive', 'finite'}, ...
        mfilename, "options.objectiveGP.jitter");
    validateLogicalScalar(options.objectiveGP.standardizeY, ...
        "options.objectiveGP.standardizeY");

    validateattributes(options.pof.rawInfeasible, {'numeric'}, ...
        {'scalar', 'real', 'finite'}, mfilename, "options.pof.rawInfeasible");
    validateattributes(options.pof.rawFeasible, {'numeric'}, ...
        {'scalar', 'real', 'finite'}, mfilename, "options.pof.rawFeasible");
    validateattributes(options.pof.priorMean, {'numeric'}, ...
        {'scalar', 'real', 'finite', '>=', 0, '<=', 1}, ...
        mfilename, "options.pof.priorMean");
    if options.pof.rawInfeasible > 0 || ...
            options.pof.rawFeasible < 1 || ...
            options.pof.rawInfeasible >= options.pof.rawFeasible
        error("cTSEMO:Options:InvalidPoFTargets", ...
            "PoF targets must be ordered and bracket [0,1]: " + ...
            "rawInfeasible <= 0 and rawFeasible >= 1.");
    end
    if options.pof.priorMean <= options.pof.rawInfeasible || ...
            options.pof.priorMean >= options.pof.rawFeasible
        error("cTSEMO:Options:InvalidPoFPrior", ...
            "options.pof.priorMean must lie strictly between the raw targets.");
    end
    mustBeMember(options.pof.kernel, "matern32");
    if ~(isempty(options.pof.baseLengthScale) || ...
            (isnumeric(options.pof.baseLengthScale) && ...
            isscalar(options.pof.baseLengthScale) && ...
            isreal(options.pof.baseLengthScale) && ...
            isfinite(options.pof.baseLengthScale) && ...
            options.pof.baseLengthScale > 0))
        error("cTSEMO:Options:InvalidBaseLengthScale", ...
            "options.pof.baseLengthScale must be empty (adaptive) or positive.");
    end
    validateattributes(options.pof.localStrength, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'}, ...
        mfilename, "options.pof.localStrength");
    if ~(isempty(options.pof.localNeighbors) || ...
            (isnumeric(options.pof.localNeighbors) && ...
            isscalar(options.pof.localNeighbors) && ...
            isfinite(options.pof.localNeighbors) && ...
            options.pof.localNeighbors >= 1 && ...
            fix(options.pof.localNeighbors) == options.pof.localNeighbors))
        error("cTSEMO:Options:InvalidLocalNeighbors", ...
            "options.pof.localNeighbors must be empty (adaptive) or a positive integer.");
    end
    validateattributes(options.pof.maxLengthScaleMultiplier, {'numeric'}, ...
        {'scalar', 'finite', '>=', 1}, ...
        mfilename, "options.pof.maxLengthScaleMultiplier");
    validateattributes(options.pof.jitter, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'}, mfilename, "options.pof.jitter");
    if options.pof.jitter > 1.0e-4
        error("cTSEMO:Options:InvalidPoFJitter", ...
            "options.pof.jitter must lie in [0,1e-4].");
    end
    validateattributes(options.pof.clipBounds, {'numeric'}, ...
        {'row', 'numel', 2, 'real', 'finite'}, ...
        mfilename, "options.pof.clipBounds");
    if ~isequal(options.pof.clipBounds, [0, 1])
        error("cTSEMO:Options:InvalidClipBounds", ...
            "The shipped feasibility score must use clip bounds [0, 1].");
    end

    validateattributes(options.acquisition.pofPower, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'}, ...
        mfilename, "options.acquisition.pofPower");
    validateattributes(options.acquisition.epsilon, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'}, ...
        mfilename, "options.acquisition.epsilon");
    validateattributes(options.acquisition.backgroundQuantile, {'numeric'}, ...
        {'scalar', '>=', 0, '<=', 1, 'finite'}, ...
        mfilename, "options.acquisition.backgroundQuantile");
    validateattributes(options.acquisition.backgroundScale, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'}, ...
        mfilename, "options.acquisition.backgroundScale");
    validateattributes(options.acquisition.minPositiveHVI, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'}, ...
        mfilename, "options.acquisition.minPositiveHVI");

    validateMask(options.masks.design, "options.masks.design");
    validateMask(options.masks.codomain, "options.masks.codomain");

    validateLogicalScalar(options.challengers.enabled, ...
        "options.challengers.enabled");
    validateattributes(options.challengers.count, {'numeric'}, ...
        {'scalar', 'integer', 'nonnegative', 'finite'}, ...
        mfilename, "options.challengers.count");
    validateLogicalScalar(options.challengers.scoreCompletePools, ...
        "options.challengers.scoreCompletePools");
    if options.challengers.enabled && options.challengers.count == 0
        error("cTSEMO:Options:EmptyChallengerPool", ...
            "A positive challenger count is required when challengers are enabled.");
    end
    validateLogicalScalar(options.fallback.enabled, ...
        "options.fallback.enabled");
    validateattributes(options.fallback.triggerTolerance, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'}, ...
        mfilename, "options.fallback.triggerTolerance");
    validateattributes(options.fallback.minPoF, {'numeric'}, ...
        {'scalar', '>=', 0, '<=', 1, 'finite'}, ...
        mfilename, "options.fallback.minPoF");
    validateattributes(options.fallback.distanceScale, {'numeric'}, ...
        {'scalar', 'positive', 'finite'}, ...
        mfilename, "options.fallback.distanceScale");
    validateattributes(options.fallback.distanceWeight, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'}, ...
        mfilename, "options.fallback.distanceWeight");
    mustBeMember(options.logging.level, ["none", "summary", "full"]);
    validateLogicalScalar(options.logging.checkpoint, ...
        "options.logging.checkpoint");
    validateLogicalScalar(options.logging.saveEveryIteration, ...
        "options.logging.saveEveryIteration");
end

function validateMask(mask, name)
    validateLogicalScalar(mask.enabled, name + ".enabled");
    validateattributes(mask.radiusScale, {'numeric'}, ...
        {'scalar', 'positive', 'finite'}, mfilename, name + ".radiusScale");
    validateattributes(mask.floor, {'numeric'}, ...
        {'scalar', '>=', 0, '<=', 1, 'finite'}, ...
        mfilename, name + ".floor");
end

function validateLogicalScalar(value, name)
    if ~(islogical(value) && isscalar(value))
        error("cTSEMO:Options:ExpectedLogicalScalar", ...
            "%s must be a logical scalar.", name);
    end
end

function value = textScalar(value, name)
    if ischar(value) && isrow(value)
        value = string(value);
    end
    if ~(isstring(value) && isscalar(value) && ~ismissing(value))
        error("cTSEMO:Options:ExpectedTextScalar", ...
            "%s must be a character vector or string scalar.", name);
    end
end

function mustBeMember(value, allowed)
    if ~any(value == allowed)
        error("cTSEMO:Options:InvalidValue", ...
            "Value '%s' is not supported. Allowed values: %s.", ...
            value, strjoin(allowed, ", "));
    end
end
